### DISCUSSION TITLE
Enviornment Variables not Updating

### DISCUSSION THREAD

**Discussion by eiiot** [plausible/analytics#1245] [Self-Hosted Support] [answered]
Hello!

I'm trying to set up Google search console, and I've added GOOGLE_CLIENT_ID to my plausible-conf.env, the page doesn't seem to change. It just says "An extra step is needed to set up your Plausible Analytics Self Hosted for the Google Search Console integration. Find instructions here". Any ideas on what I could be doing wrong?

EDIT:
Okay, this is strange. It looks like the conf options just aren't updating in general. For example, I disabled registration, but when I access my homepage from an incognito window, it still lets me register...

Here's my docker-compose
```
  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env
    restart: unless-stopped
```
