### DISCUSSION TITLE
Cannot start Plausible from a docker compose file on Azure

### DISCUSSION THREAD

**Discussion by guillaumemeyer** [plausible/analytics#1294] [Self-Hosted Support] [answered]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

When hosting the platform on Microsoft Azure App Services, the container provisioning process pulls all the images successfully from the Docker public registry, then stops with an error (probably from `entrypoint.sh`):
```
multi-container unit was not started successfully
...
2021-09-01T11:13:24.001Z INFO  - Container logs from xxx_plausible_0_e338f565 = 2021-09-01T11:12:47.044901638Z 10: line 1: syntax error: unterminated quoted string
2021-09-01T11:12:57.035222652Z 10: line 1: syntax error: unterminated quoted string
2021-09-01T11:13:06.853591019Z 10: line 1: syntax error: unterminated quoted string
```

### Expected behavior

The provisioning should be able to start the container images

### Screenshots

Here's the `docker-compose.yml` file used:
```yaml
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always
  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
  plausible:
    image: plausible/analytics:latest
    restart: always
    ports:
      - "80:8080"
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
volumes:
  event-data:
    driver: local
  geoip:
    driver: local
```

As you can see this is a very streamlined version of the sample docker compose file, to accommodate with the Azure environment limitations of docker compose support.

### Environment

```markdown
- Hosting: Microsoft Azure
- Service: Azure App Services with Docker Compose
```
