### DISCUSSION TITLE
Plausible won't start because of `connection not available`

### DISCUSSION THREAD

**Discussion by simonknittel** [plausible/analytics#1336] [Self-Hosted Support] [answered]
Hey!
I'm having trouble starting Plausible. It seems that both databases are running fine. However, the Plausible container crashes on startup logging the following error:
```
Loading plausible..
Starting dependencies..
Starting repos..
create Plausible.Repo database if it doesn't exist
** (MatchError) no match of right hand side value: {:error, "connection not available and request was dropped from queue after 2973ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. By tracking down slow queries and making sure they are running fast enough
  2. Increasing the pool_size (albeit it increases resource consumption)
  3. Allow requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information
"}
    (plausible 0.0.1) lib/plausible_release.ex:48: anonymous fn/2 in Plausible.Release.createdb/0
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plausible 0.0.1) lib/plausible_release.ex:47: Plausible.Release.createdb/0
    (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.3) lib/code.ex:341: Code.eval_string_with_error_handling/3
```

This is my current docker-compose/stack/swarm setup:
```yml
version: "3.9"

services:

  plausible:
    image: plausible/analytics

    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"

    environment:
      ADMIN_USER_EMAIL: "{{ plausible_admin_email }}"
      ADMIN_USER_NAME: "{{ plausible_admin_name }}"
      ADMIN_USER_PWD: "{{ plausible_admin_password }}"
      BASE_URL: "https://{{ host }}"
      SECRET_KEY_BASE: "{{ plausible_secret_key_base }}"
      DATABASE_URL: "postgres://postgres:{{ postgres_password }}@plausible_db:5432/plausible_dev"
      CLICKHOUSE_DATABASE_URL: "http://plausible_events_db:8123/plausible_dev"
      MAILER_EMAIL: "{{ smtp_from }}"
      SMTP_HOST_ADDR: "{{ smtp_host }}"
      SMTP_HOST_PORT: "{{ smtp_port }}"
      SMTP_HOST_SSL_ENABLED: "true"
      SMTP_USER_NAME: "{{ smtp_user }}"
      SMTP_USER_PWD: "{{ smtp_password }}"
      DISABLE_REGISTRATION: "true"

    networks:
      - traefik_overlay
      - plausible_overlay

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          memory: 100M

      labels:
        traefik.enable: "true"

        traefik.http.services.plausible.loadbalancer.server.port: 8000

        traefik.http.routers.plausible_https.rule: Host(`{{ host }}`)
        traefik.http.routers.plausible_https.entrypoints: websecure
        traefik.http.routers.plausible_https.tls: "true"
        traefik.http.routers.plausible_https.tls.certresolver: letsencrypt
        traefik.http.routers.plausible_https.service: plausible

        traefik.http.routers.plausible_http.rule: Host(`{{ host }}`)
        traefik.http.routers.plausible_http.entrypoints: web
        traefik.http.routers.plausible_http.middlewares: redirect-to-https@file
        traefik.http.routers.plausible_http.service: plausible

    depends_on:
      - plausible_db
      - plausible_events_db

  plausible_db:
    image: postgres:13.4-alpine3.14

    networks:
      - plausible_overlay

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          memory: 500M

    volumes:
      - /mnt/glusterfs/volume1/plausible/db-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "{{ postgres_password }}"

  plausible_events_db:
    image: yandex/clickhouse-server:21.9.2.17-alpine

    networks:
      - plausible_overlay

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          memory: 500M

    configs:
      - source: clickhouse_config
        target: /etc/clickhouse-server/config.d/logging.xml
      - source: clickhouse_user_config
        target: /etc/clickhouse-server/users.d/logging.xml

    volumes:
      - /mnt/glusterfs/volume1/plausible/event-data:/var/lib/clickhouse

    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  traefik_overlay:
    external: true
  plausible_overlay:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "true"

# When updating a service config, you have to change it's name so `docker stack
# deploy` can pick up the change.
configs:
  clickhouse_config:
    name: clickhouse_config_{{ clickhouse_config.stat.checksum }}
    file: /mnt/glusterfs/volume1/plausible/clickhouse-config.xml
  clickhouse_user_config:
    name: clickhouse_user_config_{{ clickhouse_user_config.stat.checksum }}
    file: /mnt/glusterfs/volume1/plausible/clickhouse-user-config.xml
```
