### DISCUSSION TITLE
Email reports not sent

### DISCUSSION THREAD

**Discussion by aespasa** [plausible/analytics#1860] [Self-Hosted Support] [answered]
Hello, I have installed Plausible on a Plesk VPS through docker, it works pretty well, but the email reports are not sent. However, the reset password email is  correctly sent. 

SMTP is defined in the docker-compose.yml and also inside the plausible-conf.env files.

**docker-compose.yml**
```
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: smtp-relay.sendinblue.com
      RELAY_PORT: 587
      RELAY_USERNAME:XXXXXXX@XXXXXXX
      RELAY_PASSWORD:XXXXXXXXXXX

  plausible_db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always

  plausible_events_db:
    image: yandex/clickhouse-server:latest
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always

  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env
    restart: always

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
```

**plausible-conf.env**

```
ADMIN_USER_EMAIL=XXXXXXX@XXXXXXX
ADMIN_USER_NAME=XXXXXX
ADMIN_USER_PWD=XXXXXXXXX
BASE_URL=XXXXXXXXXX
SECRET_KEY_BASE=SECRET_KEY
PORT=8000
MAILER_EMAIL=XXXXXXX@XXXXXXX
SMTP_HOST_ADDR=smtp-relay.sendinblue.com
SMTP_HOST_PORT=587
SMTP_USER_NAME=XXXXXXX@XXXXXXX
SMTP_USER_PWD=XXXXXXXXXXX
SMTP_HOST_SSL_ENABLED=false
CRON_ENABLED=true
DISABLE_REGISTRATION=true
```

I don't have any errors except this one:

```
plausible_events_db_1  | 2022.04.26 07:41:02.616812 [ 1 ] {} <Warning> Application: Listen [::]:9005 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 22.1.3.7 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
mail_1                 |     1 LOG: MAIN
mail_1                 |     1   exim 4.89 daemon started: pid=1, -q30m, listening for SMTP on port 25 (IPv6 and IPv4)
mail_1                 |     1 LOG: MAIN
mail_1                 |     1   exim 4.89 daemon started: pid=1, -q30m, listening for SMTP on port 25 (IPv6 and IPv4)
```

What's going on? Did I forget to do something? 

Thank for your help
