### DISCUSSION TITLE
Geodata issue

### DISCUSSION THREAD

**Discussion by AmreshSinha** [plausible/analytics#2002] [Self-Hosted Support]
I have self-hosted plausible on Oracle cloud (Arm64) in Docker and reverse proxying through Traefik.\
Here's my `docker-compose.yml`:
```yaml
version: "3.3"
services:
  mail:
    build:
      context: ../Bytemark-docker-smtp/stretch
      dockerfile: Dockerfile
    # image: bytemark/smtp
    restart: always
    networks:
      - default

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - default

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.4.2.1
    # image: altinity/clickhouse-server:21.12.3.32.altinitydev.arm
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
      - ./clickhouse/clickhouse-issue-15638.xml:/etc/clickhouse-server/config.d/clickhouse-issue-15638.xml:ro
      - ./clickhouse/ssl.xml:/etc/clickhouse-server/config.d/ssl.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - default

  plausible:
    build:
      context: ../plausible-analytics-repo
      dockerfile: Dockerfile
    # image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env
      # mailgun
      - plausible-smtp.env
    networks:
      - default
      - proxy
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.plausible.rule: "Host(`plausible.x-axis.me`)" # change to your domain name
      traefik.http.routers.plausible.entrypoints: "websecure"
      traefik.http.routers.plausible.service: "plausible-service"
      traefik.http.services.plausible-service.loadbalancer.server.port: "8000"
      traefik.http.services.plausible-service.loadbalancer.passhostheader: "true"
      # traefik.http.services.plausible.loadbalancer.server.port: "8000"

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
networks:
  proxy:
    external: true
```

Everything seems to be working fine except the geodata. On the dashboard, the location is empty. My plausible instance is up for around one month now, but still, it's empty. Not sure why. Traefik automatically passes the required header like `X-Forwarded-For`.

Here are the logs:
```
Attaching to plausible_plausible_1, plausible_plausible_events_db_1, plausible_plausible_db_1, plausible_mail_1
mail_1                 |     1 LOG: MAIN
mail_1                 |     1   exim 4.89 daemon started: pid=1, -q30m, listening for SMTP on port 25 (IPv6 and IPv4)
plausible_db_1         |
plausible_db_1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
plausible_db_1         |
plausible_db_1         | 2022-07-10 08:40:29.942 UTC [1] LOG:  starting PostgreSQL 12.11 (Debian 12.11-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
plausible_db_1         | 2022-07-10 08:40:29.943 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
plausible_db_1         | 2022-07-10 08:40:29.943 UTC [1] LOG:  listening on IPv6 address "::", port 5432
plausible_db_1         | 2022-07-10 08:40:29.949 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
plausible_db_1         | 2022-07-10 08:40:29.983 UTC [25] LOG:  database system was shut down at 2022-07-10 08:40:08 UTC
plausible_db_1         | 2022-07-10 08:40:30.001 UTC [1] LOG:  database system is ready to accept connections
plausible_events_db_1  | Processing configuration file '/etc/clickhouse-server/config.xml'.
plausible_events_db_1  | Merging configuration file '/etc/clickhouse-server/config.d/clickhouse-issue-15638.xml'.
plausible_events_db_1  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
plausible_events_db_1  | Merging configuration file '/etc/clickhouse-server/config.d/logging.xml'.
plausible_events_db_1  | Merging configuration file '/etc/clickhouse-server/config.d/ssl.xml'.
plausible_events_db_1  | Logging warning to /var/log/clickhouse-server/clickhouse-server.log
plausible_events_db_1  | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
plausible_events_db_1  | 2022.07.10 08:40:30.339597 [ 1 ] {} <Warning> Context: Linux is not using fast TSC clock source. Performance can be degraded.
plausible_events_db_1  | 2022.07.10 08:40:30.494912 [ 1 ] {} <Warning> Application: Calculated checksum of the binary: 422515D69C0964C6B49D3FA4A54B11FC. There is no information about the reference checksum.
plausible_events_db_1  | 2022.07.10 08:40:30.672524 [ 1 ] {} <Warning> Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 22.4.2.1 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db_1  | 2022.07.10 08:40:30.686421 [ 1 ] {} <Warning> Application: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 22.4.2.1 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db_1  | 2022.07.10 08:40:30.700681 [ 1 ] {} <Warning> Application: Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 22.4.2.1 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db_1  | 2022.07.10 08:40:30.714743 [ 1 ] {} <Warning> Application: Listen [::]:9004 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 22.4.2.1 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db_1  | 2022.07.10 08:40:30.728505 [ 1 ] {} <Warning> Application: Listen [::]:9005 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 22.4.2.1 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_1            | Loading plausible..
plausible_1            | Starting dependencies..
plausible_1            | Starting repos..
plausible_1            | create Plausible.Repo database if it doesn't exist
plausible_1            | create Plausible.ClickhouseRepo database if it doesn't exist
plausible_1            | Creation of Db successful!
plausible_1            | Loading plausible..
plausible_1            | Starting dependencies..
plausible_1            | Starting repos..
plausible_1            | Running migrations for Elixir.Plausible.Repo
plausible_1            | Running migrations for Elixir.Plausible.ClickhouseRepo
plausible_1            | Migrations successful!
plausible_1            | Loading plausible..
plausible_1            | Starting dependencies..
plausible_1            | Starting repos..
plausible_1            | Admin user already exists. I won't override, bailing
plausible_1            | 08:40:43.208 [warning] OTLP exporter failed to initialize with exception :throw:{:application_either_not_started_or_not_ready, :tls_certificate_check}
```

I guess the issue is with the clickhouse server 🤔 because of that warning maybe. Not sure.

Any help is appreciated.
