### DISCUSSION TITLE
Self-Hosted Plausible Deployment Creates Zombie Process

### DISCUSSION THREAD

**Discussion by SidSidSid16** [plausible/analytics#2057] [Self-Hosted Support]
I have deployed Plausible on my DigitalOcean droplet running Ubuntu 20.04.4 LTS.

My `docker-compose.yml` file:
```
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
#    ports:
#      - 8000:8000
    expose:
      - 8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
```

I am using Nginx Proxy Manager as a reverse proxy to serve Plausible, hence the port is exposed.

My `plausible-conf.env` file:

```
ADMIN_USER_EMAIL=<REDACTED>
ADMIN_USER_NAME=sid
ADMIN_USER_PWD=<REDACTED>
DISABLE_REGISTRATION=true
BASE_URL=https://plausible.example.com
SECRET_KEY_BASE=<REDACTED>

MAILER_EMAIL=plausible@example.com
SMTP_HOST_ADDR=smtp.sendgrid.com
SMTP_HOST_PORT=465
SMTP_USER_NAME=apikey
SMTP_USER_PWD=<REDACTED>
SMTP_HOST_SSL_ENABLED=true

GOOGLE_CLIENT_ID=<REDACTED>
GOOGLE_CLIENT_SECRET=<REDACTED>
```

With Plausible running:
```
sid@deployment-server:~/deployments/plausible$ ps aux | grep 'Z'
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
sid       641017  0.0  0.0      0     0 ?        Zs   12:52   0:00 [epmd] <defunct>
sid       641190  0.0  0.2   8160  2356 pts/0    S+   12:55   0:00 grep --color=auto Z
```
There seems to be a zombie process.

This zombie process goes away once the `plausible` service from the `docker-compose` is stopped:
```
sid@deployment-server:~/deployments/plausible$ ps aux | grep 'Z'
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
sid       641017  0.0  0.0      0     0 ?        Zs   12:52   0:00 [epmd] <defunct>
sid       641190  0.0  0.2   8160  2356 pts/0    S+   12:55   0:00 grep --color=auto Z

sid@deployment-server:~/deployments/plausible$ docker-compose stop plausible
Stopping plausible_plausible_1 ... done

sid@deployment-server:~/deployments/plausible$ ps aux | grep 'Z'
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
sid       641348  0.0  0.2   8160  2416 pts/0    S+   12:58   0:00 grep --color=auto Z
```

The zombie process doesn't seem to be using any resources. What may be causing this zombie process, and could this a bug?
