### DISCUSSION TITLE
Provided admin credentials not working

### DISCUSSION THREAD

**Discussion by JackMorganNZ** [plausible/analytics#2390] [Self-Hosted Support]
I have deployed Plausible using the following Docker Compose file for deploying on Docker Swarm, however the two strings I have provided for the admin user email and admin user password do not allow me to login.

I have disabled the SMTP settings for the moment while awaiting for another IT to make a decision but it seems to be unrelated. I did test registering a new account (before I disabled user registratations) and it did throw a 500 error, but did successfully create the account log me in (though I expected it to require email verification...).

```yaml
version: '3.8'

services:
  plausible_db:
    image: postgres:14.5-alpine
    volumes:
      - plausible_db_data:/var/lib/postgresql/data
    networks:
      - plausible
    # healthcheck:
    # Need to pass username/database as root does not exist
    #   test: ['CMD', 'pg_isready']
    environment:
      - POSTGRES_DB=plausible
      - POSTGRES_USER_FILE=/run/secrets/plausible_postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/plausible_postgres_password
    secrets:
      - plausible_postgres_password
      - plausible_postgres_user
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
            - node.role==worker
            - node.labels.role==management
      labels:
        - 'traefik.enable=false'

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    volumes:
      - plausible_event_data:/var/lib/clickhouse
      - plausible_etc_clickhouse_server:/etc/clickhouse-server
    networks:
      - plausible
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
            - node.role==worker
            - node.labels.role==management
      labels:
        - 'traefik.enable=false'

  plausible:
    image: plausible/analytics:1.5.0-rc.0
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    networks:
      - plausible
      - uccser-public
    environment:
      - CONFIG_DIR=/run/secrets
      - SMTP_HOST_PORT=465
      - SMTP_HOST_SSL_ENABLED=false
      - DISABLE_REGISTRATION=true
    healthcheck:
      test:
        ['CMD', 'wget', '-q', '--tries=1', '--spider', 'http://localhost:8000']
    secrets:
      - source: plausible_admin_user_email
        target: /run/secrets/ADMIN_USER_EMAIL
      - source: plausible_admin_user_name
        target: /run/secrets/ADMIN_USER_NAME
      - source: plausible_admin_user_password
        target: /run/secrets/ADMIN_USER_PWD
      - source: plausible_base_url
        target: /run/secrets/BASE_URL
      - source: plausible_secret_key_base
        target: /run/secrets/SECRET_KEY_BASE
      - source: plausible_database_url
        target: /run/secrets/DATABASE_URL
      - source: plausible_mailer_email
        target: /run/secrets/MAILER_EMAIL
      # - source: plausible_smtp_host_addr
      #   target: /run/secrets/SMTP_HOST_ADDR
      # - source: plausible_smtp_user_name
      #   target: /run/secrets/SMTP_USER_NAME
      # - source: plausible_smtp_user_pwd
      #   target: /run/secrets/SMTP_USER_PWD
      # - source: plausible_google_client_id
      #   target: /run/secrets/GOOGLE_CLIENT_ID
      # - source: plausible_google_client_secret
      #   target: /run/secrets/GOOGLE_CLIENT_SECRET
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
            - node.role==worker
            - node.labels.role==management
      labels:
        # Redacted Traefik rules

networks:
  uccser-public:
    external: true
  plausible:
    driver: overlay
    attachable: true

secrets:
  plausible_admin_user_email:
    external: true
  plausible_admin_user_name:
    external: true
  plausible_admin_user_password:
    external: true
  plausible_base_url:
    external: true
  plausible_secret_key_base:
    external: true
  plausible_postgres_user:
    external: true
  plausible_postgres_password:
    external: true
  plausible_database_url:
    external: true
  plausible_mailer_email:
    external: true
  # plausible_smtp_host_addr:
  #   external: true
  # plausible_smtp_user_name:
  #   external: true
  # plausible_smtp_user_pwd:
  #   external: true
  # plausible_google_client_id:
  #   external: true
  # plausible_google_client_secret:
  #   external: true

volumes:
  plausible_db_data:
  plausible_event_data:
  plausible_etc_clickhouse_server:
```

This is based on the work from [Richard Willis](https://richardwillis.info/blog/run-plausible-with-docker-swarm-and-traefik).

The logs do show the account is created successfully:
```
analytics_plausible.1.tcbbt0z9gfim@REDACTED    | Starting dependencies..
analytics_plausible.1.tcbbt0z9gfim@REDACTED    | Starting repos..
analytics_plausible.1.tcbbt0z9gfim@REDACTED    | Running migrations for Elixir.Plausible.Repo
analytics_plausible.1.tcbbt0z9gfim@REDACTED    | Running migrations for Elixir.Plausible.ClickhouseRepo
analytics_plausible.1.tcbbt0z9gfim@REDACTED    | Migrations successful!
analytics_plausible.1.tcbbt0z9gfim@REDACTED    | Loading plausible..
analytics_plausible.1.tcbbt0z9gfim@REDACTED    | Starting dependencies..
analytics_plausible.1.tcbbt0z9gfim@REDACTED    | Starting repos..
analytics_plausible.1.tcbbt0z9gfim@REDACTED    | Admin user created successful!
```

Any ideas on what is missing here?
