### DISCUSSION TITLE
plausible docker image support for linux/arm/v7? Raspberry PI 4

### DISCUSSION THREAD

**Discussion by 1mfaasj** [plausible/analytics#2555] [Self-Hosted Support]
I want to deploy plausible on a raspberry pi 4 with docker compose (selfhosted) but can't get it to work. It seems that the image 'plausible/analytics:' is not made for raspberry. can this be correct?
I also have tried 'plausible/analytics:v1.5.0-rc.1' but it not working either.

the error message is:
`failed to deploy a stack: plausible Pulling no matching manifest for linux/arm/v7 in the manifest list entries
`
my docker compose contains:
```
version: "3.3"
services:
  plausible_db:
    image: postgres:12
    volumes:
      - /srv/dev-disk/blabla/plausible/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always

  plausible_events_db:
    image: altinity/clickhouse-server:21.12.3.32.altinitydev.arm
    volumes:
      - /srv/dev-disk/blabla/plausible/events:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
#      - mail
    ports:
      - 8000:8000
    environment:
#      - ADMIN_USER_EMAIL=myemail@gmail.com
#      - ADMIN_USER_NAME=admin
#      - ADMIN_USER_PWD=password
      - BASE_URL=https://mywebsite.com
      - SECRET_KEY_BASE=BLABLABLA
    restart: always

```
