### DISCUSSION TITLE
Can't start when using Docker Swarm (feature request?)

### DISCUSSION THREAD

**Discussion by sebdanielsson** [plausible/analytics#2634] [Self-Hosted Support] [answered]
I can't get plausible to start when running it as a Docker Swarm service.

I believe the error is that the "hostname" pointing to the Postgres database isn't the same when running it as a Swarm service. Here's the error output for the app service:

```
Loading plausible..
Starting dependencies..
Starting repos..
create Plausible.Repo database if it doesn't exist
20:05:07.026 [error] Postgrex.Protocol (#PID<0.173.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
20:05:07.026 [error] Postgrex.Protocol (#PID<0.172.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
20:05:07.023 [error] GenServer #PID<0.190.0> terminating
** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
    (db_connection 2.4.2) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
20:05:07.104 [error] GenServer #PID<0.197.0> terminating
** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
    (db_connection 2.4.2) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
** (MatchError) no match of right hand side value: {:error, "killed"}
    (plausible 0.0.1) lib/plausible_release.ex:39: anonymous fn/2 in Plausible.Release.createdb/0
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plausible 0.0.1) lib/plausible_release.ex:38: Plausible.Release.createdb/0
    (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
```

**Comment by ruslandoga** [comment, marked as answer]
👋 @SebDanielsson 

Can you please post the Docker Swarm configuration you are using?

**Reply by sebdanielsson** [reply]
> 👋 @SebDanielsson
> 
> Can you please post the Docker Swarm configuration you are using?

Of course, here's my compose-file😊

```yaml
services:
  plausible_db:
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/plausible_postgres_password
    secrets:
      - plausible_postgres_password
    deploy:
      mode: replicated
      replicas: 1
  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    volumes:
      - event_db:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    deploy:
      mode: replicated
      replicas: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  app:
    image: plausible/analytics:v1.5.1
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - "8888:8000"
    environment:
      - BASE_URL=https://plausible.hogwarts.zone
      - DISABLE_REGISTRATION=true
      - SECRET_KEY_BASE=/run/secrets/plausible_secret_key_base
      - GOOGLE_CLIENT_ID=/run/secrets/plausible_google_client_id
      - GOOGLE_CLIENT_SECRET=/run/secrets/plausible_google_client_secretp
      - MAILER_EMAIL=/run/secrets/plausible_mailer_email
      - SMTP_HOST_ADDR=/run/secrets/plausible_smtp_host_addr
      - SMTP_HOST_PORT=587
      - SMTP_USER_NAME=/run/secrets/plausible_smtp_user_name
      - SMTP_USER_PWD=/run/secrets/plausible_smtp_user_pwd
      - SMTP_HOST_SSL_ENABLED=false
      - SMTP_RETRIES=2
    secrets:
      - plausible_secret_key_base
      - plausible_google_client_id
      - plausible_google_client_secret
      - plausible_mailer_email
      - plausible_smtp_host_addr
      - plausible_smtp_user_name
      - plausible_smtp_user_pwd
    deploy:
      mode: replicated
      replicas: 1
volumes:
  db:
    name: plausible_db
  event_db:
    name: plausible_event_db
  geoip:
    name: plausible_geoip

secrets:
  plausible_postgres_password:
    external: true
  plausible_secret_key_base:
    external: true
  plausible_google_client_id:
    external: true
  plausible_google_client_secret:
    external: true
  plausible_mailer_email:
    external: true
  plausible_smtp_host_addr:
    external: true
  plausible_smtp_user_name:
    external: true
  plausible_smtp_user_pwd:
    external: true
```
