### DISCUSSION TITLE
City level geolocation causing Plausible v1.5.1 to crash on startup

### DISCUSSION THREAD

**Discussion by perfectly-preserved-pie** [plausible/analytics#2697] [Self-Hosted Support] [answered]
Hey, I'm following the instructions here: https://github.com/plausible/analytics/discussions/2324#discussioncomment-3857114

But it's crashing with:

```10:49:15.157 [warning] OTLP exporter failed to initialize with exception :throw:{:application_either_not_started_or_not_ready, :tls_certificate_check}
plausible-plausible-1            | {"Kernel pid terminated",application_controller,"{application_start_failure,plausible,{bad_return,{{'Elixir.Plausible.Application',start,[normal,[]]},{'EXIT',{timeout,{'Elixir.Task',await,[#{'__struct__' => 'Elixir.Task',owner => <0.2926.0>,pid => <0.2930.0>,ref => #Ref<0.451273697.225771521.164627>},30000]}}}}}}"}
plausible-plausible-1            | Kernel pid terminated (application_controller) ({application_start_failure,plausible,{bad_return,{{'Elixir.Plausible.Application',start,[normal,[]]},{'EXIT',{timeout,{'Elixir.Task',await,[#{'__struct__' => 'Elixir.Task',owner => <0.2926.0>,pid => <0.2930.0>,ref => #Ref<0.451273697.225771521.164627>},30000]}}}}}})
```

In my `plausible-conf.env` file, I have
```
IP_GEOLOCATION_DB=/etc/app/cities/geolite2-city.mmdb
GEONAMES_SOURCE_FILE=/etc/app/cities/geonames.csv
```

In my `docker-compose.yml` file, I have:
```
plausible:
    hostname: plausible
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    volumes:
      - /appdata/plausible/cities/geolite2-city.mmdb:/etc/app/cities/geolite2-city.mmdb:ro
      - /appdata/plausible/cities/geonames.csv:/etc/app/cities/geonames.csv:ro
    env_file:
      - plausible-conf.env
```

My filesystem structure on the host:
```
redacted:/appdata/plausible/cities$ ls -al
total 187912
drwxr-xr-x 2 root root      4096 Feb 21 12:17 .
drwxr-xr-x 5 root root      4096 Jan  5 20:25 ..
-rw-r--r-- 1 root root  70799360 Feb 21 12:17 geolite2-city.mmdb
-rw-r--r-- 1 root root 121603380 Feb 21 11:38 geonames.csv
```

If I comment out the `GEONAMES_SOURCE_FILE` in the .env file, Plausible works again.

Any idea where I went wrong?
