### DISCUSSION TITLE
I'm getting `curl: (52) Empty reply from server`

### DISCUSSION THREAD

**Discussion by nimit2801** [plausible/analytics#2723] [Self-Hosted Support] [answered]
I followed everything on my windows 10 and it works! But when I'm trying to follow the same guide for self hosting on digital ocean it gives me error when I'm trying to access port 8000 locally

```bash
curl localhost:8000
```
curl: (52) Empty reply from server

**Comment by ruslandoga** [comment]
👋 @nimit2801 

Can you please post your docker-compose.yml, logs from docker compose, and plausible-conf.env here?

**Reply by nimit2801** [reply]
Yeah sure :)

**Comment by nimit2801** [comment]
`docker-compose.yml`
```yaml
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
```

`plausible-conf.env`
```env
BASE_URL=https://ana.idta.in
SECRET_KEY_BASE=h0BvWVzDK3k0UV6jTIhL8Ne7Df8Q/ccM4RsmigCdNKsA6K7IwLddY+gyaOTIhOZ4ccAPHGdzEcOBtsyGWQrFgQ==
```
