### DISCUSSION TITLE
Unable to see Regions and Cities data

### DISCUSSION THREAD

**Discussion by 1kevinson** [plausible/analytics#2886] [Self-Hosted Support] [answered]
Hi every one,

I'm facing an issue right now on my plausible self-hosted instance.
I'm not able to see data from regions and cities of my visitors.

Can someone help please ?
Thank in advance

![CleanShot 2023-04-29 at 10 08 52](https://user-images.githubusercontent.com/59510116/235292305-c2571f5e-ad86-4a64-9cc6-1e8aa9dc71ea.png)
![CleanShot 2023-04-29 at 10 09 07](https://user-images.githubusercontent.com/59510116/235292299-6a1040e8-799d-410d-b92e-b70ba5264ed8.png)

**Comment by ruslandoga** [comment]
👋 @1kevinson 

Can you please post your config files (docker-compose.yml in particular)?

**Reply by 1kevinson** [reply]
Yes, sure.

### Docker compose for my plausible self-hosted

```yaml
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
```

### Docker compose for geoIP

```yaml
version: "3.3"
services:
  plausible:
    depends_on:
      - geoip
    environment:
      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
    volumes:
      - geoip:/geoip:ro

  geoip:
    image: maxmindinc/geoipupdate
    restart: always
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168 # update every 7 days
    env_file:
      geoip/geoip.conf
    volumes:
      - geoip:/usr/share/GeoIP

volumes:
  geoip:
    driver: local
```

**Reply by ruslandoga** [reply]
You seem to be using `GeoLite2-Country` geolocation database which doesn't include city-level info.

**Reply by 1kevinson** [reply, marked as answer]
I change my conf + delete previous containers and associated images, but I dont have Regions and Cities data

### geoip docker compose

```yaml
version: "3.3"
services:
  plausible:
    depends_on:
      - geoip
    environment: 
      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-City.mmdb
    volumes:
      - geoip:/geoip:ro

  geoip:
    image: ghcr.io/maxmind/geoipupdate
    restart: always
    environment:
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-City GeoLite2-Country GeoLite2-ASN'
      - GEOIPUPDATE_FREQUENCY=72 # update every 3 days
    env_file:
      geoip/geoip.conf
    volumes:
      - geoip:/usr/share/GeoIP

volumes:
  geoip:
    driver: local
```
