### DISCUSSION TITLE
Request to update documentation of the 'postgres upgrade guide'

### DISCUSSION THREAD

**Discussion by dtrai2** [plausible/analytics#2961] [Self-Hosted Support]
I recently upgraded my plausible instance and followed the [release notes for v1.5.1](https://github.com/plausible/analytics/releases/tag/v1.5.1). When trying to upgrade my PstgrSQL to 14 I had some difficulty with the [upgrade guide](https://github.com/plausible/hosting/blob/master/upgrade/postgres.md). In step 4 the guide describes making a backup of the postgres `plausible_db` database:

```bash
> docker compose exec plausible_db sh -c "pg_dump -U postgres plausible_db > /backup/plausible_db.bak"
```
and in step 11 that's being loaded again with:

```bash
> docker compose exec plausible_db sh -c "psql -U postgres -d plausible_db < /backup/plausible_db.bak"
```
On my system I didn't had a `plausible_db` database though, mine was called `plausible_dev`. So to align this I tried to make a backup of my `plausible_dev` database, make the upgrade and then load the data back into a new `plausible_db` database, but that didn't work either. When running the plausible instance it didn't had my user data anymore. Only after doing it all again, and creating another `plausible_dev` database after the upgrade and loading the data into that one, it all worked. 

I don't know why on my system I have a `plausible_dev` database, but maybe if I am not the only one it would be good to update the `upgrade guide` such that it gives a hint to look for `plausible_dev` databases as well.

**Comment by ruslandoga** [comment]
👋 @dtrai2 

Could you please share your `plausible_db` and `plausible` sections from `docker-compose.yml`. And `DATABASE_URL` from `plausible-conf.env` (if it's set).

**Reply by ruslandoga** [reply]
I think it'd be nice to first understand why you have `plausible_dev` instead of `plausible_db`

AFAIK `plausible_dev` is the database that is created in `dev` env by default.

**Reply by dtrai2** [reply]
Ah that's true indeed. And I see already it is probably the `DATABASE_URL` in the `plausible-conf.env`. I deployed the instance quite a long time ago and never touched it again. The `DATABASE_URL` is set to `postgres://postgres:postgres@plausible_db:5433/plausible_dev`. I did check the old documentation from one and a half years ago ([see here](https://github.com/plausible/docs/blob/cca4c025b635312e98c6e3a715f7f291108dcf19/docs/self-hosting-configuration.md)) and there it says the default `DATABASE_URL` was `postgres://localhost:5432/plausible_dev`. So it is probably just a relic from old times.

Here are also the requested parts of my `docker-compose.yml` setup:

```yml
plausible_db:
  image: postgres:14-alpine
  restart: always
  volumes:
    - db-data:/var/lib/postgresql/data
  environment:
    - POSTGRES_PASSWORD=<SECRET>
  expose:
    - "5433"
  command: -p 5433
```
```yml
plausible:
  image: plausible/analytics:v1.5.1
  restart: always
  command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
  depends_on:
    - plausible_db
    - plausible_events_db
  ports:
    - 127.0.0.1:8200:8000
  env_file:
    - plausible-conf.env
```

So maybe as a compromise you could add a small hint to the `upgrade guide` that people should look for the database name in `DATABASE_URL` inside the `plausible-conf.env` file before they try to do the backup.
