### DISCUSSION TITLE
v2 migration failing

### DISCUSSION THREAD

**Discussion by convernaticspeter** [plausible/analytics#3035] [Self-Hosted Support] [answered]
Hi! I'm self-hosting and tried to update plausible today.

The docker-image pushed 13 hours ago didn't have the correct clickhouse version. I corrected this in my docker-compose.yml.

It looks like this now:
```
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.8.13.20-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
```

Since updating to the higher clickhouse version tracking works again.

But the migration of the old events fails with this output:
```    
    check-replicas Done!

------------------------------------------------------------------------------
    list-partitions Done!

------------------------------------------------------------------------------
Got the following migration settings:

  - max_threads: 16
  - table_settings: SETTINGS index_granularity = 8192
  - db url: http://plausible_events_db:8123/plausible_events_db
  - cluster?: false
  - partitions to do: ["202205", "202206", "202207", "202208", "202209", "202210", "202211", "202212",
 "202301", "202302", "202303", "202304", "202305", "202306"]
  - start from: 202205
  - stop at: 

Running drop-events-v2
  -> Query: DROP TABLE IF EXISTS events_v2  SYNC

Execute? [y/N]: ** (FunctionClauseError) no function clause matching in String.trim/1    
    
    The following arguments were given to String.trim/1:
    
        # 1
        :eof
    
    (elixir 1.14.3) lib/string.ex:1271: String.trim/1
    lib/plausible/data_migration/numeric_ids.ex:6: Plausible.DataMigration.NumericIDs.confirm/3
    lib/plausible/data_migration/numeric_ids.ex:105: Plausible.DataMigration.NumericIDs.run/1
    nofile:1: (file)
    (stdlib 4.2) erl_eval.erl:748: :erl_eval.do_apply/7```

To me personally it looks like the wrong version got pushed to the Docker servers which is why migration doesn't work.
