### DISCUSSION TITLE
** (Postgrex.Error) ERROR 42703 (undefined_column) column g0.domain does not exist

### DISCUSSION THREAD

**Discussion by wef0rm** [plausible/analytics#3047] [Self-Hosted Support]
I recently started getting this error:
`** (Postgrex.Error) ERROR 42703 (undefined_column) column g0.domain does not exist`

Not sure what happened, but I guess it got updated and broke. The landing page looks normal with all sites, but clicking one of the sites, gives error 500 – and the output below.

I did find [this post](https://github.com/plausible/analytics/discussions/3042) – which is a bit similar, but I don't see any solution?

```
plausible_db           |
plausible_db           | PostgreSQL Database directory appears to contain a database; Skipping initialization
plausible_db           |
plausible_db           | 2023-06-18 16:48:12.118 UTC [1] LOG:  starting PostgreSQL 14.8 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
plausible_db           | 2023-06-18 16:48:12.118 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
plausible_db           | 2023-06-18 16:48:12.118 UTC [1] LOG:  listening on IPv6 address "::", port 5432
plausible_db           | 2023-06-18 16:48:12.120 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
plausible_db           | 2023-06-18 16:48:12.123 UTC [22] LOG:  database system was shut down at 2023-06-18 16:47:50 UTC
plausible_db           | 2023-06-18 16:48:12.132 UTC [1] LOG:  database system is ready to accept connections
plausible_events_db    | Processing configuration file '/etc/clickhouse-server/config.xml'.
plausible_events_db    | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
plausible_events_db    | Merging configuration file '/etc/clickhouse-server/config.d/logging.xml'.
plausible_events_db    | Logging warning to /var/log/clickhouse-server/clickhouse-server.log
plausible_events_db    | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
plausible_events_db    | 2023.06.18 16:48:12.895925 [ 1 ] {} <Warning> Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 22.8.13.20 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db    | 2023.06.18 16:48:12.896258 [ 1 ] {} <Warning> Application: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 22.8.13.20 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db    | 2023.06.18 16:48:12.896517 [ 1 ] {} <Warning> Application: Listen [::]:9004 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 22.8.13.20 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db    | 2023.06.18 16:48:12.896711 [ 1 ] {} <Warning> Application: Listen [::]:9005 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 22.8.13.20 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db    | 2023.06.18 16:48:12.937735 [ 1 ] {} <Warning> Application: Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 22.8.13.20 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible              | Loading plausible..
plausible              | Starting dependencies..
plausible              | Starting repos..
plausible              | create Plausible.Repo database if it doesn't exist
plausible              | create Plausible.ClickhouseRepo database if it doesn't exist
plausible              | Creation of Db successful!
plausible              | Loading plausible..
plausible              | Starting dependencies..
plausible              | Starting repos..
plausible              | Running migrations for Elixir.Plausible.Repo
plausible              | Running migrations for Elixir.Plausible.ClickhouseRepo
plausible              | Migrations successful!
plausible_db           | 2023-06-18 16:48:34.622 UTC [35] ERROR:  column g0.domain does not exist at character 39
plausible_db           | 2023-06-18 16:48:34.622 UTC [35] STATEMENT:  SELECT TRUE FROM "goals" AS g0 WHERE (g0."domain" = $1) LIMIT 1
plausible              | 16:48:34.624 [error] #PID<0.3234.0> running PlausibleWeb.Endpoint (connection #PID<0.3203.0>, stream id 4) terminated
plausible              | Server: pa.<domain>.tld:80 (http)
plausible              | Request: GET /sitename
plausible              | ** (exit) an exception was raised:
plausible              |     ** (Postgrex.Error) ERROR 42703 (undefined_column) column g0.domain does not exist
plausible              |
plausible              |     query: SELECT TRUE FROM "goals" AS g0 WHERE (g0."domain" = $1) LIMIT 1
plausible              |         (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
plausible              |         (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:847: Ecto.Adapters.SQL.execute/6
plausible              |         (ecto 3.8.4) lib/ecto/repo/queryable.ex:221: Ecto.Repo.Queryable.execute/4
plausible              |         (ecto 3.8.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
plausible              |         (ecto 3.8.4) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.exists?/3
plausible              |         (plausible 0.0.1) lib/plausible_web/controllers/stats_controller.ex:66: PlausibleWeb.StatsController.stats/2
plausible              |         (plausible 0.0.1) lib/plausible_web/controllers/stats_controller.ex:1: PlausibleWeb.StatsController.action/2
plausible              |         (plausible 0.0.1) lib/plausible_web/controllers/stats_controller.ex:1: PlausibleWeb.StatsController.phoenix_controller_pipeline/2
```

This is my `docker-compose.yml`

```
version: "3.3"
services:

  plausible_db:
    image: postgres:14-alpine
    container_name: plausible_db
    restart: always
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=<password>

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.8.13.20-alpine
    container_name: plausible_events_db
    restart: always
    networks:
      - backend
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    container_name: plausible
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    networks:
      - web
      - backend
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

networks:
  web:
    name: web
    external: true
  ua_backend:
    name: backend
```
