### DISCUSSION TITLE
Plausible fails to connect to clickhouse even with correct CLICKHOUSE_DATABASE_URL

### DISCUSSION THREAD

**Discussion by xrl** [plausible/analytics#3070] [Self-Hosted Support]
I am spinning up plausible+clickhouse inside of Kubernetes using argo-cd. I have one argo application to manage the plausible helm release (homemade chart), and another argo application to manage the clickhouse helm release (bitnami clickhouse).

Here are the application definitions:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plausible
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/my-org/plausible.git
    targetRevision: HEAD
    path: charts/plausible
    helm:
      releaseName: plausible
  destination:
    server: https://kubernetes.default.svc
    namespace: plausible
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plausible-clickhouse
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.4.4
    chart: clickhouse
    helm:
      releaseName: clickhouse
  destination:
    server: https://kubernetes.default.svc
    namespace: plausible
```

I have confirmed that clickhouse+plausible have happy pods:

```
% k get pods
NAME                          READY   STATUS    RESTARTS   AGE
clickhouse-5b498cb688-fwqfr   1/1     Running   0          6d20h
clickhouse-shard0-0           1/1     Running   0          8h
clickhouse-shard0-1           1/1     Running   0          21h
clickhouse-shard0-2           1/1     Running   0          21h
clickhouse-shard1-0           1/1     Running   0          16h
clickhouse-shard1-1           1/1     Running   0          21h
clickhouse-shard1-2           1/1     Running   0          21h
clickhouse-zookeeper-0        1/1     Running   0          21h
clickhouse-zookeeper-1        1/1     Running   0          16h
clickhouse-zookeeper-2        1/1     Running   0          8h
plausible-8587857b77-pd424    1/1     Running   0          18h
```

And the services are laid out like this:

```
% k get svc 
NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                        AGE
clickhouse                      ClusterIP   10.100.94.202    <none>        8123/TCP,9000/TCP,9004/TCP,9005/TCP,9009/TCP   10d
clickhouse-headless             ClusterIP   None             <none>        8123/TCP,9000/TCP,9004/TCP,9005/TCP,9009/TCP   21h
clickhouse-zookeeper            ClusterIP   10.100.69.11     <none>        2181/TCP,2888/TCP,3888/TCP                     21h
clickhouse-zookeeper-headless   ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP                     21h
plausible                       ClusterIP   10.100.220.100   <none>        8000/TCP                                       9d
```

And plausible is talking to the `clickhouse` service like this:

```
% k get pod plausible-8587857b77-pd424 -o yaml
kind: Pod
metadata:
  name: plausible-8587857b77-pd424
  namespace: plausible
spec:
  containers:
  - env:
    - name: BASE_URL
      value: https://plausible.my-thing.com
    - name: DISABLE_REGISTRATION
      value: "true"
    - name: POSTGRES_PORT
      value: "5432"
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          key: POSTGRES_URL
          name: plausible-postgres-direct-secret
    - name: CLICKHOUSE_DATABASE_URL
      value: http://default:$admin-password-from-the-helm-created-secret@clickhouse:8123/plausible
    envFrom:
    - secretRef:
        name: plausible-postgres-direct-secret
    image: plausible/analytics:v2.0.0-rc.2
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: plausible
    ports:
    - containerPort: 8000
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "2"
        memory: 10Gi
      requests:
        cpu: "2"
        memory: 10Gi
```

but when I look at the logs for plausible I get an infinite stream of these lines:

```
01:37:35.801 [error] Ch.Connection (#PID<0.3392.0>) failed to connect: ** (Ch.Error) Code: 81. DB::Exception: Database plausible doesn't exist. (UNKNOWN_DATABASE) (version 23.5.3.24 (official build))
```

but if I query the clickhouse service using curl I can see the database:

```
# echo 'SHOW DATABASES' | curl 'http://default:$admin-password-from-the-helm-created-secret@clickhouse:8123/' --data-binary @-
INFORMATION_SCHEMA
default
information_schema
plausible
system
```

Why is plausible unable to acccess the `plausible` database from clickhouse?
