### DISCUSSION TITLE
v2.0.0

### DISCUSSION THREAD

**Discussion by ruslandoga** [plausible/analytics#3132] [Self-Hosted Support]
The highlights of this release are:

- more visitor metrics like total visits and views per visit
- period comparisons [[docs]](https://plausible.io/docs/guided-tour#compare-your-stats-over-time) [[example]](https://plausible.io/plausible.io?comparison=previous_period)
- ability to change domains names https://github.com/plausible/analytics/pull/2803
- automatic geolocation database downloads  plausible/analytics#2362
- more email adapters support (Mailgun, Mandrill, SendGrid) plausible/analytics#2649

### Upgrading Plausible Analytics to v2.0

>  [!WARNING]
> 
> This guide assumes you are running v1.5.1.
> If you are upgrading from an earlier version, you might encounter the error reported (and resolved) in https://github.com/plausible/analytics/issues/4779

>  [!WARNING]
> 
> Upgrading to `v2.0` requires performing a data migration.
> Please read these notes until the end before deploying `v2.0.0`

#### Ensure you are using a new ClickHouse version

The steps below have been tested with [`clickhouse/clickhouse-server:22.6-alpine`](https://github.com/plausible/hosting/blob/3e1462eabd510cc9320a6cfed0ae45355d86bb05/docker-compose.yml#L16-L26) please make sure to upgrade ClickHouse to at least this version.

<details>
<summary>Here's the excerpt from <a href="https://github.com/plausible/analytics/discussions/2507"><code>v1.5 release discussion</code></a> regarding the ClickHouse upgrade</summary>

---

In your docker-compose.yml update the image used for plausible_events_db to a newer ClickHouse version:

### Upgrading ClickHouse to 22.6

```diff
plausible_events_db:
- image: yandex/clickhouse-server:21.3.2.5
+ image: clickhouse/clickhouse-server:22.6-alpine
```

#### Restart the container

```console
$ docker compose stop plausible plausible_events_db
$ docker compose rm plausible_events_db
$ docker compose up -d
```

This will boot up the new version of ClickHouse.

Related PR: https://github.com/plausible/hosting/pull/45

---

</details>

#### Update image tag

In your `docker-compose.yml` update the image used for `plausible` to `v2.0.0`

```diff
plausible:
- image: plausible/analytics:v1.5.1
+ image: plausible/analytics:v2.0.0
```

and restart the container

```console
$ cd hosting
$ docker compose stop plausible
$ docker compose rm plausible
$ docker compose up -d
```

This will boot up the new version of the app.

If you open the dashboards now, you wouldn't see any past metrics. This is expected as `v2.0` uses the new `events_v2` and `sessions_v2` tables to store analytics data. We need to perform data migration to copy the data into the new tables.

#### Run data migration

> ⚠️ ⚠️ ⚠️
> 
> You need enough free disk space available for x2 of the current `plausible_events_db`'s `event-data` volume size. You can use something like `docker system df -v | grep hosting_event-data` to check how much space the current volume is occupying.

Connect to the running `plausible` container and start the migration flow

```console
$ cd hosting
$ docker compose exec plausible bin/plausible rpc Plausible.DataMigration.NumericIDs.run
```

You can attempt this migration multiple times unless you drop `v1` tables.

#### Drop v1 tables (optional)

Once you **verify** the migration went **well,** the old tables can be dropped. It's easiest to use `clickhouse-client` for this

```console
$ ch hosting
$ docker compose exec plausible_events_db clickhouse-client
```
```sql
:) \c plausible_events_db
:) show tables;
:) drop table events;
:) drop table sessions;
```

See https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#max-table-size-to-drop for how to drop tables with more than 50GB of data.

#### Enable automatic MaxMind GeoLite2 updates (optional)

In your `plausible-config.env` set [`MAXMIND_LICENSE_KEY`](https://www.maxmind.com/en/accounts/current/license-key) environment variable and get an automatically updated [GeoLite2 City](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data) geolocation database. The database edition is configurable with `MAXMIND_EDITION` environment variable and defaults to `GeoLite2-City`.

```diff
- IP_GEOLOCATION_DB=...
+ MAXMIND_LICENSE_KEY=LNpsJCCKPis6XvBP
+ MAXMIND_EDITION=GeoLite2-City
```

Note that for the changes in `plausible-config.env` to propagate to the `plausible`, the container needs to be recreated:

```console
$ docker compose stop plausible
$ docker compose rm plausible
$ docker compose up -d
```

Also note that using `GeoLite2-City` edition requires more RAM than using `GeoLite2-Country`.

Now you can remove any other volumes and services used to download, store, and update geolocation databases.

## Changelog

Following [changes](https://github.com/plausible/analytics/compare/v1.5.1...v2.0.0) have been made since v1.5:

### Added
- Add support for `with_imported=true` in Stats API aggregate endpoint
- Ability to use '--' instead of '=' sign in the `tagged-events` classnames
- 'Last updated X seconds ago' info to 'current visitors' tooltips
- Add support for more Bamboo adapters, i.e. `Bamboo.MailgunAdapter`, `Bamboo.MandrillAdapter`, `Bamboo.SendGridAdapter` plausible/analytics#2649
- Ability to change domain for existing site (requires numeric IDs data migration, instructions will be provided separately) UI + API (`PUT /api/v1/sites`)
- Add `LOG_FAILED_LOGIN_ATTEMPTS` environment variable to enable failed login attempts logs plausible/analytics#2936
- Add `MAILER_NAME` environment variable support plausible/analytics#2937
- Add `MAILGUN_BASE_URI` support for `Bamboo.MailgunAdapter` plausible/analytics#2935
- Add a landing page for self-hosters plausible/analytics#2989
- Allow optional IPv6 for clickhouse repo plausible/analytics#2970

### Fixed
- Fix tracker bug - call callback function even when event is ignored
- Make goal-filtered CSV export return only unique_conversions timeseries in the 'visitors.csv' file
- Stop treating page filter as an entry page filter
- City report showing N/A instead of city names with imported data plausible/analytics#2675
- Empty values for Screen Size, OS and Browser are uniformly replaced with "(not set)"
- Fix [more pageviews with session prop filter than with no filters](https://github.com/plausible/analytics/issues/1666)
- Cascade delete sent_renewal_notifications table when user is deleted plausible/analytics#2549
- Show appropriate top-stat metric labels on the realtime dashboard when filtering by a goal
- Fix breakdown API pagination when using event metrics plausible/analytics#2562
- Automatically update all visible dashboard reports in the realtime view
- Connect via TLS when using HTTPS scheme in ClickHouse URL plausible/analytics#2570
- Add error message in case a transfer to an invited (but not joined) user is requested plausible/analytics#2651
- Fix bug with [showing property breakdown with a prop filter](https://github.com/plausible/analytics/issues/1789)
- Fix bug when combining goal and prop filters plausible/analytics#2654
- Fix broken favicons when domain includes a slash
- Fix bug when using multiple [wildcard goal filters](https://github.com/plausible/analytics/pull/3015)
- Fix a bug where realtime would fail with imported data
- Fix a bug where the country name was not shown when [filtering through the map](https://github.com/plausible/analytics/issues/3086)

### Changed
- Treat page filter as entry page filter for `bounce_rate`
- Reject events with long URIs and data URIs plausible/analytics#2536
- Always show direct traffic in sources reports plausible/analytics#2531
- Stop recording XX and T1 country codes plausible/analytics#2556
- Device type is now determined from the User-Agent instead of window.innerWidth plausible/analytics#2711
- Add padding by default to embedded dashboards so that shadows are not cut off plausible/analytics#2744
- Update the User Agents database (https://github.com/matomo-org/device-detector/releases/tag/6.1.1)
- Disable registration in self-hosted setups by default plausible/analytics#3014

### Removed
- Remove Firewall plug and `IP_BLOCKLIST` environment variable
- Remove the ability to collapse the main graph plausible/analytics#2627
- Remove `custom_dimension_filter` feature flag plausible/analytics#2996

<hr /><em>This discussion was created from the release <a href='https://github.com/plausible/analytics/releases/tag/v2.0.0'>v2.0.0</a>.</em>

**Comment by stijneikelboom** [comment]
After the seemingly successful migration to `v2.0.0`, I noticed the `tmp_events_v2` and `tmp_sessions_v2` tables in the `plausible_events_db` database.

Are these tables expected to exist after the migration? Or are they as temporary as their name suggests and can they be dropped along with the `v1` tables?

My full list of tables is currently as follows:
```
┌─name───────────────────────┐
│ domains_lookup             │
│ events                     │
│ events_v2                  │
│ imported_browsers          │
│ imported_devices           │
│ imported_entry_pages       │
│ imported_exit_pages        │
│ imported_locations         │
│ imported_operating_systems │
│ imported_pages             │
│ imported_sources           │
│ imported_visitors          │
│ ingest_counters            │
│ schema_migrations          │
│ sessions                   │
│ sessions_v2                │
│ tmp_events_v2              │
│ tmp_sessions_v2            │
└────────────────────────────┘
```

**Reply by ruslandoga** [reply]
👋 @stijneikelboom 

I think these tables are indeed temporary (since the partitions are moved, and these tables are truncated in the end of the script) and can be dropped.

https://github.com/plausible/analytics/blob/c550a87e01e7adbc075ecbc647f38610c475f12c/lib/plausible/data_migration/numeric_ids.ex#L143-L150

Seems like they were used to atomically copy the rows partition by partition into the new tables.

**Reply by aerosol** [reply]
Yeah, safe to drop them

**Reply by stijneikelboom** [reply]
Thanks both! Totally clear why these tables are there. I now see that they are empty indeed.

Dropping these tables might be a useful addition to the ‘Drop v1 tables’ section, just for tidiness.

**Comment by Lastofthefirst** [comment]
I'm having difficulties enabling city geolocation. When I try to add I get a 502 error.

Here are my docker-compose logs, can you point me in the right direction?

https://gist.github.com/Lastofthefirst/08ba4ba464eccb00826936bfa774a874

**Reply by Lastofthefirst** [reply]
(I was running some pre-v1.5.1 version and upgraded to v2.0.0. It was successful until I added city with maxmind.)

**Reply by ruslandoga** [reply]
👋 @Lastofthefirst 

The error says `/etc/app/geonames.csv` is a directory, and it's expected to be a file. Check your mounts in the `docker-compose.yml` config.

**Comment by strefethen** [comment]
I attempted upgrading from v1.5.1 > v2.0.0 and ran into some significant issues due to what appears to have been some latent issues with the Clickhouse DB that I was unaware of. Since it took me several hours to get a backup working I thought I'd post what I did to get my v1.5.1 back up and running and avoid losing 6 mos. of data. For starters, I followed the v2.0.0 upgrade instructions but upon bringing Plausible backup noticed tons of errors streaming by in docker. 

```curl
$ docker logs -f <plausible_containerID>
```

The first was (truncated):
```
"[error] [locus] [geolocation] database failed to load (:filesystem): {:unpack_database_from, :mmdb_blob"
```
...followed by 

```
"Kernel pid terminated",application_controller,"{application_start_failure,plausible,{bad_return,{{'Elixir.Plausible.Application'"
```

I decided to restore my backup and ran into the Clickhouse issues restarting docker makes me think there were problems prior to the upgrade. Btw, I'd previously performed the steps to get city level data via Maxmind. I searched for multiple Clickhouse errors including "Suspiciously many (12 parts, 0.00 B in total) broken parts...". I made two changes that allowed me to get my backup working which is what I think is worth sharing.

[This](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication#recovery-after-failures) article (among others) was helpful. 

1. Add the empty force_restore_data file via a volume reference in ./geoip/docker-compose.geoip.yaml under geoip.
2. Added the following XML to ./clickhouse/clickhouse-config.xml

```xml
    <merge_tree>
        <max_suspicious_broken_parts>12</max_suspicious_broken_parts>
    </merge_tree>
```

After these changes my v1.5.1 backup started working again. I haven't repeated the v2.0.0 upgrade but will give it another go.

**Comment by sebdanielsson** [comment]
**UPDATE**: I solved my error. See reply down below.

I'm trying to use the new Bamboo Mailgun adapter. I've added my API key and Mailgun domain but I don't receive mail anymore. Is there a way to check for error logs and also send test mails when troubleshooting? I can't see any obvious errors in my compose file and running docker logs <container-id> doesn't show any mail related errors.

My compose file:

```yaml
services:
  plausible_db:
    image: postgres:14-alpine
    networks:
      - plausible_network
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - source: plausible_postgres_password
        target: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    restart: always
  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    networks:
      - plausible_network
    volumes:
      - event_db:/var/lib/clickhouse
      - event_db_logs:/var/log/clickhouse-server
      - event_db_config:/etc/clickhouse-server
    deploy:
      mode: replicated
      replicas: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always
  app:
    image: plausible/analytics:v2.0.0
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    networks:
      - plausible_network
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - "8888:8000"
    environment:
      - CONFIG_DIR=/run/secrets
      - DISABLE_REGISTRATION=false
      - BASE_URL=/run/secrets/plausible_base_url
      - SECRET_KEY_BASE=/run/secrets/plausible_secret_key_base
      - GOOGLE_CLIENT_ID=/run/secrets/plausible_google_client_id
      - GOOGLE_CLIENT_SECRET=/run/secrets/plausible_google_client_secret
      - MAILGUN_API_KEY=/run/secrets/plausible_mailgun_api_key
      - MAILGUN_DOMAIN=/run/secrets/plausible_mailgun_domain
    secrets:
      - source: plausible_base_url
        target: /run/secrets/BASE_URL
      - source: plausible_secret_key_base
        target: /run/secrets/SECRET_KEY_BASE
      - source: plausible_google_client_id
        target: /run/secrets/GOOGLE_CLIENT_ID
      - source: plausible_google_client_secret
        target: /run/secrets/GOOGLE_CLIENT_SECRET
      - source: plausible_mailgun_api_key
        target: /run/secrets/MAILGUN_API_KEY
      - source: plausible_mailgun_domain
        target: /run/secrets/MAILGUN_DOMAIN
    deploy:
      mode: replicated
      replicas: 1
    restart: always

networks:
  plausible_network:
    external: true

volumes:
  db:
    name: plausible_db
  event_db:
    name: plausible_event_db
  event_db_logs:
    name: plausible_event_db_logs
  event_db_config:
    name: plausible_event_db_config

secrets:
  plausible_postgres_password:
    external: true
  plausible_base_url:
    external: true
  plausible_secret_key_base:
    external: true
  plausible_google_client_id:
    external: true
  plausible_google_client_secret:
    external: true
  plausible_mailgun_api_key:
    external: true
  plausible_mailgun_domain:
    external: true
```
