### DISCUSSION TITLE
Error configuring Clickhouse remotely

### DISCUSSION THREAD

**Discussion by altendorfme** [plausible/analytics#3147] [Self-Hosted Support]
Server A:

```
version: "3.3"
services:
  mail:
    container_name: mail
    image: bytemark/smtp
    restart: always
    logging:
      options:
        max-size: 50m

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /opt/postgres/var:/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/plausible
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 50m

  plausible:
    container_name: plausible
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - postgres
      - geoip
      - mail
    environment:
      - TZ=America/Sao_Paulo
      - BASE_URL=https://xyz.xyz
      - SECRET_KEY_BASE=SECRET_KEY_BASE
      - MAILER_EMAIL=email@xyz.xyz
      - SMTP_HOST_ADDR=in-v3.mailjet.com
      - SMTP_HOST_PORT=587
      - SMTP_USER_NAME=SMTP_USER_NAME
      - SMTP_USER_PWD=SMTP_USER_PWD
      - SMTP_HOST_SSL_ENABLED=false
      - SMTP_RETRIES=2
      - GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET
      - DISABLE_REGISTRATION=false
      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
      - CLICKHOUSE_DATABASE_URL=http://10.0.0.92:8123/plausible
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/plausible_db
    ports:
      - 8000:8000
    volumes:
      - /opt/geoip:/geoip:ro
    labels:
      virtual.host: "https://xyz.xyz"
      virtual.port: "8000"
      virtual.tls-email: "email@xyz.xyz"
    logging:
      options:
        max-size: 50m

  geoip:
    container_name: geoip
    image: maxmindinc/geoipupdate
    restart: always
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168
      - GEOIPUPDATE_ACCOUNT_ID=GEOIPUPDATE_ACCOUNT_ID
      - GEOIPUPDATE_LICENSE_KEY=GEOIPUPDATE_LICENSE_KEY
      - MAXMIND_LICENSE_KEY=MAXMIND_LICENSE_KEY
      - MAXMIND_EDITION=GeoLite2-City
    volumes:
      - /opt/geoip:/usr/share/GeoIP
    logging:
      options:
        max-size: 50m

  caddy:
    container_name: caddy
    image: wemakeservices/caddy-gen:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/caddy/:/data/caddy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - plausible
    logging:
      options:
        max-size: 50m
```

Server B:

```
version: "3.3"
services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:22.8.13.20-alpine
    restart: always
    network_mode: host
    volumes:
      - /opt/clickhouse/data:/var/lib/clickhouse
      - /opt/clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - /opt/clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    logging:
      options:
        max-size: 50m
```

Server A is seeing Server B, I validated with:

```
$curl 10.0.0.92:8123
Ok.
```

I can also see the plausible table, which I manually created on Server B:

```
$ curl 10.0.0.92:8123/?query=SHOW%20DATABASES
INFORMATION_SCHEMA
default
information_schema
plausible
system
```

But when looking at the Plausible logs:

```
Loading plausible..
Starting dependencies..
Starting repos..
create Plausible.Repo database if it doesn't exist
19:26:46.862 [error] Ch.Connection (#PID<0.172.0>) failed to connect: ** (Mint.TransportError) non-existing domain
19:26:46.862 [error] Ch.Connection (#PID<0.171.0>) failed to connect: ** (Mint.TransportError) non-existing domain
create Plausible.IngestRepo database if it doesn't exist
** (MatchError) no match of right hand side value: {:error, %Mint.TransportError{reason: :nxdomain}}
    (plausible 0.0.1) lib/plausible_release.ex:40: anonymous fn/2 in Plausible.Release.createdb/0
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plausible 0.0.1) lib/plausible_release.ex:39: Plausible.Release.createdb/0
    nofile:1: (file)
    (stdlib 4.2) erl_eval.erl:748: :erl_eval.do_apply/7
```

Any ideas?
When I up the clickhouse together on Server A everything worked perfectly, I even kept the CLICKHOUSE_DATABASE_URL env to validate.
