### DISCUSSION TITLE
Region and cities no longer appear after 2.0

### DISCUSSION THREAD

**Discussion by altendorfme** [plausible/analytics#3248] [Self-Hosted Support]
It's been a week since the cities and region tabs haven't received any data, country works correctly, I updated by removing the geoip package along with updating to 2.0 as per the repository.

I also turned off Cloudflare to validate that it wasn't some kind of block.

I'm using Caddygen as Webservice

Any tips here?

**Comment by ruslandoga** [comment]
👋 @altendorfme 

You can check what IPs Plausible receives: https://github.com/plausible/analytics/discussions/2767#discussioncomment-5367417

```elixir
iex> remote_ip_and_headers = fn {:trace, _pid, :call, {_mod, _fun, [%Plug.Conn{remote_ip: remote_ip, req_headers: headers}]}} -> inspect([remote_ip: remote_ip, headers: headers]) end
iex> mod_fun_args = {PlausibleWeb.RemoteIP, :get, 1}
iex> how_many_times = 5
iex> :recon_trace.calls(mod_fun_args, how_many_times, formatter: remote_ip_and_headers)
```

And then you can connect to the running instance and try to look them up:

```console
$ cd hosting
$ docker compose exec plausible bin/plausible remote
```
```elixir
iex> Plausible.Geo.lookup("1.1.1.1") # but with the IPs you see in the headers / conn.remote_ip
```

This would hopefully help you debug this issue.

**Comment by altendorfme** [comment]
It seems that the IPs are arriving correctly, but when I use:
`
Plausible.Geo.lookup("143.137.xx.xx") // my ip
`
It returns:
```
%{
  "continent" => %{
    "code" => "SA",
    "geoname_id" => 6255150,
    "names" => %{
      "de" => "Südamerika",
      "en" => "South America",
      "es" => "Sudamérica",
      "fa" => "امریکای جنوبی",
      "fr" => "Amérique Du Sud",
      "ja" => "南アメリカ大陸",
      "ko" => "남아메리카",
      "pt-BR" => "América Do Sul",
      "ru" => "Южная Америка",
      "zh-CN" => "南美洲"
    }
  },
  "country" => %{
    "geoname_id" => 3469034,
    "is_in_european_union" => false,
    "iso_code" => "BR",
    "names" => %{
      "de" => "Brasilien",
      "en" => "Brazil",
      "es" => "Brasil",
      "fa" => "برزیل",
      "fr" => "Brésil",
      "ja" => "ブラジル",
      "ko" => "브라질",
      "pt-BR" => "Brasil",
      "ru" => "Бразилия",
      "zh-CN" => "巴西"
    }
  }
}

```

That's right, it's an IP from Brazil, but it doesn't show City or Region

**Reply by ruslandoga** [reply]
What does `:locus.get_info(:geolocation)` return?

**Reply by altendorfme** [reply]
```
iex> :locus.get_info(:geolocation)

{:ok,
 %{
   metadata: %{
     binary_format_version: {2, 0},
     build_epoch: 1688198873,
     database_type: "DBIP-Country-Lite",
     description: %{
       "en" => "DB-IP.com - IP to Country",
       "fr" => "DB-IP.com - IP vers Pays"
     },
     ip_version: 6,
     languages: ["en", "de", "es", "fr", "ja", "pt-BR", "ru", "zh-CN", "fa",
      "ko"],
     node_count: 1272144,
     record_size: 24
   },
   source: {:filesystem,
    '/app/lib/plausible-0.0.1/priv/geodb/dbip-country.mmdb.gz'},
   version: {{2023, 7, 1}, {8, 7, 53}}
 }}
```

and

```
System.get_env("MAXMIND_EDITION")

nil
```

**Reply by ruslandoga** [reply]
Seems like you are using DBIP Country Lite and not MaxMind. Please double check your configuration, it should have `MAXMIND_LICENSE_KEY` set at least, more info: https://plausible.io/docs/self-hosting-configuration#ip-geolocation

**Reply by altendorfme** [reply]
Ow! I just see where I went wrong, the ENV settings were in the old geoip packet and not plausible! Thank you very much!

```
:locus.get_info(:geolocation)

iex> :locus.get_info(:geolocation)
{:ok,
 %{
   metadata: %{
     binary_format_version: {2, 0},
     build_epoch: 1691080267,
     database_type: "GeoLite2-City",
     description: %{"en" => "GeoLite2 City database"},
     ip_version: 6,
     languages: ["de", "en", "es", "fr", "ja", "pt-BR", "ru", "zh-CN"],
     node_count: 5211078,
     record_size: 28
   },
   source: {:remote, {:maxmind, :"GeoLite2-City"}},
   version: {{2023, 8, 3}, {16, 31, 7}}
 }}
```

```
System.get_env("MAXMIND_EDITION")
"GeoLite2-City"
```

**Comment by pasqualevitiello** [comment]
Hey there, not an expert here. I did manage to get Plausible Self-Hosted up and running on a DigitalOcean droplet. By the way, I noticed that the regions and cities aren't showing up, so I decided to follow the advice in this thread to see what's wrong.

```
docker compose exec plausible bin/plausible remote
iex()> Plausible.Geo.lookup("myIPaddress")
```

returned

```
%{
  "continent" => %{
    "code" => "OC",
    "geoname_id" => 6255151,
    "names" => %{
      "de" => "Ozeanien",
      "en" => "Oceania",
      "es" => "Oceanía",
      "fa" => "اقیانوسیه",
      "fr" => "Océanie",
      "ja" => "オセアニア",
      "ko" => "오세아니아",
      "pt-BR" => "Oceania",
      "ru" => "Океания",
      "zh-CN" => "大洋洲"
    }
  },
  "country" => %{
    "geoname_id" => 2077456,
    "is_in_european_union" => false,
    "iso_code" => "AU",
    "names" => %{
      "de" => "Australien",
      "en" => "Australia",
      "es" => "Australia",
      "fa" => "استرالیا",
      "fr" => "Australie",
      "ja" => "オーストラリア",
      "ko" => "오스트레일리아",
      "pt-BR" => "Austrália",
      "ru" => "Австралия",
      "zh-CN" => "澳大利亚"
    }
  }
}
```

Then I tried to run `:locus.get_info(:geolocation)`, and it returned
```
 %{
   metadata: %{
     binary_format_version: {2, 0},
     build_epoch: 1688198873,
     database_type: "DBIP-Country-Lite",
     description: %{
       "en" => "DB-IP.com - IP to Country",
       "fr" => "DB-IP.com - IP vers Pays"
     },
     ip_version: 6,
     languages: ["en", "de", "es", "fr", "ja", "pt-BR", "ru", "zh-CN", "fa",
      "ko"],
     node_count: 1272144,
     record_size: 24
   },
   source: {:filesystem,
    '/app/lib/plausible-0.0.1/priv/geodb/dbip-country.mmdb.gz'},
   version: {{2023, 7, 1}, {8, 7, 53}}
 }}
```

It seems like the DBIP-Country-Lite response doesn't include regions and cities data. So, I thought to give Maxmind a shot.

I checked out the [v2.0 release notes](https://github.com/plausible/analytics/releases), and it seems all you need to do is set up these two variables: `MAXMIND_LICENSE_KEY` and `MAXMIND_EDITION`. Then, recreate the container, right? But when I do that, the server doesn't kick off (502 error).

The `docker-compose logs` command returned quite a lot of errors that look like this:

```
<Error> DynamicQueryHandler: Code: 82. DB::Exception: Database plausible_events_db already exists.
```

Any ideas on what's gone wrong here?

**Reply by ruslandoga** [reply]
@pasqualevitiello 👋

Are there any errors that are logged from `plausible` container when you get the 502 response?

**Reply by pasqualevitiello** [reply]
Hey @ruslandoga , thanks for answering! How can I check these logs?

**Reply by ruslandoga** [reply]
```console
$ cd hosting
$ docker compose logs plausible
```

**Reply by pasqualevitiello** [reply]
```
root@docker2306onubuntu2204-s-1vcpu-1gb-ams3-01:/opt/plausible# docker compose logs plausible
plausible-plausible-1  | Loading plausible..
plausible-plausible-1  | Starting dependencies..
plausible-plausible-1  | Starting repos..
plausible-plausible-1  | create Plausible.Repo database if it doesn't exist
plausible-plausible-1  | create Plausible.IngestRepo database if it doesn't exist
plausible-plausible-1  | Creation of Db successful!
plausible-plausible-1  | Loading plausible..
plausible-plausible-1  | Starting dependencies..
plausible-plausible-1  | Starting repos..
plausible-plausible-1  | Running migrations for Elixir.Plausible.Repo
plausible-plausible-1  | Running migrations for Elixir.Plausible.IngestRepo
plausible-plausible-1  | Migrations successful!
plausible-plausible-1  | Loading plausible..
plausible-plausible-1  | Starting dependencies..
plausible-plausible-1  | Starting repos..
plausible-plausible-1  | create Plausible.Repo database if it doesn't exist
plausible-plausible-1  | create Plausible.IngestRepo database if it doesn't exist
plausible-plausible-1  | Creation of Db successful!
plausible-plausible-1  | Loading plausible..
plausible-plausible-1  | Starting dependencies..
plausible-plausible-1  | Starting repos..
plausible-plausible-1  | Running migrations for Elixir.Plausible.Repo
plausible-plausible-1  | Running migrations for Elixir.Plausible.IngestRepo
plausible-plausible-1  | Migrations successful!
```

Not sure why, I don't have a `hosting` dir.

**Reply by ruslandoga** [reply]
> But when I do that, the server doesn't kick off (502 error).

Can you try making a request to get some errors in the logs?

**Reply by ruslandoga** [reply]
Ah, the error code means `plausible` is not reachable from the proxy. Can you please share your proxy<->plausible configuration?

> Not sure why, I don't have a hosting dir.

You probably followed an unofficial guide :) If that's the case, please share your `docker-compose.yml` and `plausible-conf.env` (if you have it) with secrets redacted.

**Reply by pasqualevitiello** [reply]
Yes, I followed [this guide](https://flaviocopes.com/how-to-self-host-plausible-analytics/).

`docker-compose.yml`

```
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:23.3.7.5-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v2.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
```

`plausible-conf.env`

```
BASE_URL=https://plausible.website.com
SECRET_KEY_BASE=secretkey
DISABLE_REGISTRATION=true
GOOGLE_CLIENT_ID=xxxx.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=XXXX
MAXMIND_LICENSE_KEY=mylicensekey
MAXMIND_EDITION=GeoLite2-City
```
