### DISCUSSION TITLE
Why geoip volume is still in the docker-compose.yml

### DISCUSSION THREAD

**Discussion by madanyang** [plausible/analytics#3252] [Self-Hosted Support] [answered]
On the [release notes for v2.0](https://github.com/plausible/analytics/discussions/3132) just before the changelog @ruslandoga wrote

**Now you can remove any other volumes and services used to download, store, and update geolocation databases.**

the [docker-compose.yml](https://github.com/plausible/hosting/blob/master/docker-compose.yml) has the geoip volume. If the above is true shouldn't this volume be removed.
```
volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
```
