### DISCUSSION TITLE
SMTP environment variables not working if set inside `plausible-conf.env`

### DISCUSSION THREAD

**Discussion by puresick** [plausible/analytics#3299] [Self-Hosted Support] [answered]
Using the docker image `plausible/analytics:v2.0.0` the SMTP environment variables do not work for me setting up the mailer.

As [described in the docs](https://plausible.io/docs/self-hosting-configuration#mailersmtp-setup), I've been using the following env vars for setting up my SMTP server:

```
MAILER_EMAIL
SMTP_HOST_ADDR=mysmtpserverhostname
SMTP_HOST_PORT=587
SMTP_USER_NAME=mysmtpserverusername
SMTP_USER_PWD=mysupersecretpassword
SMTP_HOST_SSL_ENABLED=true
```

Setting the configuration that way results in no email being sent (tested with inviting people).

When I am removing all of the above again and setting the following onto the `bytemnark/smtp` image in my `docker-compose.yml` directly, it works:

```
mail: bytemark/smtp
restart: always
environment:
  RELAY_HOST: mysmtpserverhostname
  RELAY_PORT: 587
  RELAY_USERNAME: mysmtpserverusername
  RELAY_PASSWORD: mysupersecretpassword
```

Anything I am missing here or is something with the translation from the plausible environment variables to the bytemark smtp configuration broken?
