### DISCUSSION TITLE
Can't seem to get Maxmind to work

### DISCUSSION THREAD

**Discussion by zenminimalist** [plausible/analytics#3447] [Self-Hosted Support]
I'm sure I'm missing something obvious. Here's my Stack file (Portainer Docker compose file) to make sure I didn't forget anything.

```
version: '3.9'
services:
  mail:
    image: bytemark/smtp
    container_name: plausible-mail
    restart: always
    environment:
      - MAILER_EMAIL=XXX@domain.com
      - MAILER_NAME=Plausible Analytics
      - SMTP_HOST_ADDR=smtp.XXXX.com
      - SMTP_HOST_PORT=465
      - SMTP_USER_NAME=XXX@domain.com
      - SMTP_USER_PWD=XXXXXX
      - SMTP_HOST_SSL_ENABLED=true
      - SMTP_RETRIES=2
      - CRON_ENABLED=true

  plausible_db:
    image: postgres:15-alpine
    container_name: plausible-db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=XXXXX

  plausible_events_db:
    image: clickhouse/clickhouse-server:23.6-alpine
    container_name: plausible-clickhouse-db
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro,Z
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro,Z
    environment:
      - CLICKHOUSE_FLUSH_INTERVAL_MS=5000
      - CLICKHOUSE_MAX_BUFFER_SIZE=10000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    container_name: plausible
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
      - geoip
    ports:
      - 8001:8000
    environment:
      - BASE_URL=https://pa.domain.com
      - SECRET_KEY_BASE=XXXXXX
      - ENABLE_EMAIL_VERIFICATION=false
      - DISABLE_REGISTRATION=false
      - LOG_FAILED_LOGIN_ATTEMPT=true
      - RELEASE_DISTRIBUTION=none
      - GOOGLE_CLIENT_ID=XXXXXXapps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=XXXXX
      - GEOIPUPDATE_LICENSE_KEY=XXXXXXXXXXXXXXXXXX

  geoip:
    image: maxmindinc/geoipupdate
    container_name: geoip-maxmind
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168
      - GEOIPUPDATE_ACCOUNT_ID=007
      - GEOIPUPDATE_LICENSE_KEY=XXXXXX
    volumes:
      - ./geoip:/usr/share/GeoIP
    restart: always

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
```

When I  go to `:/usr/share/GeoIP#` and `ls -sh` I have two files 
`total 9.8M -- 2.1M GeoIP.dat  7.8M GeoIPv6.dat`

**Comment by ruslandoga** [comment]
👋 @zenminimalist 

Your setup seems slightly wrong. The files saved by `geoip` service in `./geoip:/usr/share/GeoIP` are not visible by `plausible` service since that volume is not mounted there. Also `geoip` and similar services are no longer needed since `v2.0.0` where Plausible can fetch MaxMind DBs and keep them up top date automatically. See "Enable automatic MaxMind GeoLite2 updates" at https://github.com/plausible/analytics/discussions/3132.

**Reply by ruslandoga** [reply]
I guess `plausible.environment.GEOIPUPDATE_LICENSE_KEY` contains your MaxMind license key. If so, you can try renaming it to `MAXMIND_LICENSE_KEY` and checking if it works. See https://plausible.io/docs/self-hosting-configuration#ip-geolocation for more env var options.

**Comment by zenminimalist** [comment]
> Also `geoip` and similar services are no longer needed since `v2.0.0` where Plausible can fetch MaxMind DBs and keep them up top date automatically. See "Enable automatic MaxMind GeoLite2 updates" at #3132.

So I can remove this part from my docker compose file 

```
geoip:
    image: maxmindinc/geoipupdate
    container_name: geoip-maxmind
    environment:
      - MAXMIND_EDITION=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168
      - GEOIPUPDATE_ACCOUNT_ID=XXXX
      - MAXMIND_LICENSE_KEY=4XXXXXX
      - TZ=Europe/Berlin
    volumes:
      - ./geoip:/usr/share/GeoIP
    restart: always
```

and just leave this part in my palusible env?

```
      - MAXMIND_EDITION=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168
      - GEOIPUPDATE_ACCOUNT_ID=XXXX
      - MAXMIND_LICENSE_KEY=4XXXXXX
```

**Reply by ruslandoga** [reply]
Yes, except there are no geoipupdate_* env vars in Plausible:)

**Reply by zenminimalist** [reply]
Thanks for the help. So, considering everything you mentioned, it should look like so: 

<details>

```
version: '3.9'
services:
  mail:
    image: bytemark/smtp
    container_name: mail
    restart: always

  plausible_db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      
  plausible_events_db:
    image: clickhouse/clickhouse-server:23.6-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    container_name: plausible
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8001:8000
    environment:
      - ENVIRONMENT=production
      - BASE_URL=https://pa.domain.com
      - SECRET_KEY_BASE=XXXXX
      - SIGNING_SALT=XXXXX
      - ENABLE_EMAIL_VERIFICATION=false
      - DISABLE_REGISTRATION=false
      - DISABLE_SUBSCRIPTION=true
      - LOG_FAILED_LOGIN_ATTEMPT=true
      - RELEASE_DISTRIBUTION=none
      - GOOGLE_CLIENT_ID=XXXXX.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=XXXXX
      - MAXMIND_EDITION=GeoLite2-City      
      - MAXMIND_LICENSE_KEY=XXXXX
      - CLICKHOUSE_FLUSH_INTERVAL_MS=5000
      - CLICKHOUSE_MAX_BUFFER_SIZE=10000
      - DATABASE_POOL_SIZE=20
      - CLICKHOUSE_DATABASE_POOLSIZE=20
      - MAILER_EMAIL=XXXXX@domain.com
      - MAILER_NAME=Plausible-Analytics
      - SMTP_HOST_ADDR=smtp.XXXXX.com
      - SMTP_HOST_PORT=465
      - SMTP_USER_NAME=xxxx@domain.com
      - SMTP_USER_PWD=XXXXX
      - SMTP_HOST_SSL_ENABLED=true
      - SMTP_RETRIES=2
      - CRON_ENABLED=true

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
```

</details>
