### DISCUSSION TITLE
Second user on selfhost instance cannot be owner of a website (needs a subscription)

### DISCUSSION THREAD

**Discussion by GoudronViande24** [plausible/analytics#3450] [Self-Hosted Support]
I tried creating a second user and transferring ownership of a website. The message showing up when accepting says that it will need an active subscription, even though that's not something on the selfhosted version. I clicked accept anyway (it's a test website I don't care about it's data), and now the following is showing up instead of the stats:

![image](https://github.com/plausible/analytics/assets/42936037/4170595e-a942-4c5d-8f31-6c71b32d8a64)

**Comment by GoudronViande24** [comment]
Of course the manage my subscription is not working, it redirects to user's settings page which has nothing about subscriptions.

Is that a bug? Should I open an issue for this?

**Comment by GoudronViande24** [comment]
oh and when I add a new website with the second account, there is also the subscription message showing up:
![image](https://github.com/plausible/analytics/assets/42936037/7066f28a-9916-4848-81d0-de631e8e517f)

**Comment by ruslandoga** [comment]
👋 @GoudronViande24 

Can you please share your configuration? `docker-compose.yml`, how you deploy, env vars (with secrets redacted), etc.

**Reply by zenminimalist** [reply]
Would the ENV variable `DISABLE_SUBSCRIPTION=true` in the plausible server solve his issue?

**Reply by ruslandoga** [reply]
This env var has been removed for about two years: https://github.com/plausible/analytics/commit/e873d790e5117f08102e28be1f7f1926ec35d877 Right now subscriptions are disabled by default.

All currently supported env vars (both documented and undocumented) can be found in https://github.com/plausible/analytics/blob/master/config/runtime.exs

**Comment by GoudronViande24** [comment]
Here are the configuration files:

## docker-compose.yml
```yml
version: "3.3"
services:
#  mail:
#    image: bytemark/smtp
#    restart: always

  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=[REDACTED]

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    restart: always
    volumes:
      - ./event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v2.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
#      - mail
    env_file:
      - plausible-conf.env

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=[REDACTED]
```

## plausible-conf.env
```env
BASE_URL=[REDACTED]
SECRET_KEY_BASE=[REDACTED]
MAILER_EMAIL=[REDACTED]
MAILER_NAME=[REDACTED]
SMTP_HOST_ADDR=[REDACTED]
SMTP_HOST_PORT=465
SMTP_USER_NAME=[REDACTED]
SMTP_USER_PWD=[REDACTED]
SMTP_HOST_SSL_ENABLED=true
SMTP_RETRIES=2
DISABLE_REGISTRATION=invite_only
MAXMIND_LICENSE_KEY=[REDACTED]
MAXMIND_EDITION=GeoLite2-City
```

@ruslandoga do you need something else?

Thanks in advance for the support!
