### DISCUSSION TITLE
Plausible hosted not starting

### DISCUSSION THREAD

**Discussion by rbndg** [plausible/analytics#3549] [Self-Hosted Support]
Plausible is stuck on looping over and over again.
Running latest version of the repo
Docker version 24.0.7, build afdd53
Ubuntu 20.04.1 LTS

```
hosting-plausible_db-1         |
hosting-plausible_db-1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
hosting-plausible_db-1         |
hosting-mail-1                 |     1 LOG: MAIN
hosting-mail-1                 |     1   exim 4.89 daemon started: pid=1, -q30m, listening for SMTP on port 25 (IPv6 and IPv4)
hosting-plausible_db-1         | 2023-11-23 02:43:05.928 UTC [1] LOG:  starting PostgreSQL 14.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
hosting-plausible_db-1         | 2023-11-23 02:43:05.928 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
hosting-plausible_db-1         | 2023-11-23 02:43:05.928 UTC [1] LOG:  listening on IPv6 address "::", port 5432
hosting-plausible_db-1         | 2023-11-23 02:43:05.931 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
hosting-plausible_db-1         | 2023-11-23 02:43:05.947 UTC [22] LOG:  database system was shut down at 2023-11-23 02:18:18 UTC
hosting-plausible_db-1         | 2023-11-23 02:43:05.989 UTC [1] LOG:  database system is ready to accept connections
hosting-plausible_events_db-1  | Processing configuration file '/etc/clickhouse-server/config.xml'.
hosting-plausible_events_db-1  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
hosting-plausible_events_db-1  | Merging configuration file '/etc/clickhouse-server/config.d/logging.xml'.
hosting-plausible_events_db-1  | Logging warning to /var/log/clickhouse-server/clickhouse-server.log
hosting-plausible_events_db-1  | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
hosting-plausible_events_db-1  | 2023.11.23 02:43:11.808824 [ 1 ] {} <Warning> Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.3.7.5 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
hosting-plausible_events_db-1  | 2023.11.23 02:43:11.810043 [ 1 ] {} <Warning> Application: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.3.7.5 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
hosting-plausible_events_db-1  | 2023.11.23 02:43:11.810272 [ 1 ] {} <Warning> Application: Listen [::]:9004 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.3.7.5 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
hosting-plausible_events_db-1  | 2023.11.23 02:43:11.810395 [ 1 ] {} <Warning> Application: Listen [::]:9005 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.3.7.5 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
hosting-plausible_events_db-1  | 2023.11.23 02:43:11.957410 [ 1 ] {} <Warning> Application: Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.3.7.5 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
hosting-plausible-1            | Loading plausible..
hosting-plausible-1            | Starting dependencies..
hosting-plausible-1            | Starting repos..
hosting-plausible-1            | create Plausible.Repo database if it doesn't exist
hosting-plausible-1            | ** (MatchError) no match of right hand side value: {:error, "connection not available and request was dropped from queue after 2000ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Ensuring your database is available and that you can connect to it\n  2. Tracking down slow queries and making sure they are running fast enough\n  3. Increasing the pool_size (although this increases resource consumption)\n  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval\n\nSee DBConnection.start_link/2 for more information\n"}
hosting-plausible-1            |     (plausible 0.0.1) lib/plausible_release.ex:40: anonymous fn/2 in Plausible.Release.createdb/0
hosting-plausible-1            |     (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
hosting-plausible-1            |     (plausible 0.0.1) lib/plausible_release.ex:39: Plausible.Release.createdb/0
hosting-plausible-1            |     nofile:1: (file)
hosting-plausible-1            |     (stdlib 4.2) erl_eval.erl:748: :erl_eval.do_apply/7
hosting-plausible-1 exited with code 0
```

**Comment by ruslandoga** [comment]
👋 @rbndg 

The error means that `plausible` can't access PostgreSQL to create the database within 2 seconds.

> Running latest version of the repo

By the repo, do you mean `plausible/hosting`? Please share your `docker-compose.yml` and any other relevant information about your setup :)

**Comment by rbndg** [comment]
thank you for your response.
Yes, i'm running latest version of plausible/hosting

docker-compose.yml
```
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

  plausible_events_db:
    image: clickhouse/clickhouse-server:23.3.7.5-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v2.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 127.0.0.1:8884:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  ```
