### DISCUSSION TITLE
Basic setup not working on Digital Ocean docker droplet

### DISCUSSION THREAD

**Discussion by StephenHaney** [plausible/analytics#3607] [Self-Hosted Support] [answered]
Edit: this is due to trying to use `MAXMIND` for city data... once I remove the `MAXMIND` config options, everything works as expected.

Solution: the VM needed at least 2GB of memory to finish setting up with `MAXMIND` configuration. I was trying to use 1GB and the container was getting `OOMKilled`.

---

Hello, I'm following a minimal set of steps to get up and running but it doesn't appear to be working. Can anyone point me in the right direction?

When I try to `curl http://localhost:8000` I either get:
`curl: (52) Empty reply from server` or `curl: (56) Recv failure: Connection reset by peer`

Here is my `plausible-conf.env`:
```
BASE_URL=https://subdomain.my-real-domain.com
SECRET_KEY_BASE=key-here
MAXMIND_LICENSE_KEY=my-key-here
MAXMIND_EDITION=GeoLite2-City
```

Here is my `docker-compose.yml`:
```
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:23.3.7.5-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v2.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
```

And I'm attaching my `docker compose logs` after running `docker compose up -d`. Definitely some suspicious errors in here! 
[plausible-docker-compose-logs.txt](https://github.com/plausible/analytics/files/13629543/plausible-docker-compose-logs.txt)

I appreciate any help!
