### DISCUSSION TITLE
Self Host Data Differs Massively From Cloud

### DISCUSSION THREAD

**Discussion by pymike00** [plausible/analytics#3619] [Self-Hosted Support]
Hello everyone, 

I have setup a new self host instance of Plausible 2.0 using https://github.com/plausible/hosting

However as you can see from the screenshots attached, the data differ massively between the two instances and in ways you would not expect.

Although the graphs look somehow similar, details differ so much it seems like they are coming from different websites.

How is this even possible?

Thoughts?

![CLOUD-PLAUSIBLE](https://github.com/plausible/analytics/assets/32687496/93f1bdc8-8a71-42a4-a2aa-e15a768ee7d3)
![SELF-HOST-PLAUSIBLE](https://github.com/plausible/analytics/assets/32687496/26e847f7-cf45-458d-abc4-492246c2fdd1)

**Comment by digital88** [comment]
Did you put 2 plausible scripts on same page? Maybe this causes conflicts?

**Reply by pymike00** [reply]
Hi Digital88

Yes, I am indeed using both scripts at the same time.

I haven't thought about it as a possible cause for conflicts, as both page view counters are so similar yet all other params are *that* far apart.

I will now try removing the cloud script, let's see what happens, I will keep you updated.

Thanks for your reply!

**Reply by pymike00** [reply]
Ok so, here is today's data after removing the cloud integration script.

As you can see, self host data resembles yesterday's one, so I don't think that has anything to do with it.

This is very concerning. Thoughts?


![self-host-1412](https://github.com/plausible/analytics/assets/32687496/075bcffa-438f-4f45-a557-4e2e410be7da)

**Reply by digital88** [reply]
1) Check that your selfhosted instance is actually getting requests to /api/event/ endpoint. Maybe some requests are being dropped.
2) Check for adblockers blocking requests to your selfhosted domain.

**Reply by pymike00** [reply]
The domain is brand new; I have checked the nginx logs for requests on /api/event/, everything seems fine with status code 202 

What I find most weird is how the page views counter has almost identical values, while other values differ so much from one another!

I have now doubled the RAM capacity of the droplet, just because I don't know what else to do software side. I don't really expect anything from this as looking at the server stats everything seems fine and requests are clearly coming through.

Anyways let's see! I will report again tomorrow.

Thank You for your time.
![nginx](https://github.com/plausible/analytics/assets/32687496/59661502-be6f-4d84-a43e-6e340ecc2bd0)

**Reply by pymike00** [reply]
Hi there,

As expected, doubling the RAM has no effect, and data still looks the same.

I don't know what else to think about.

Could there be any parameter I may have misconfigured, somehow?

Thanks

**Comment by ruslandoga** [comment]
@pymike00 👋

Could you please describe your setup in more detail? For example, what (if any) changes have you made to `docker-compose.yml` and `plausible-conf.env`?

**Reply by pymike00** [reply]
Hi there @ruslandoga !!

Sure, here is docker-compose.yml

```
version: "3.3"
services:

  # Adding the nginx image here
  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - plausible

  certbot:
     image: certbot/certbot
     container_name: certbot
     volumes:
       - ./certbot/conf:/etc/letsencrypt
       - ./certbot/www:/var/www/certbot
     command: certonly --webroot -w /var/www/certbot --force-renewal --email mymail@mymail.com -d my-website-com --agree-tos

  mail:
    image: bytemark/smtp
    restart: always
    networks:
      - plausible

  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=######
    networks:
      - plausible

  plausible_events_db:
    image: clickhouse/clickhouse-server:23.3.7.5-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - plausible

  plausible:
    image: plausible/analytics:v2.0
    container_name: plausible
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env
    networks:
      - plausible

volumes:
  db-data:
    driver: local
  event-data:
    driver: local

# Add the network
networks:
  plausible:
    driver: bridge
```

here is my nginx.conf

```
server {
  listen 80;
  server_name my-website.com;
  resolver 127.0.0.11;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;         # also tried to just "listen 443 ssl;" with no effect
  ssl_certificate     /etc/letsencrypt/live/my-website.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/my-website.com/privkey.pem;
  server_name my-website.com;

  location ~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location  / {
    proxy_pass http://plausible:8000;
  }
}
```

And here is plausible-conf.env

```
BASE_URL=http://my-website.com
SECRET_KEY_BASE=my-key
DISABLE_REGISTRATION=invite_only
```

thank you for your time, appreciated!!! 🙌🏻 

p.s. again the thing I find most interesting is that the page view counter is almost the same, while everything else is *so much* different
