### DISCUSSION TITLE
Click house not able to connect - non existing domain

### DISCUSSION THREAD

**Discussion by jaynguyens** [plausible/analytics#3917] [Self-Hosted Support] [answered]
Not sure why but am unable to run on my raspberry pi - would someone able to help me.

I ran `git clone https://github.com/plausible/community-edition plausible` and update the docker compose with the version 2.1.

In `plausible-conf.env`
```
BASE_URL='https://plausible.[mydomain]'
SECRET_KEY_BASE=[openssl rand -base64 48]
TOTP_VAULT_KEY=[openssl rand -base64 32]
```

In `docker-compose.yml`
```
version: "3.3"
services:
  plausible_db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:23.3.7.5-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.0-rc.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
```

Here is the logs

```
nguyen@home:~/plausible $ logs
WARN[0000] /home/nguyen/plausible/docker-compose.yml: `version` is obsolete
plausible_db-1  |
plausible_db-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
plausible_db-1  |
plausible_db-1  | 2024-03-20 11:39:38.330 UTC [1] LOG:  starting PostgreSQL 14.11 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
plausible_db-1  | 2024-03-20 11:39:38.331 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
plausible_db-1  | 2024-03-20 11:39:38.331 UTC [1] LOG:  listening on IPv6 address "::", port 5432
plausible_db-1  | 2024-03-20 11:39:39.034 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
plausible_db-1  | 2024-03-20 11:39:39.061 UTC [21] LOG:  database system was shut down at 2024-03-20 11:38:50 UTC
plausible_db-1  | 2024-03-20 11:39:39.080 UTC [1] LOG:  database system is ready to accept connections
plausible-1 exited with code 0
plausible-1     | Loading plausible..
plausible-1     | Starting dependencies..
plausible-1     | Starting repos..
plausible-1     | create Plausible.Repo database if it doesn't exist
plausible-1     | 11:39:53.180 [error] Ch.Connection (#PID<0.176.0>) failed to connect: ** (Mint.TransportError) connection refused
plausible-1     | 11:39:53.180 [error] Ch.Connection (#PID<0.175.0>) failed to connect: ** (Mint.TransportError) connection refused
plausible-1     | create Plausible.IngestRepo database if it doesn't exist
plausible-1     | ** (MatchError) no match of right hand side value: {:error, %Mint.TransportError{reason: :econnrefused}}
plausible-1     |     (plausible 0.0.1) lib/plausible_release.ex:47: anonymous fn/2 in Plausible.Release.createdb/0
plausible-1     |     (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
plausible-1     |     (plausible 0.0.1) lib/plausible_release.ex:46: Plausible.Release.createdb/0
plausible-1     |     nofile:1: (file)
plausible-1     |     (stdlib 5.2) erl_eval.erl:750: :erl_eval.do_apply/7
plausible-1     | Loading plausible..
plausible-1     | Starting dependencies..
plausible-1     | Starting repos..
plausible-1     | create Plausible.Repo database if it doesn't exist
plausible-1     | 11:40:47.895 [error] Ch.Connection (#PID<0.176.0>) failed to connect: ** (Mint.TransportError) non-existing domain
plausible-1     | 11:40:47.895 [error] Ch.Connection (#PID<0.175.0>) failed to connect: ** (Mint.TransportError) non-existing domain
plausible-1     | create Plausible.IngestRepo database if it doesn't exist
plausible-1     | ** (MatchError) no match of right hand side value: {:error, %Mint.TransportError{reason: :nxdomain}}
plausible-1     |     (plausible 0.0.1) lib/plausible_release.ex:47: anonymous fn/2 in Plausible.Release.createdb/0
plausible-1     |     (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
plausible-1     |     (plausible 0.0.1) lib/plausible_release.ex:46: Plausible.Release.createdb/0
plausible-1     |     nofile:1: (file)
plausible-1     |     (stdlib 5.2) erl_eval.erl:750: :erl_eval.do_apply/7
```

```
nguyen@home:~/plausible $ docker network ls
NETWORK ID     NAME                   DRIVER    SCOPE
ad08dc972fc1   applications_default   bridge    local
c711d15cf644   bridge                 bridge    local
6cdf4952c6bd   host                   host      local
ec1b962e8d0a   none                   null      local
34df89d5e0ac   plausible              bridge    local
8db50676c141   plausible_default      bridge    local
nguyen@home:~/plausible $ docker ps
CONTAINER ID   IMAGE                                             COMMAND                  CREATED          STATUS                                    PORTS                                                                                                         NAMES
6de927c73121   ghcr.io/plausible/community-edition:v2.1.0-rc.0   "/entrypoint.sh sh -…"   12 minutes ago   Up 8 seconds                              127.0.0.1:8000->8000/tcp                                                                                      plausible-plausible-1
54aa49981cd5   postgres:14-alpine                                "docker-entrypoint.s…"   12 minutes ago   Up 12 minutes                             5432/tcp                                                                                                      plausible-plausible_db-1
f7338d3ec399   clickhouse/clickhouse-server:23.3.7.5-alpine      "/entrypoint.sh"         12 minutes ago   Restarting (132) Less than a second ago                                                                                                                 plausible-plausible_events_db-1
d069a5e23b9b   jc21/nginx-proxy-manager:latest                   "/init"                  6 months ago     Up 2 hours                                0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:90->80/tcp, :::90->80/tcp, 0.0.0.0:91->81/tcp, :::91->81/tcp   applications-nginx-1
70e98489dbc3   b4a0ae103759                                      "/usr/bin/entry.sh /…"   6 months ago     Up 2 hours (healthy)                      3012/tcp, 0.0.0.0:92->80/tcp, :::92->80/tcp                                                                   vaultwarden
```
