### DISCUSSION TITLE
Plausible CE doesn't log pageviews.

### DISCUSSION THREAD

**Discussion by byemc** [plausible/analytics#4139] [Self-Hosted Support]
I recently upgraded from v1.4 to v2.1. I managed to migrate my data. However, no pageviews are logged. I downgraded to v2.0 and it was working again! 
Looking in my docker logs, I found something like "No such column", alongside errors from Clickhouse saying the same thing.

```bash
plausible_events_db-1  | 2024.05.24 14:44:38.817198 [ 745 ] {ebc394ed-9d33-4ffc-8461-8fc344f429b7} <Error> executeQuery: Code: 16. DB::Exception: No such column revenue_source_amount in table plausible_events_db.events_v2 (6bef22d1-9213-406a-bb8e-121f8aa6d54f). (NO_SUCH_COLUMN_IN_TABLE) (version 24.3.3.102 (official build)) (from 172.30.0.5:51540) (in query: INSERT INTO events_v2 (name, site_id, hostname, pathname, user_id, session_id, timestamp, meta.key, meta.value, revenue_source_amount, revenue_source_currency, revenue_reporting_amount, revenue_reporting_currency, referrer, referrer_source, utm_medium, utm_source, utm_campaign, utm_content, utm_term, country_code, subdivision1_code, subdivision2_code, city_geoname_id, screen_size, operating_system, operating_system_version, browser, browser_version) FORMAT RowBinaryWithNamesAndTypes ), Stack trace (when copying this message, always include the lines below):
plausible_events_db-1  | 
plausible_events_db-1  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
plausible_events_db-1  | 1. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x0000000007f0d65d
plausible_events_db-1  | 2. DB::InterpreterInsertQuery::getSampleBlockImpl(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool) @ 0x0000000010de9253
plausible_events_db-1  | 3. DB::InterpreterInsertQuery::getSampleBlock(DB::ASTInsertQuery const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, bool, bool) @ 0x0000000010de819f
plausible_events_db-1  | 4. DB::InterpreterInsertQuery::execute() @ 0x0000000010dec18b
plausible_events_db-1  | 5. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001126e162
plausible_events_db-1  | 6. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x000000001127341e
plausible_events_db-1  | 7. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000122f0075
plausible_events_db-1  | 8. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000122f4b34
plausible_events_db-1  | 9. DB::HTTPServerConnection::run() @ 0x00000000123740da
plausible_events_db-1  | 10. Poco::Net::TCPServerConnection::start() @ 0x0000000014c9b8d2
plausible_events_db-1  | 11. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014c9c719
plausible_events_db-1  | 12. Poco::PooledThread::run() @ 0x0000000014d94e81
plausible_events_db-1  | 13. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014d9341d
plausible_events_db-1  | 14. ? @ 0x00007fa61bee2609
plausible_events_db-1  | 15. ? @ 0x00007fa61be07353
plausible_events_db-1  | 
plausible_events_db-1  | 2024.05.24 14:44:38.817465 [ 745 ] {ebc394ed-9d33-4ffc-8461-8fc344f429b7} <Error> DynamicQueryHandler: Code: 16. DB::Exception: No such column revenue_source_amount in table plausible_events_db.events_v2 (6bef22d1-9213-406a-bb8e-121f8aa6d54f). (NO_SUCH_COLUMN_IN_TABLE), Stack trace (when copying this message, always include the lines below):
plausible_events_db-1  | 
plausible_events_db-1  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
plausible_events_db-1  | 1. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x0000000007f0d65d
plausible_events_db-1  | 2. DB::InterpreterInsertQuery::getSampleBlockImpl(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool, bool) @ 0x0000000010de9253
plausible_events_db-1  | 3. DB::InterpreterInsertQuery::getSampleBlock(DB::ASTInsertQuery const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, bool, bool) @ 0x0000000010de819f
plausible_events_db-1  | 4. DB::InterpreterInsertQuery::execute() @ 0x0000000010dec18b
plausible_events_db-1  | 5. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001126e162
plausible_events_db-1  | 6. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x000000001127341e
plausible_events_db-1  | 7. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000122f0075
plausible_events_db-1  | 8. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000122f4b34
plausible_events_db-1  | 9. DB::HTTPServerConnection::run() @ 0x00000000123740da
plausible_events_db-1  | 10. Poco::Net::TCPServerConnection::start() @ 0x0000000014c9b8d2
plausible_events_db-1  | 11. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014c9c719
plausible_events_db-1  | 12. Poco::PooledThread::run() @ 0x0000000014d94e81
plausible_events_db-1  | 13. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014d9341d
plausible_events_db-1  | 14. ? @ 0x00007fa61bee2609
plausible_events_db-1  | 15. ? @ 0x00007fa61be07353
plausible_events_db-1  |  (version 24.3.3.102 (official build))
plausible-1            | 14:44:38.819 [error] GenServer Plausible.Event.WriteBuffer terminating
plausible-1            | ** (Ch.Error) Code: 16. DB::Exception: No such column revenue_source_amount in table plausible_events_db.events_v2 (6bef22d1-9213-406a-bb8e-121f8aa6d54f). (NO_SUCH_COLUMN_IN_TABLE) (version 24.3.3.102 (official build))
plausible-1            | 
plausible-1            |     (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
plausible-1            |     (stdlib 5.2) gen_server.erl:1143: :gen_server.try_terminate/3
plausible-1            |     (stdlib 5.2) gen_server.erl:1339: :gen_server.terminate/10
plausible-1            |     (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
plausible-1            | Last message: :tick
```

Did I do something wrong? I found a [similar discussion](https://github.com/plausible/analytics/discussions/3246) but I don't think the fix worked (I ran it directly in Clickhouse).

My docker-compose (the ports on the two databases were for debugging and are disabled):
```yml
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    # Plausible v2.0.0 was tested against PostgreSQL versions 12, 13, and 14
    # https://github.com/plausible/analytics/blob/v2.0.0/.github/workflows/elixir.yml#L16
    image: postgres:14-alpine
    restart: always
      #ports:
      #  - 100.99.123.97:5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
      #    ports:
      #      - 100.99.123.97:5432:5432
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1
    #    image: plausible/analytics:v2.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 5049:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  event-logs:
    driver: local
```
