### DISCUSSION TITLE
MacOS M1 fresh install fail

### DISCUSSION THREAD

**Discussion by OptimusKoala** [plausible/analytics#4154] [Self-Hosted Support]
Hi, I've juste clone the repo with:

`$ git clone https://github.com/plausible/community-edition hosting`

I have thoses errors in my 'hosting-plausible-1' and the container in in crash loop. 

> Running migrations for Elixir.Plausible.Repo
> 2024-05-28 13:37:11 ** (ArgumentError) could not call Module.put_attribute/3 because the module Plausible.Repo.Migrations.AddPageviews is already compiled
> 2024-05-28 13:37:11     (elixir 1.16.0) lib/module.ex:2360: Module.assert_not_readonly!/2
> 2024-05-28 13:37:11     (elixir 1.16.0) lib/module.ex:2041: Module.__put_attribute__/5
> 2024-05-28 13:37:11     lib/plausible-0.0.1/priv/repo/migrations/20181214201821_add_new_visitor_to_pageviews.exs:2: (module)

I'm running macOS 14.4.1 with M1 chip
Docker version: v4.30.0

**Comment by ruslandoga** [comment]
👋 @OptimusKoala 

I wasn't able to reproduce this error on a fresh install on M2 mac.

Please share your `docker-compose.yml`, `plausible-conf.env` (with secrets redacted), and the Docker Compose commands you used.

**Reply by OptimusKoala** [reply]
plausible-conf.env:
```
BASE_URL=http://plausible.example.com
SECRET_KEY_BASE=GLVzDZW04FzuS1gMcmBRVhwgd4Gu9YmSl/k/TqfTUXti7FLBd7aflXeQDdwCj6Cz
TOTP_VAULT_KEY=dsxvbn3jxDd16az2QpsX5B8O+llxjQ2SJE2i5Bzx38I=
```

docker-compose.yml:
```
services:
  plausible_db:
    # Plausible v2.1.0 was tested against PostgreSQL versions 15 and 16
    # https://github.com/plausible/analytics/blob/v2.1.0/.github/workflows/elixir.yml#L21-L32
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  event-logs:
    driver: local
 ```
    
Started with: docker-compose up -d
