### DISCUSSION TITLE
Could not check origin for Phoenix.Socket transport

### DISCUSSION THREAD

**Discussion by nicedevil007** [plausible/analytics#4163] [Self-Hosted Support]
Hey guys, I have a VM that is running AlmaLinux 9.4 with docker installed on it.
I can access my plausible page and try to register. After filling all needed fields to register nothing happens after I click on the register button.

In the docker logs I can find this:

```bash
plausible_db-plausible-1            | 13:36:20.166 [error] Could not check origin for Phoenix.Socket transport.
plausible_db-plausible-1            | 
plausible_db-plausible-1            | Origin of the request: http://192.168.125.2:8000
plausible_db-plausible-1            | 
plausible_db-plausible-1            | This happens when you are attempting a socket connection to
plausible_db-plausible-1            | a different host than the one configured in your config/
plausible_db-plausible-1            | files. For example, in development the host is configured
plausible_db-plausible-1            | to "localhost" but you may be trying to access it from
plausible_db-plausible-1            | "127.0.0.1". To fix this issue, you may either:
plausible_db-plausible-1            | 
plausible_db-plausible-1            |   1. update [url: [host: ...]] to your actual host in the
plausible_db-plausible-1            |      config file for your current environment (recommended)
plausible_db-plausible-1            | 
plausible_db-plausible-1            |   2. pass the :check_origin option when configuring your
plausible_db-plausible-1            |      endpoint or when configuring the transport in your
plausible_db-plausible-1            |      UserSocket module, explicitly outlining which origins
plausible_db-plausible-1            |      are allowed:
plausible_db-plausible-1            | 
plausible_db-plausible-1            |         check_origin: ["https://example.com",
plausible_db-plausible-1            |                        "//another.com:888", "//other.com"]
```

My docker compose looks like this:

```yaml
services:
  plausible_db:
    # Plausible v2.1.0 was tested against PostgreSQL versions 15 and 16
    # https://github.com/plausible/analytics/blob/v2.1.0/.github/workflows/elixir.yml#L21-L32
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - ./event-data:/var/lib/clickhouse
      - ./event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db
      migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - 8000:8000
    env_file:
      - .env
volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  event-logs:
    driver: local
```

and my .env file looks like this:

```java
BASE_URL=https://<REDACTED>
SECRET_KEY_BASE=<REDACTED>
TOTP_VAULT_KEY=<REDACTED>
```

Plausible is running behind my nginx-proxymanager, which is configured this way:

![image](https://github.com/plausible/analytics/assets/17103076/eea057ed-0aa1-4254-bfff-d479138702c8)

Of course I added a ssl cert there as well :)

I have a friends environment running as well and he got it up and working with the same settings, just different URl and different Keys, same docker-compose.yaml etc. So what am I missing here?
