### DISCUSSION TITLE
Registration UI broken

### DISCUSSION THREAD

**Discussion by DrMaxNix** [plausible/analytics#4164] [Self-Hosted Support]
Heyo, me again! After some testing I noticed that the register UI is broken.
When accessing `/register`, the register UI comes up and you can enter name, email and passwd.
When clicking on the "Create account" submit button, the data is sent to the server and even the db entry for the new user is created, but the UI is not switching over to the second registration step. It stays on the first step "Register".
Clicking the submit button again gives me a notice for Email input "has already been taken" due to `ERROR:  duplicate key value violates unique constraint "users_email_index"` in log.

I have verified this behaviour on a brand new instance as well (CE v2.1, fresh databases).
I have also tested directly accessing the port without a reverse proxy, same behavior.
I think this is related to the problems described in #4140

**Comment by ruslandoga** [comment]
👋 @DrMaxNix 

So to get things clear:
- you used apache without WebSocket connections being allowed
- you created an account but the form failed to send you to the next step since it uses WebSockets
- you tried creating an account again without a reverse proxy but now the email is taken

Is that right? If so, can you try creating another account with a different email address? Please make sure WebSockets are allowed by your reverse proxy :)

**Reply by ruslandoga** [reply]
If the issue repeats please post your full configuration (reverse proxy if any, its config, docker-compose.yml, plausible-conf.env) and logs both from the server (docker compose logs) and from the browser console.

**Reply by DrMaxNix** [reply]
Nope, as I have already stated in my initial message, I have also tested the whole without any reverse proxy, completely new setup, new database.

**Reply by ruslandoga** [reply]
How is the linked post related then?

**Reply by ruslandoga** [reply]
Do you get the "email being taken" notice on a clean database? If not, what's the problem exactly?

**Reply by DrMaxNix** [reply]
Same UI behaviour

**Reply by ruslandoga** [reply]
Please see https://github.com/plausible/analytics/discussions/4160 as well. It might be related.

**Reply by DrMaxNix** [reply]
### docker-compose.yml
```yml
version: "3.3"
services:
  plausible_db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    volumes:
      - ./my_versioned_sessions.ex:/app/lib/plausible-0.0.1/priv/ingest_repo/migrations/20240222082911_sessions_v2_versioned_collapsing_merge_tree.exs:ro
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - "50324:8000"
    env_file:
      - plausible-conf.env
```

### plausible-conf.env
```env
BASE_URL=http://mn5.tjdev.de:50324
PORT=8000
LISTEN_IP=0.0.0.0
SECRET_KEY_BASE=<super secret token>
TOTP_VAULT_KEY=<super secret token>
DISABLE_REGISTRATION=false
```

### docker logs
The only lines I get during the whole test are these when trying same email address again:
```
plausible_db-1         | 2024-05-30 14:48:51.204 UTC [37] ERROR:  duplicate key value violates unique constraint "users_email_index"
plausible_db-1         | 2024-05-30 14:48:51.204 UTC [37] DETAIL:  Key (email)=(8a6d87ad@m.drmaxnix.de) already exists.
plausible_db-1         | 2024-05-30 14:48:51.204 UTC [37] STATEMENT:  INSERT INTO "users" ("name","email","password_hash","email_verified","totp_enabled","accept_traffic_until","trial_expiry_date","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING "id"
```

### browser console
No messages
