### DISCUSSION TITLE
Caddy-gen doesn't support ARM

### DISCUSSION THREAD

**Discussion by rmens** [plausible/analytics#4180] [Self-Hosted Support]
When following the steps in the repo to set-up a self-hosted Plausible CE there is this error:

```
caddy-gen The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Looking at https://hub.docker.com/r/wemakeservices/caddy-gen/tags it seems there's only amd64 versions. Is it possible to switch to a supported Caddy image? The official one seems to support ARM.

**Comment by manelephant** [comment]
Does anyone knows how to install it cleanly on Mac Arm ?

**Reply by ElastiCourse** [reply]
> Does anyone knows how to install it cleanly on Mac Arm ?

@manelephant @rmens 
It's quite simple to use it with Caddy. I have tested it on ARM64 and it works fine.

1. Download [custom](https://caddyserver.com/download) build of Caddy. Make sure you choose your favorite DNS plugin and change arch to Linux Arm64 or MacOS Arm64 (Apple silicon: run extra command on downloaded binary `xattr -d com.apple.quarantine`)
2. Rename downloaded binary to `caddy` and make it executable. 
3. Docker's config compose.yaml:
```
services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 443:443/udp # Needed for HTTP/3.
    volumes:
      - ./caddy:/usr/bin/caddy  # Your custom build of Caddy.
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      EMAIL: "youremail@domain.com"
      LOG_FILE: "/data/access.log"
  plausible_db:
    # Plausible v2.1.1 was tested against PostgreSQL versions 15 and 16
    # https://github.com/plausible/analytics/blob/v2.1.1/.github/workflows/elixir.yml#L21-L32
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - ./event-data:/var/lib/clickhouse
      - ./event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.1
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - plausible-conf.env
```
Caddy uses `Caddyfile` to configure domains and certificates. 
Example 1: The config below uses a wildcard domain certificate:
```
*.services.elasticourse.com {
  log {
    level INFO
    output file {$LOG_FILE} {
      roll_size 10MB
      roll_keep 10
    }
  }

  # Use the ACME DNS-01 challenge to get a cert for the configured domain.
  tls {
  dns route53 {
    max_retries 10
    region "us-east-1"
    max_wait_dur 60,
    wait_for_propagation true
      }
    }

  encode zstd gzip

  @counter host counter.services.elasticourse.com
  handle @counter {
    reverse_proxy plausible:8000
  }

```
Example 2:
Using a free DuckDNS subdomain (works locally as well): [Instructions](https://github.com/dani-garcia/vaultwarden/wiki/Running-a-private-vaultwarden-instance-with-Let%27s-Encrypt-certs)
