### DISCUSSION TITLE
plausible db wont start

### DISCUSSION THREAD

**Discussion by 1mfaasj** [plausible/analytics#4296] [Self-Hosted Support]
Hi
plausible is having trouble starting because of the error below, any idea how to solve it?

```
Loading plausible..
Starting dependencies..
Starting repos..
create Plausible.Repo database if it doesn't exist
13:00:38.361 [error] Ch.Connection (#PID<0.175.0>) failed to connect: ** (Mint.TransportError) non-existing domain
13:00:38.361 [error] Ch.Connection (#PID<0.176.0>) failed to connect: ** (Mint.TransportError) non-existing domain
create Plausible.IngestRepo database if it doesn't exist
** (MatchError) no match of right hand side value: {:error, %Mint.TransportError{reason: :nxdomain}}
    (plausible 0.0.1) lib/plausible_release.ex:47: anonymous fn/2 in Plausible.Release.createdb/0
    (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plausible 0.0.1) lib/plausible_release.ex:46: Plausible.Release.createdb/0
    nofile:1: (file)
    (stdlib 5.2) erl_eval.erl:750: :erl_eval.do_apply/7
```

the database has started successfuly though:
```
2024-07-01 12:51:25.985 UTC [1] LOG:  starting PostgreSQL 16.3 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
2024-07-01 12:51:25.986 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-07-01 12:51:25.986 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-07-01 12:51:25.989 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-07-01 12:51:26.004 UTC [32] LOG:  database system was shut down at 2024-07-01 12:51:16 UTC
2024-07-01 12:51:26.526 UTC [1] LOG:  database system is ready to accept connections
2024-07-01 12:56:26.070 UTC [30] LOG:  checkpoint starting: time
2024-07-01 12:56:26.084 UTC [30] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.001 s, total=0.014 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB; lsn=0/1D73100, redo lsn=0/1D730C8
```

how my compose looks like (I removed some passwords etc)
```
version: "3.3"
services:
  plausible_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - /docker/plausible/db1:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=plausible
      - POSTGRES_PASSWORD=plausible
      - POSTGRES_DB=plausible

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - /docker/plausible/eventsdb1:/var/lib/clickhouse
      - /docker/plausible/eventslog1:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.1
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - 8888:8000
    environment:
      - TOTP_VAULT_KEY=XXX
      - GOOGLE_CLIENT_ID=XXX-XXX.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=XXX-XXX
      - ADMIN_USER_EMAIL=XXX@gmail.com
      - ADMIN_USER_NAME=admin
      - ADMIN_USER_PWD=XXX
      - BASE_URL=https://plausible.mydomain.com
      - SECRET_KEY_BASE=XXX
      - DATABASE_URL=postgres://plausible:plausible@plausible_db:5432/plausible
      - CLICKHOUSE_DATABASE_URL=http://plausible_events_db:8123/plausible_events_db
    restart: always

```

What I already tried:

- to use the same docker compose file and env file as described here: https://github.com/plausible/community-edition/blob/v2.1.1/docker-compose.yml
- I also added/removed the 2 environment variables (database_url) and (clickhouse_database_url) but that make no difference.
