### DISCUSSION TITLE
MySites (/sites) overview with no data after 2.0 to 2.1 Upgrade

### DISCUSSION THREAD

**Discussion by shakalandy** [plausible/analytics#4310] [Self-Hosted Support] [answered]
Hi,

i upgraded a little instance used at multiple sites from 2.0 to 2.1 and realized, that after logging in the startpage (at /sites) does not show any metrics any more. All the metrics are still there if I enter the detailed view - it is just the startpage missing the values.

There is also no error shown / no element loaded with exception/404 in the network tab.

It looks like this:

![image](https://github.com/plausible/analytics/assets/182060/a0cb4069-85db-4fc6-8330-ecf9567189e6)

What did i miss during the update?
Thanks!

**Comment by ruslandoga** [comment, marked as answer]
👋 @shakalandy 

Please make sure your reverse-proxy allows WebSocket connections.

You can check the browser console log, it probably has some WebSocket connection failing warnings.

**Reply by ruslandoga** [reply]
Here's how it could look like for nginx: https://github.com/plausible/community-edition/blob/e023cf8874871865be88d81b759c62d1032237a6/reverse-proxy/nginx/plausible#L12-L17

And apache: https://github.com/plausible/community-edition/blob/e023cf8874871865be88d81b759c62d1032237a6/reverse-proxy/apache2/plausible.conf#L7-L8

**Reply by shakalandy** [reply]
Thanks for the super fast reply, that is indeed correct.
I was looking for errors in the network tab, but it's not really shown as error, despite it does not work:

![image](https://github.com/plausible/analytics/assets/182060/e55b5d50-8ca6-4c91-b9ea-b9035ce6131f)
 
It works once I do it right, strange :D 
Thanks again!

**Comment by Ruddc** [comment]
I'm experiencing the exact same issue, including the console errors related to the websocket, but I'm not sure how to resolve it. If anyone has any suggestions or solutions, I would really appreciate your help. Thank you!

**Reply by ruslandoga** [reply]
👋 @Ruddc 

Please provide more information on your setup ;)

**Reply by Ruddc** [reply]
Wow, thats fast :-)

Running this on a DigitalOcean droplet, what other info do you need?

This happened after the upgrade to 2.1

**Reply by ruslandoga** [reply]
`docker-compose.yml`, `plausible-conf.env` (with secrets redacted), reverse proxy, anything else that seems relevant.

**Reply by Ruddc** [reply]
Ok, here we go:

 _docker-compose.yml_                                                                                                                                                                       
```
GNU nano 6.2                                                                                                                                                            
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=REDACTED

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.1
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
```

_plausible-conf_

```
BASE_URL=REDACTED
SECRET_KEY_BASE=REDACTED
TOTP_VAULT_KEY=REDACTED
DISABLE_REGISTRATION=true
GOOGLE_CLIENT_ID=REDACTED
GOOGLE_CLIENT_SECRET=REDACTED
MAILER_EMAIL=info@REDACTED
MAILER_NAME=REDACTED
SMTP_HOST_ADDR=in-v3.mailjet.com
SMTP_USER_NAME=REDACTED
SMTP_USER_PWD=REDACTED
SMTP_HOST_PORT=587

```

Not sure where to find the 'reversed proxy' info to share!
