### DISCUSSION TITLE
Missing site / data since migration to 2.1.1

### DISCUSSION THREAD

**Discussion by youradds** [plausible/analytics#4315] [Self-Hosted Support] [answered]
Hi,

We were running fine on 2.0.0. I wanted to get the latest, so updated **docker-compose.yml** to:

```
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    #image: clickhouse/clickhouse-server:22.6-alpine
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    #image: plausible/analytics:v2.0.0-rc.0
    image: ghcr.io/plausible/community-edition:v2.1.1
    restart: always
    #command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

```

Then did:

```
root@2024:# docker-compose stop plausible
Stopping hosting_plausible_1 ... done
root@2024:# docker-compose rm plausible
Going to remove hosting_plausible_1
Are you sure? [yN] y
Removing hosting_plausible_1 ... done
root@2024:# docker-compose up -d
hosting_mail_1 is up-to-date
hosting_plausible_events_db_1 is up-to-date
hosting_plausible_db_1 is up-to-date
Creating hosting_plausible_1 ... done
```

Plausible comes back up - but it has me logged out, and won't let me log in - so I'm assuming a migration needs to take place? I can see it running 2.1.1:

```
3e4352b2185c   ghcr.io/plausible/community-edition:v2.1.1       "/entrypoint.sh sh -…"   38 seconds ago   Up 38 seconds             0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   hosting_plausible_1
20cf6bf1bcf7   clickhouse/clickhouse-server:24.3.3.102-alpine   "/entrypoint.sh"         18 minutes ago   Up 14 minutes             8123/tcp, 9000/tcp, 9009/tcp                hosting_plausible_events_db_1
07d985cc9173   postgres:12                                      "docker-entrypoint.s…"   24 hours ago     Up 14 minutes             5432/tcp                                    hosting_plausible_db_1
a560b895f5e9   bytemark/smtp                                    "docker-entrypoint.s…"   24 hours ago     Up 14 minutes             25/tcp                                      hosting_mail_1
118ab25ab7f9   prodrigestivill/postgres-backup-local            "/bin/sh -c 'exec /u…"   6 months ago     Up 14 minutes (healthy)   5432/tcp                                    pg-backup
53c97614cda8   bytemark/smtp                                    "docker-entrypoint.s…"   6 months ago     Up 14 minutes             25/tcp                                      plausible_mail_1
44e581748dea   clickhouse/clickhouse-server:22.6-alpine         "/entrypoint.sh"         6 months ago     Up 14 minutes             8123/tcp, 9000/tcp, 9009/tcp                plausible_plausible_events_db_1
c132f1b26c9f   postgres:12                                      "docker-entrypoint.s…"   6 months ago     Up 14 minutes             5432/tcp                                    plausible_plausible_db_1

```

Thanks in advance

Andy
