### DISCUSSION TITLE
"FATAL:  role "root" does not exist" error every 30 seconds in the plausible_db container

### DISCUSSION THREAD

**Discussion by MisterC925** [plausible/analytics#4370] [Self-Hosted Support] [answered]
Hello!

I'm new to Plausible so I apologize if this is a stupid or irrelevant question.

Since I installed from the example docker compose file (and successfully seeing page views show up) I've been getting a consistent error every 30 seconds on the database container:
`2024-07-17 16:48:46.936 UTC [563] FATAL:  role "root" does not exist

2024-07-17 16:49:16.975 UTC [572] FATAL:  role "root" does not exist`

etc

I'm not sure if it's a functionality issue, but wanted to make sure it wasn't a sign of an installation issue or anything.

Thanks

**Comment by ruslandoga** [comment, marked as answer]
👋 @MisterC925 

This looks like someone trying to connect to PostgreSQL using `root` user, e.g. using `psql` without `-U` flag. Either way, it's not a problem if everything else is working as expected.

**Reply by MisterC925** [reply]
Thanks.  The only containers on the network are the three the compose file builds, there's no outside access (and I'm not trying to manually access anything) enabled.

I'll ignore it for now but might ask again if I notice it impacting functionality.

Thanks!

**Comment by drlogout** [comment]
I think it's the healthcheck which tries to connect as root:

```yaml
    healthcheck:
      test: pg_isready
      start_interval: 2s
      start_period: 1m
```

I replaced it with:

```yaml
    healthcheck:
      test: "pg_isready -U postgres"
      start_interval: 2s
      start_period: 1m
```

and the error is gone.
