### DISCUSSION TITLE
Messages missing a valid Message-ID

### DISCUSSION THREAD

**Discussion by stoutZero** [plausible/analytics#4421] [Self-Hosted Support] [answered]
Can anyone help me?
It has been several months since I installed plausible on a server,
but only yesterday that I noticed that the email doesn't work at all.

Yesterday I was using the `bytemark/smtp` image for mailing purposes,
that doesn't work at all. It kept sending from `hello@plausible.local`.

Right now I'm using `Bamboo.Mua`, but this simple error keep showing up in the log:
"**[error] Failed to send e-mail**"

After looking around in plausible/analytics source code, I noticed there is a `SENTRY_DSN` env.

So I set it up, and found this way better error message:
"**Messages missing a valid Message-ID header are not accepted**"

The complete error response shown in Sentry is:
`"%Mua.SMTPError{code: 550, lines: [\"550-5.7.1 [51.79.207.19] Messages missing a valid Message-ID header are not\\r\\n\", \"550-5.7.1 accepted. For more information, go to\\r\\n\", \"550-5.7.1  https://support.google.com/mail/?p=RfcMessageNonCompliant and review\\r\\n\", \"550 5.7.1 RFC 5322 specifications. d2e1a72fcca58-7106ec7236csi6376246b3a.109 - gsmtp\\r\\n\"]}"`

**Comment by stoutZero** [comment]
Oh, I forgot to include the relevant env I was using:
```
SMTP_HOST=smtp.resend.com
SMTP_HOST_SSL_ENABLED=true
SMTP_PORT=587
SMTP_PWD=<REDACTED>
SMTP_SECURITY=tls
SMTP_USERNAME=resend
```

And here is the shortened docker compose file:
<details>
  <summary>docker-compose.yml</summary>

  ```yml
  services:
    plausible:
      env_file: "./.env"
      image: 'ghcr.io/plausible/community-edition:v2.1.1'
      command: 'sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"'
      environment:
        DATABASE_URL: 'postgres://postgres:$SERVICE_PASSWORD_POSTGRES@plausible_db/plausible'
        BASE_URL: $SERVICE_FQDN_PLAUSIBLE
        SECRET_KEY_BASE: $SERVICE_BASE64_64_PLAUSIBLE
        TOTP_VAULT_KEY: $SERVICE_BASE64_TOTP
        COOLIFY_CONTAINER_NAME: plausible-ekoc4og
      depends_on:
        - plausible_db
        - plausible_events_db
      networks:
        ekoc4og: null
      labels:
        - coolify.managed=true
        - traefik.enable=true
        - caddy_ingress_network=ekoc4og
      restart: unless-stopped
      container_name: plausible-ekoc4og
    plausible_db:
      image: 'postgres:14-alpine'
      volumes:
        - 'ekoc4og_db-data:/var/lib/postgresql/data'
      environment:
        POSTGRES_DB: plausible
        POSTGRES_PASSWORD: $SERVICE_PASSWORD_POSTGRES
        COOLIFY_CONTAINER_NAME: plausible_db-ekoc4og
      networks:
        ekoc4og: null
      labels:
        - coolify.managed=true
      restart: unless-stopped
      container_name: plausible_db-ekoc4og
    plausible_events_db:
      image: 'clickhouse/clickhouse-server:24.3.3.102-alpine'
      volumes:
        -
          type: volume
          source: ekoc4og_event-data
          target: /var/lib/clickhouse
        -
          type: bind
          source: ./clickhouse/clickhouse-config.xml
          target: /etc/clickhouse-server/config.d/logging.xml
          read_only: true
        -
          type: bind
          source: ./clickhouse/clickhouse-user-config.xml
          target: /etc/clickhouse-server/users.d/logging.xml
          read_only: true
      ulimits:
        nofile:
          soft: 262144
          hard: 262144
      networks:
        ekoc4og: null
      labels:
        - coolify.managed=true
      restart: unless-stopped
      container_name: plausible_events_db-ekoc4og
      environment:
        COOLIFY_CONTAINER_NAME: plausible_events_db-ekoc4og
  volumes:
    ekoc4og_db-data:
      name: ekoc4og_db-data
    ekoc4og_event-data:
      name: ekoc4og_event-data
  networks:
    ekoc4og:
      name: ekoc4og
      external: true
  ```

</details>
