### DISCUSSION TITLE
I keep getting 502 bad gateway error while trying to self host with nginx + docker

### DISCUSSION THREAD

**Discussion by i701** [plausible/analytics#4497] [Self-Hosted Support]
I have followed the [official guide](https://github.com/plausible/community-edition/) to self host the community edition with nginx and docker and cloudflare
I have tried to deploy this using different domains and different vps also. No luck. I always keep getting 502 bad gateway error.
i have added A record to point my VPS ip to the domain i specified. 

Here is my the output of docker compose logs --follow
```
plausible-1 exited with code 0
plausible-1            | Loading plausible..
plausible-1            | Starting dependencies..
plausible-1            | Starting repos..
plausible-1            | create Plausible.Repo database if it doesn't exist
plausible-1            | create Plausible.IngestRepo database if it doesn't exist
plausible_events_db-1  | 2024.08.31 05:59:05.680445 [ 48 ] {19ad4c85-429b-4132-9f74-c7edc002f036} <Error> executeQuery: Code: 82. DB::Exception: Database plausible_events_db already exists. (DATABASE_ALREADY_EXISTS) (version 24.3.3.102 (official build)) (from 172.27.0.4:51842) (in query: CREATE DATABASE "plausible_events_db"), Stack trace (when copying this message, always include the lines below):
plausible_events_db-1  | 
plausible_events_db-1  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
plausible_events_db-1  | 1. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000766ce63
plausible_events_db-1  | 2. DB::InterpreterCreateQuery::createDatabase(DB::ASTCreateQuery&) @ 0x0000000010b5e982
plausible_events_db-1  | 3. DB::InterpreterCreateQuery::execute() @ 0x0000000010b812be
plausible_events_db-1  | 4. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001126e162
plausible_events_db-1  | 5. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x000000001127341e
plausible_events_db-1  | 6. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000122f0075
plausible_events_db-1  | 7. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000122f4b34
plausible_events_db-1  | 8. DB::HTTPServerConnection::run() @ 0x00000000123740da
plausible_events_db-1  | 9. Poco::Net::TCPServerConnection::start() @ 0x0000000014c9b8d2
plausible_events_db-1  | 10. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014c9c719
plausible_events_db-1  | 11. Poco::PooledThread::run() @ 0x0000000014d94e81
plausible_events_db-1  | 12. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014d9341d
plausible_events_db-1  | 13. ? @ 0x00007f06700bb609
plausible_events_db-1  | 14. ? @ 0x00007f066ffe0353
plausible_events_db-1  | 
plausible_events_db-1  | 2024.08.31 05:59:05.686985 [ 48 ] {19ad4c85-429b-4132-9f74-c7edc002f036} <Error> DynamicQueryHandler: Code: 82. DB::Exception: Database plausible_events_db already exists. (DATABASE_ALREADY_EXISTS), Stack trace (when copying this message, always include the lines below):
plausible_events_db-1  | 
plausible_events_db-1  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
plausible_events_db-1  | 1. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000766ce63
plausible_events_db-1  | 2. DB::InterpreterCreateQuery::createDatabase(DB::ASTCreateQuery&) @ 0x0000000010b5e982
plausible_events_db-1  | 3. DB::InterpreterCreateQuery::execute() @ 0x0000000010b812be
plausible_events_db-1  | 4. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001126e162
plausible_events_db-1  | 5. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x000000001127341e
plausible_events_db-1  | 6. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000122f0075
plausible_events_db-1  | 7. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000122f4b34
plausible_events_db-1  | 8. DB::HTTPServerConnection::run() @ 0x00000000123740da
plausible_events_db-1  | 9. Poco::Net::TCPServerConnection::start() @ 0x0000000014c9b8d2
plausible_events_db-1  | 10. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014c9c719
plausible_events_db-1  | 11. Poco::PooledThread::run() @ 0x0000000014d94e81
plausible_events_db-1  | 12. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014d9341d
plausible_events_db-1  | 13. ? @ 0x00007f06700bb609
plausible_events_db-1  | 14. ? @ 0x00007f066ffe0353
plausible_events_db-1  |  (version 24.3.3.102 (official build))
plausible-1            | Creation of Db successful!
plausible-1            | Loading plausible..
plausible-1            | Starting dependencies..
plausible-1            | Starting repos..
plausible-1            | Running migrations for Elixir.Plausible.Repo
plausible-1            | Running migrations for Elixir.Plausible.IngestRepo
plausible-1            | Migrations successful!
plausible_db-1         | 2024-08-31 05:59:20.025 UTC [25] LOG:  checkpoint starting: time
plausible_db-1         | 2024-08-31 05:59:20.204 UTC [25] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.025 s, sync=0.021 s, total=0.192 s; sync files=2, longest=0.009 s, average=0.006 s; distance=0 kB, estimate=0 kB; lsn=0/1B9DE38, redo lsn=0/1B9DE00
plausible-1 exited with code 0

```
these docker logs keep repeating whenever i try to visit the url

here is my docker-compose file

```
services:
  plausible_db:
    # Plausible v2.1.1 was tested against PostgreSQL versions 15 and 16
    # https://github.com/plausible/analytics/blob/v2.1.1/.github/workflows/elixir.yml#L21-L32
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.1
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  event-logs:
    driver: local
```

for the nginx config file i did not change anything other than my server name from the example given [here](https://github.com/plausible/community-edition/blob/v2.1.1/reverse-proxy/nginx/plausible) 

and also uh i have also tried to `curl http:localhost:8000` and it gives me this output

```bash
curl: (56) Recv failure: Connection reset by peer
```

#### Here is how my plausible-conf.env looks like

BASE_URL=https://analytics.[my_domain_name]
SECRET_KEY_BASE=Jyh5i9wk7BZrf/wem9aTieRkVx306E/3d5nQGFLKsTvMZs1wOgiTb9uPs/E2H1qx
TOTP_VAULT_KEY=KeGYAJHPqz8GQKSwkNLlLJOBOrw1qBTIn8Fgu/O4eAE=
BUILD_METADATA={}

i don't know at this point what to do. Kindly please help.
