### DISCUSSION TITLE
Plausible not working with https

### DISCUSSION THREAD

**Discussion by hardik-codept** [plausible/analytics#4556] [Self-Hosted Support]
I've installed it on Ubuntu 20.04 via the docker installation with AWS. 

site is working fine with http, but with https it's not working fine. 

docker-compose.yml

```
services:
  plausible_db:
    # Plausible v2.1.1 was tested against PostgreSQL versions 15 and 16
    # https://github.com/plausible/analytics/blob/v2.1.1/.github/workflows/elixir.yml#L21-L32
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432" # http interface

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ports:
      - "8123:8123" # http interface
      - "9000:9000" # native interface
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.1
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - "8000:8000"
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  event-logs:
    driver: local
```
plausible-conf.env

```
BASE_URL=https://demo4commerce.com:8000
SECRET_KEY_BASE=#######
TOTP_VAULT_KEY=########
admin_user_email=****.****@gmail.com
ADMIN_USER_NAME=******
ADMIN_USER_PWD=********
```

All ports are enable in inbound rules - https://prnt.sc/iICaHhDHpOzE

Can you please assist me how I can fix https problem?

**Comment by ruslandoga** [comment]
👋 @hardik-codept 

You seem to have skipped Caddy setup: https://github.com/plausible/community-edition#caddy

**Reply by ruslandoga** [reply]
Also these env vars are no longer supported. You might have followed an outdated setup guide.

```env
admin_user_email=****.****@gmail.com
ADMIN_USER_NAME=******
ADMIN_USER_PWD=********
```

**Reply by hardik-codept** [reply]
Thanks for your quick  response. 

I have follow the same stuff, still I face same issue. 

reverse-proxy/nginx/plausible 
```
server {
        # replace example.com with your domain name
        server_name demo4commerce.com;

        listen 80;
        listen [::]:80;

        location / {
                proxy_pass http://127.0.0.1:8000;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                location = /live/websocket {
                        proxy_pass http://127.0.0.1:8000;
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";
                }
        }
}
```

reverse-proxy/docker-compose.caddy-gen.yml 
```
version: "3.3"
services:
  caddy-gen:
    container_name: caddy-gen
    image: "wemakeservices/caddy-gen:latest"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy-certificates:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - plausible

  plausible:
    labels:
      virtual.host: "demo4commerce.com" # change to your domain name
      virtual.port: "8000"
      virtual.tls-email: "*******@gmail.com" # change to your email
  volumes:
    caddy-certificates:
        driver: local
```

Do you have any idea what I missed? 

Thanks in advance.
