### DISCUSSION TITLE
v2.1.2

### DISCUSSION THREAD

**Discussion by ruslandoga** [plausible/analytics#4618] [Self-Hosted Support]
> [!WARNING]
> This release had [problems](https://github.com/plausible/analytics/discussions/4618#discussioncomment-10751271) with login, v2.1.3 has been published with a [fix:](https://github.com/plausible/analytics/pull/4621) https://github.com/plausible/analytics/discussions/4629

The highlights of this release are:

- Automatic IPv6 support for all outgoing connections
- Opt-in HTTPS support and Let's Encrypt integration
- Simplified Docker Compose [configuration](https://github.com/plausible/community-edition/tree/v2.1.2) (no reverse proxy required)
- Various product improvements: https://plausible.io/changelog — up until today's date :)

#### Upgrade

Update the image used for `plausible`

<sub><kbd>docker-compose.yml</kbd></sub>
```diff
plausible:
- image: ghcr.io/plausible/community-edition:v2.1.1
+ image: ghcr.io/plausible/community-edition:v2.1.2
```

and restart the containers

<sub><kbd>console</kbd></sub>
```console
$ cd hosting
$ docker compose up -d
```

This will boot up the new version of the app.

## Changelog

Following [changes](https://github.com/plausible/analytics/compare/v2.1.1...v2.1.2) have been made since v2.1.1:

### Added
- UI to edit goals along with display names
- Support contains filter for goals
- UI to edit funnels
- Add Details views for browsers, browser versions, os-s, os versions, and screen sizes reports
- Add a search functionality in all Details views
- Icons for browsers plausible/analytics#4239
- Automatic custom property selection in the dashboard Properties report
- Add `contains_not` filter support to dashboard
- Traffic drop notifications plausible/analytics#4300
- Add search and pagination functionality into Google Keywords > Details modal
- ClickHouse system.query_log table log_comment column now contains information about source of queries. Useful for debugging
- New /debug/clickhouse route for super admins which shows information on clickhouse queries executed by user
- Typescript support for `/assets`
- Testing framework for `/assets`
- Automatic HTTPS plausible/analytics#4491
- Make details views on dashboard sortable

### Removed
- Deprecate `ECTO_IPV6` and `ECTO_CH_IPV6` env vars in CE plausible/analytics#4245
- Remove support for importing data from no longer available Universal Analytics
- Soft-deprecate `DATABASE_SOCKET_DIR` plausible/analytics#4202

### Changed
- Support Unix sockets in `DATABASE_URL` plausible/analytics#4202
- Realtime and hourly graphs now show visits lasting their whole duration instead when specific events occur
- Increase hourly request limit for API keys in CE from 600 to 1000000 (practically removing the limit) plausible/analytics#4200
- Make TCP connections try IPv6 first with IPv4 fallback in CE plausible/analytics#4245
- `is` and `is not` filters in dashboard no longer support wildcards. Use contains/does not contain filter instead.
- `bounce_rate` metric now returns 0 instead of null for event:page breakdown when page has never been entry page.
- Make `TOTP_VAULT_KEY` optional plausible/analytics#4317
- Sources like 'google' and 'facebook' are now stored in capitalized forms ('Google', 'Facebook') plausible/analytics#4417
- `DATABASE_CACERTFILE` now forces TLS for PostgreSQL connections, so you don't need to add `?ssl=true` in `DATABASE_URL`
- Change auth session cookies to token-based ones with server-side expiration management.
- Improve Google error messages in CE plausible/analytics#4485
- Better compress static assets in CE plausible/analytics#4476
- Return domain-less cookies in CE plausible/analytics#4482
- Internal stats API routes now return a JSON error over HTML in case of invalid access.

### Fixed

- Fix access to Stats API feature in CE plausible/analytics#4244
- Fix filter suggestions when same filter previously applied
- Fix MX lookup when using relays with Bamboo.Mua plausible/analytics#4350
- Don't include imports when showing time series hourly interval. Previously imported data was shown each midnight
- Fix property filter suggestions 500 error when property hasn't been selected
- Bamboo.Mua: add Date and Message-ID headers if missing plausible/analytics#4474
- Fix migration order across `plausible_db` and `plausible_events_db` databases plausible/analytics#4466

<hr /><em>This discussion was created from the release <a href='https://github.com/plausible/analytics/releases/tag/v2.1.2'>v2.1.2</a>.</em>

**Comment by Olakeen** [comment]
Hello, thank you for this update.

My admin account is no longer working. How do I define the account now ? I don't see Admin_User_Pwd in the wiki ? https://github.com/plausible/community-edition/wiki

**Reply by ruslandoga** [reply]
`ADMIN_*` environment variables have been no-op since v1.5.1 release: https://github.com/plausible/analytics/discussions/2507

**Reply by Olakeen** [reply]
I have deleted these variables, temporary enable registration, created a new account and I have the same issue.
No "Wrong email or password. Please try again." message, just stuck on the login page.

**Reply by ruslandoga** [reply]
Do you have a reverse proxy in front of Plausible? If so, you would need to make sure you have WebSockets-proxying enabled there: https://github.com/plausible/community-edition/wiki/Reverse-Proxy

You can also search for past discussions about that issue:

- https://github.com/plausible/analytics/discussions/4274
- https://github.com/plausible/analytics/discussions/3826
- https://github.com/plausible/analytics/discussions/4291
- https://github.com/plausible/analytics/discussions/4310

**Reply by Olakeen** [reply]
WebSockets-proxying is correctly configured.

Tested on my phone and login was functionnal so I tried in private mode on my computer and it also worked.
I have deleted cookies and local storage and it now works properly. First time I've had this problem.

**Reply by lordcris** [reply]
> I have deleted cookies and local storage and it now works properly. First time I've had this problem.

Yes, I was using traefik and had the same problem. Deleting the cookies resolved it,

**Reply by Tony-MF** [reply]
I also had to delete cookies in order to get past the login screen.

**Reply by ruslandoga** [reply]
https://github.com/plausible/analytics/pull/4621 would probably fix the issue and get released as v2.1.3. Sorry for the inconvenience :)

@Olakeen thank you for providing a workaround!

**Comment by rootforbid** [comment]
Hi,

After upgrading from 2.1.1 as per the instruction, Plausible doesn't boot anymore, getting a bootloop of this error message:
```
ERROR! Config provider Config.Reader failed with:
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an already existing atom

    :erlang.binary_to_existing_atom("1", :utf8)
    /app/releases/0.0.1/runtime.exs:648: (file)
    (elixir 1.17.1) src/elixir.erl:386: :elixir.eval_external_handler/3
    (stdlib 6.0) erl_eval.erl:904: :erl_eval.do_apply/7
    (stdlib 6.0) erl_eval.erl:648: :erl_eval.expr/6
    (stdlib 6.0) erl_eval.erl:271: :erl_eval.exprs/6
    (elixir 1.17.1) src/elixir.erl:364: :elixir.eval_forms/4
    (elixir 1.17.1) lib/module/parallel_checker.ex:112: Module.ParallelChecker.verify/1

Runtime terminating during boot ({badarg,[{erlang,binary_to_existing_atom,[<<"1">>,utf8],[{error_info,#{module=>erl_erts_errors}}]},{elixir_eval,'__FILE__',1,[{file,"/app/releases/0.0.1/runtime.exs"},{line,648}]},{elixir,eval_external_handler,3,[{file,"src/elixir.erl"},{line,386}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,904}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,648}]},{erl_eval,exprs,6,[{file,"erl_eval.erl"},{line,271}]},{elixir,eval_forms,4,[{file,"src/elixir.erl"},{line,364}]},{'Elixir.Module.ParallelChecker',verify,1,[{file,"lib/module/parallel_checker.ex"},{line,112}]}]})

Crash dump is being written to: erl_crash.dump...
```

docker-compose.yml
```
services:
  plausible_db:
    image: postgres:15-alpine
    container_name: plausible_db
    env_file: ./.env
    user: "${PUID}:${PGID}"
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    container_name: plausible_db-events
    env_file: ./.env
    user: "${PUID}:${PGID}"
    volumes:
      - ./db-events/data:/var/lib/clickhouse
      - ./db-events/logs:/var/log/clickhouse-server
      - ./db-events/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./db-events/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always

  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.2
    container_name: plausible
    env_file: ./.env
    depends_on:
      - plausible_db
      - plausible_events_db
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    restart: always

networks:
    default:
      name: analytics_nw
      external: true
```

.env
```
BASE_URL=https://plausible.mysite.com
SECRET_KEY_BASE=******
TOTP_VAULT_KEY=******
DISABLE_REGISTRATION=invite_only
DATABASE_URL=postgres://root:******@plausible_db:5432/plausible
CLICKHOUSE_DATABASE_URL=http://plausible_db-events:8123/plausible_events_db
MAILER_ADAPTER=Bamboo.Mua
MAILER_EMAIL="no-reply@mysite.com"
SMTP_HOST_ADDR="******"
SMTP_HOST_PORT="587"
SMTP_USER_NAME="******"
SMTP_USER_PWD="******"
SMTP_HOST_SSL_ENABLED=1
MAXMIND_LICENSE_KEY=******
MAXMIND_EDITION=GeoLite2-City
GOOGLE_CLIENT_ID=******
GOOGLE_CLIENT_SECRET=******
PUID=1000
PGID=1000
```

Had to downgrade to 2.1.1 which didn't cause any issue.
