### DISCUSSION TITLE
v2.1.3

### DISCUSSION THREAD

**Discussion by ruslandoga** [plausible/analytics#4629] [Self-Hosted Support]
This release is the same as [v2.1.2](https://github.com/plausible/analytics/discussions/4618) but with cookie and filters issues resolved.

#### Upgrade

Update the image used for `plausible`

<sub><kbd>docker-compose.yml</kbd></sub>
```diff
plausible:
- image: ghcr.io/plausible/community-edition:v2.1.2
+ image: ghcr.io/plausible/community-edition:v2.1.3
```

and restart the containers

<sub><kbd>console</kbd></sub>
```console
$ cd hosting
$ docker compose up -d
```

This will boot up the new version of the app.

## Changelog

Following [changes](https://github.com/plausible/analytics/compare/v2.1.2...v2.1.3) have been made since v2.1.2:

### Fixed

- Change cookie key to resolve login issue https://github.com/plausible/analytics/pull/4621
- Set secure attribute on cookies when BASE_URL has HTTPS scheme https://github.com/plausible/analytics/pull/4623
- Don't track custom events in CE (fixes filters) https://github.com/plausible/analytics/pull/4627

<hr /><em>This discussion was created from the release <a href='https://github.com/plausible/analytics/releases/tag/v2.1.3'>v2.1.3</a>.</em>

**Comment by lordcris** [comment]
Just a heads up.
I am running docker as a non-root user and I had to add to "CAP_SYS_NICE" the clickhouse server to not get continuously "**get_mempolicy: Operation not permitted**" errors

```
plausible_events_db:
    image: clickhouse/clickhouse-server:24-alpine
      #image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8123/ping || exit 1"]
      start_interval: 2s
      start_period: 1m
    cap_add:
      - CAP_SYS_NICE
````
