### DISCUSSION TITLE
No page view is being tracked, despite the request being successful

### DISCUSSION THREAD

**Discussion by SebastianGode** [plausible/analytics#4655] [Self-Hosted Support]
I'm right now stuck on this view:
![grafik](https://github.com/user-attachments/assets/6d88056b-20b9-4571-b8b5-044c0d439e6c)

However the setup of my website should work fine as the even request passes according to the browser console and it provides an "ok" as response.
![grafik](https://github.com/user-attachments/assets/af00bfc1-cacf-4f57-b716-1ee33d392ddf)

The `docker compose logs` shows the following:
```
plausible_events_db-1  | ClickHouse Database directory appears to contain a database; Skipping initialization
plausible_events_db-1  | Processing configuration file '/etc/clickhouse-server/config.xml'.
plausible_events_db-1  | Merging configuration file '/etc/clickhouse-server/config.d/disable_cgroups.xml'.
plausible_events_db-1  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
plausible_events_db-1  | Merging configuration file '/etc/clickhouse-server/config.d/ipv4-only.xml'.
plausible_events_db-1  | Merging configuration file '/etc/clickhouse-server/config.d/logs.xml'.
plausible_events_db-1  | Logging warning to /var/log/clickhouse-server/clickhouse-server.log
plausible_events_db-1  | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
plausible-1            | Loading plausible..
plausible-1            | Starting dependencies..
plausible-1            | Starting repos..
plausible-1            | Plausible.Repo database already exists
plausible-1            | Plausible.IngestRepo database already exists
plausible-1            | Creation of Db successful!
plausible-1            | Loading plausible..
plausible-1            | Starting dependencies..
plausible-1            | Starting repos..
plausible_events_db-1  | 2024.10.07 13:01:33.389325 [ 1 ] {} <Warning> Context: Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. You can enable it using `echo 1 > /proc/sys/kernel/task_delayacct` or by using sysctl.
plausible_events_db-1  | 2024.10.07 13:01:33.539082 [ 1 ] {} <Error> Application: Disabling cgroup memory observer because of an error during initialization: Code: 107. DB::Exception: Cannot find cgroups v1 or v2 current memory file. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):
plausible_events_db-1  |
plausible_events_db-1  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
plausible_events_db-1  | 1. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x00000000076614c3
plausible_events_db-1  | 2. DB::CgroupsMemoryUsageObserver::CgroupsMemoryUsageObserver(std::chrono::duration<long long, std::ratio<1l, 1l>>) @ 0x000000000cce452e
plausible_events_db-1  | 3. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000cd562bd
plausible_events_db-1  | 4. Poco::Util::Application::run() @ 0x0000000014ca8606
plausible_events_db-1  | 5. DB::Server::run() @ 0x000000000cd46671
plausible_events_db-1  | 6. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000014cb14b9
plausible_events_db-1  | 7. mainEntryClickHouseServer(int, char**) @ 0x000000000cd4246a
plausible_events_db-1  | 8. main @ 0x0000000007651578
plausible_events_db-1  | 9. ? @ 0x0000773c8edb6083
plausible_events_db-1  | 10. _start @ 0x0000000005dee46e
plausible_events_db-1  |  (version 24.3.3.102 (official build))
```
So there's some issue with the Events DB, but I don't know how to fix it.
I'm using an external PostgresDB for accounting, but the standard Events-DB.
```
  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - event-data2:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m
```

What am I doing wrong?
