### DISCUSSION TITLE
Unable to start plausible using postgres user without permission to create db

### DISCUSSION THREAD

**Discussion by JuniorJPDJ** [plausible/analytics#481] [Self-Hosted Support] [answered]
I'm trying to run plausible self-hosted, but it fails to start without postgres permissions to create DB.

plausible docker log
```
$ dclf plausible
Attaching to plausible_plausible_1
plausible_1   | Loading plausible..
plausible_1   | Starting dependencies..
plausible_1   | Starting repos..
plausible_1   | create Plausible.Repo database if it doesn't exist
plausible_1   | ** (MatchError) no match of right hand side value: {:error, "ERROR 42501 (insufficient_privilege) permission denied to create database"}
plausible_1   |     (plausible 0.0.1) lib/plausible_release.ex:56: anonymous fn/2 in Plausible.Release.createdb/0
plausible_1   |     (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
plausible_1   |     (plausible 0.0.1) lib/plausible_release.ex:55: Plausible.Release.createdb/0
plausible_1   |     (stdlib 3.12.1) erl_eval.erl:680: :erl_eval.do_apply/6
plausible_1   |     (elixir 1.10.3) lib/code.ex:341: Code.eval_string_with_error_handling/3
plausible_plausible_1 exited with code 1
```

docker-compose fragment
```
  plausible:
    image: plausible/analytics:latest
    networks:
      - default
      - haproxy
      - postgres
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - clickhouse
      - mail
    environment:
      ADMIN_USER_EMAIL: "<censored>"
      ADMIN_USER_NAME: <censored>
      ADMIN_USER_PWD: "<censored>"
      BASE_URL: "https://<censored>" 
      SECRET_KEY_BASE: "<censored>"
      DATABASE_URL: "postgres://plausible:<censored>@postgres:5432/plausible"
      CLICKHOUSE_DATABASE_URL: "http://clickhouse:8123/plausible"
```

postgres log:
```
postgres_1  | 2020-12-16 12:16:06.274 UTC [56313] ERROR:  permission denied to create database
postgres_1  | 2020-12-16 12:16:06.274 UTC [56313] STATEMENT:  CREATE DATABASE "plausible" ENCODING 'UTF8'
postgres_1  | 2020-12-16 12:20:38.089 UTC [56431] ERROR:  permission denied to create database
postgres_1  | 2020-12-16 12:20:38.089 UTC [56431] STATEMENT:  CREATE DATABASE "plausible" ENCODING 'UTF8'
postgres_1  | 2020-12-16 12:21:32.475 UTC [56455] ERROR:  permission denied to create database
postgres_1  | 2020-12-16 12:21:32.475 UTC [56455] STATEMENT:  CREATE DATABASE "plausible" ENCODING 'UTF8'
```

postgres dbs
```
postgres=# \l
                                     List of databases
       Name       |      Owner       | Encoding | Collate | Ctype |    Access privileges
------------------+------------------+----------+---------+-------+-------------------------
[..]
 plausible        | plausible        | UTF8     | C       | C     | =Tc/plausible          +
                  |                  |          |         |       | plausible=CTc/plausible
 postgres         | postgres         | UTF8     | C       | C     |
[..]
 template0        | postgres         | UTF8     | C       | C     | =c/postgres            +
                  |                  |          |         |       | postgres=CTc/postgres
 template1        | postgres         | UTF8     | C       | C     | postgres=CTc/postgres  +
                  |                  |          |         |       | =c/postgres
(11 rows)
```
