### DISCUSSION TITLE
Installing Plausible CE on a Plesk Server

### DISCUSSION THREAD

**Discussion by actuallyba** [plausible/analytics#4876] [Self-Hosted Support]
Hi, I am trying to run Plausible CE on a Linux Ubuntu Server. I installed the Docker Extension and used Docker Stacks to create the containers for the plausible and postgres. In the Console log of the plausible container I get the following output: 

```
18:10:31.397 [notice] Application plausible exited: Plausible.Application.start(:normal, []) returned an error: shutdown: failed to start child: Plausible.Session.Salts
    ** (EXIT) an exception was raised:
        ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "salts" does not exist

    query: DELETE FROM "salts" AS s0 WHERE (s0."inserted_at" < now() - '48 hours'::interval)
            (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:1078: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:976: Ecto.Adapters.SQL.execute/6
            (plausible 0.0.1) lib/plausible/session/salts.ex:8: anonymous fn/0 in Plausible.Session.Salts.start_link/1
            (elixir 1.17.1) lib/agent/server.ex:8: Agent.Server.init/1
            (stdlib 6.0) gen_server.erl:2057: :gen_server.init_it/2
            (stdlib 6.0) gen_server.erl:2012: :gen_server.init_it/6
            (stdlib 6.0) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
{exit,terminating,[{application_controller,call,2,[{file,"application_controller.erl"},{line,511}]},{application,enqueue_or_start,6,[{file,"application.erl"},{line,380}]},{application,ensure_all_started,3,[{file,"application.erl"},{line,359}]},{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,195}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}
{exit,terminating,[{application_controller,call,2,[{file,"application_controller.erl"},{line,511}]},{application,enqueue_or18:12:25.341 [notice] Application plausible exited: Plausible.Application.start(:normal, []) returned an error: shutdown: failed to start child: Plausible.Session.Salts
    ** (EXIT) an exception was raised:
        ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "salts" does not exist

    query: DELETE FROM "salts" AS s0 WHERE (s0."inserted_at" < now() - '48 hours'::interval)
            (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:1078: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:976: Ecto.Adapters.SQL.execute/6
            (plausible 0.0.1) lib/plausible/session/salts.ex:8: anonymous fn/0 in Plausible.Session.Salts.start_link/1
            (elixir 1.17.1) lib/agent/server.ex:8: Agent.Server.init/1
            (stdlib 6.0) gen_server.erl:2057: :gen_server.init_it/2
            (stdlib 6.0) gen_server.erl:2012: :gen_server.init_it/6
            (stdlib 6.0) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
_start,6,[{file,"application.erl"},{line,380}]},{application,ensure_all_started,3,[{file,"application.erl"},{line,359}]},{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,195}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}
Runtime terminating during boot (terminating)

Crash dump is being written to: erl_crash.dump...Runtime terminating during boot (terminating)

Crash dump is being written to: erl_crash.dump...
```

Here is my configuration of the yml file:
```
services:
  db:
    image: postgres:14
    container_name: plausible-db
    volumes:
      - plausible-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: plausible_db
      POSTGRES_USER: plausible
      POSTGRES_PASSWORD: *plausible_pw*

  analytics:
    image: plausible/community-edition:latest
    container_name: plausible-analytics
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      ADMIN_USER_EMAIL: name@domain.com
      ADMIN_USER_PASSWORD: *admin_pw*
      BASE_URL: https://subdomain.domain.com
      SECRET_KEY_BASE: ***
      DATABASE_URL: postgresql://plausible:*plausible_pw*@db:5432/plausible_db
    volumes:
      - plausible-data:/var/lib/plausible

volumes:
  plausible-db-data:
  plausible-data:
```

And I added the following settings to the additional nginx directives in the subdomain settings:
```
location ~ ^/.* {
	proxy_pass http://0.0.0.0:8000;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header Connection 'upgrade';
	proxy_set_header Upgrade $http_upgrade;
	proxy_http_version 1.1;
}
```

Please help to solve the issue.

Best regards,
Björn
