### DISCUSSION TITLE
Invalid password

### DISCUSSION THREAD

**Discussion by zigazajc007** [plausible/analytics#523] [Self-Hosted Support]
When I use the provided docker-compose.yml file I get that error:

> Loading plausible..,
> Starting dependencies..,
> Starting repos..,
> create Plausible.Repo database if it doesn't exist,
> 18:01:01.140 [error] Postgrex.Protocol (#PID<0.238.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres",
> 18:01:01.140 [error] Postgrex.Protocol (#PID<0.237.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres",
> 18:01:01.161 [error] GenServer #PID<0.256.0> terminating,
> ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres",
>     (db_connection 2.2.2) lib/db_connection/connection.ex:87: DBConnection.Connection.connect/2,
>     (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5,
>     (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3,
> Last message: nil,
> ** (MatchError) no match of right hand side value: {:error, "killed"},
>     (plausible 0.0.1) lib/plausible_release.ex:56: anonymous fn/2 in Plausible.Release.createdb/0,
>     (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3,
>     (plausible 0.0.1) lib/plausible_release.ex:55: Plausible.Release.createdb/0,
>     (stdlib 3.12.1) erl_eval.erl:680: :erl_eval.do_apply/6,
>     (elixir 1.10.3) lib/code.ex:341: Code.eval_string_with_error_handling/3,

It seems that plausible don't know what is the password for database.

**Comment by zigazajc007** [comment]
Here is my docker-compose.yml file:

```yaml
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: yandex/clickhouse-server:latest
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 10000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
```

and here my plausible-conf.env

```
ADMIN_USER_EMAIL=ziga.zajc007@gmail.com
ADMIN_USER_NAME=ziga.zajc007
ADMIN_USER_PWD=example123
BASE_URL=http://localhost:8000
SECRET_KEY_BASE=CPmMHJm+XzxQkK+zAE/nsTpIpGpEUkbskpetF/gKsvRrurLJuYspIjCv6W4l0s1q
```
