### DISCUSSION TITLE
v3.0.1

### DISCUSSION THREAD

**Discussion by timbowhite** [plausible/analytics#5323] [Self-Hosted Support] [answered]
My self-hosted plausible instance no longer works after upgrading to v3.0.1. I get a 502 Bad Gateway from the nginx reverse proxy. Seems like an issue with Clickhouse user auth.

How I upgraded:
1. Updated docker-compose.yml
2. ```docker-compose --project-directory $PLAUSIBLE_DIR down --remove-orphans```
3. ```docker-compose --project-directory $PLAUSIBLE_DIR pull plausible```
4. ```docker-compose --project-directory $PLAUSIBLE_DIR up -d```

```docker-compose logs```
```
plausible-1  | Loading plausible..
plausible-1  | Starting dependencies..
plausible-1  | Starting repos..
plausible-1  | 14:54:49.578 [error] Ch.Connection (#PID<0.156.0>) failed to connect: ** (Ch.Error) Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.
plausible-1  | 
plausible-1  | If you have installed ClickHouse and forgot password you can reset it in the configuration file.
plausible-1  | The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
plausible-1  | and deleting this file will reset the password.
plausible-1  | See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.
plausible-1  | 
plausible-1  | . (AUTHENTICATION_FAILED) (version 24.12.6.70 (official build))
plausible-1  | 
plausible-1  | 14:54:49.578 [error] Ch.Connection (#PID<0.155.0>) failed to connect: ** (Ch.Error) Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.
plausible-1  | 
plausible-1            | If you have installed ClickHouse and forgot password you can reset it in the configuration file.
plausible_events_db-1  | /entrypoint.sh: neither CLICKHOUSE_USER nor CLICKHOUSE_PASSWORD is set, disabling network access for user 'default'
plausible_events_db-1  | ClickHouse Database directory appears to contain a database; Skipping initialization
plausible_events_db-1  | Processing configuration file '/etc/clickhouse-server/config.xml'.
plausible_events_db-1  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
plausible_events_db-1  | Merging configuration file '/etc/clickhouse-server/config.d/logging.xml'.
plausible_events_db-1  | Logging warning to /var/log/clickhouse-server/clickhouse-server.log
plausible_events_db-1  | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
plausible_events_db-1  | 2025.04.12 14:54:46.637309 [ 1 ] {} <Warning> Application: Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.12.6.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db-1  | 2025.04.12 14:54:46.646346 [ 1 ] {} <Warning> Context: Linux transparent hugepages are set to "always". Check /sys/kernel/mm/transparent_hugepage/enabled
plausible_events_db-1  | 2025.04.12 14:54:46.646597 [ 1 ] {} <Warning> Context: Linux threads max count is too low. Check /proc/sys/kernel/threads-max
plausible_events_db-1  | 2025.04.12 14:54:46.646711 [ 1 ] {} <Warning> Context: Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. You can enable it using `echo 1 > /proc/sys/kernel/task_delayacct` or by using sysctl.
plausible_events_db-1  | 2025.04.12 14:54:46.720732 [ 1 ] {} <Warning> Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.12.6.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db-1  | 2025.04.12 14:54:46.720856 [ 1 ] {} <Warning> Application: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.12.6.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db-1  | 2025.04.12 14:54:46.720946 [ 1 ] {} <Warning> Application: Listen [::]:9004 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.12.6.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db-1  | 2025.04.12 14:54:46.721024 [ 1 ] {} <Warning> Application: Listen [::]:9005 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 24.12.6.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
plausible_events_db-1  | 2025.04.12 14:54:49.562022 [ 78 ] {} <Error> DynamicQueryHandler: Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.
plausible_events_db-1  | 
plausible_events_db-1  | If you have installed ClickHouse and forgot password you can reset it in the configuration file.
plausible_events_db-1  | The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
plausible_events_db-1  | and deleting this file will reset the password.
plausible_events_db-1  | See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.
plausible_events_db-1  | 
plausible_events_db-1  | . (AUTHENTICATION_FAILED), Stack trace (when copying this message, always include the lines below):
plausible_events_db-1  | 
plausible_events_db-1  | 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d759c7b
plausible_events_db-1  | 1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000086447cc
...
```

```docker-compose.yml```:
```
services:
  plausible_db:
    # Plausible v2.1.1 was tested against PostgreSQL versions 15 and 16
    # https://github.com/plausible/analytics/blob/v2.1.1/.github/workflows/elixir.yml#L21-L32
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - CLICKHOUSE_SKIP_USER_SETUP=1
    healthcheck:
      test: pg_isready
      start_interval: 2s
      start_period: 1m

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.12-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8123/ping || exit 1
      start_interval: 2s
      start_period: 1m
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: ghcr.io/plausible/community-edition:v3.0.1
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8000 || exit 1
      start_interval: 2s
      start_period: 1m
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  event-logs:
    driver: local
```
```plausible-conf.env```:
```
ADMIN_USER_EMAIL=xxx@xxx.com
ADMIN_USER_NAME=XXXXXXXXXXXXXXXXXXXXXXXXX
ADMIN_USER_PWD=XXXXXXXXXXXXXXXXXXXXXXXXXX
BASE_URL=https://xxxxxxxx.com
# LISTEN_IP=127.0.0.1
LISTEN_IP=0.0.0.0
PORT=8000
SECRET_KEY_BASE=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
TOTP_VAULT_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
MAILER_NAME=plausible
MAILER_EMAIL=xxx@xxx.com
MAILER_ADAPTER=Bamboo.Mua
SMTP_HOST_ADDR=smtp.xxxxxxxxx.com
SMTP_HOST_PORT=587
SMTP_USER_NAME=xxx@xxx.com
SMTP_USER_PWD=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
GOOGLE_CLIENT_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
GOOGLE_CLIENT_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DISABLE_REGISTRATION=invite_only
MAXMIND_EDITION=GeoLite2-Country
MAXMIND_LICENSE_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
