### DISCUSSION TITLE
Server load issues after migrating to v3.0.1

### DISCUSSION THREAD

**Discussion by Tony-MF** [plausible/analytics#5340] [Self-Hosted Support]
Hi,

I'm having load issues after the latest upgrade. It seems after the server reaches some treshold, the CPU utilization increases disproportionally. 
![image](https://github.com/user-attachments/assets/31bb1c47-ba07-4596-a1e1-d58c400e397c)

My nginx log is full of:
```
2025/04/16 09:59:13 [error] 1426#1426: *471806619 connect() failed (111: Connection refused) while connecting to upstream, client: 172.68.147.151, server: stats2.indianfunempire.com, request: "POST /api/event HTTP/2.0", upstream: "http://127.0.0.1:8000/api/event", host: "stats2.indianfunempire.com", referrer: "https://www.mydesifun.com/"
2025/04/16 09:59:13 [error] 1426#1426: *471806619 connect() failed (111: Connection refused) while connecting to upstream, client: 172.68.147.151, server: stats2.indianfunempire.com, request: "POST /api/event HTTP/2.0", upstream: "http://127.0.0.1:8000/api/event", host: "stats2.indianfunempire.com", referrer: "https://www.desifun2.com/"
2025/04/16 09:59:13 [error] 1483#1483: *471500450 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.108.139, server: stats2.indianfunempire.com, request: "POS^C
```

Top:
<img width="568" alt="image" src="https://github.com/user-attachments/assets/a7cd8923-da9e-482e-961d-d6a634b549e4" />

The only difference I see is the user for beam.smp. Previously it was **systemd+**.

My docker-compose.xml:
```
services:
  plausible_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.12-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
        start_period: 1m

  plausible:
    image: ghcr.io/plausible/community-edition:v3.0.1
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
#    command: sh -c "tail -f /dev/null"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
```

Inside the plausible container, the top looks like this:
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/75ef3f44-828d-4007-94a2-4628189d971f" />

In the past, I had similar problems but it was because of nginx config, which has not changed:

 ```
       location / {
                proxy_pass http://127.0.0.1:8000;
                proxy_set_header X-Forwarded-Ssl on;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                location = /live/websocket {
                        proxy_pass         http://127.0.0.1:8000;
                        proxy_http_version 1.1;
                        proxy_set_header   Upgrade    $http_upgrade;
                        proxy_set_header   Connection "upgrade";
                }
        }
```
Is anyone else having similar issues?
