### DISCUSSION TITLE
Can't get it running

### DISCUSSION THREAD

**Discussion by youradds** [plausible/analytics#5342] [Self-Hosted Support]
Hi all,

I'm moving server, and rather than trying to transfer the old install, I went for a fresh install. Annoyingly, though, its being a real PITA!

So here is where I'm at:

```
docker compose up -d --remove-orphans
[+] Running 4/4
 ✔ Network plausible-ce_default                  Created                                                                                                                                                                                0.1s
 ✔ Container plausible-ce-plausible_events_db-1  Healthy                                                                                                                                                                                5.8s
 ✔ Container plausible-ce-plausible_db-1         Healthy                                                                                                                                                                                5.8s
 ✔ Container plausible-ce-plausible-1            Started                 


 docker ps
CONTAINER ID   IMAGE                                        COMMAND                  CREATED          STATUS                    PORTS                                         NAMES
5caae04f6104   ghcr.io/plausible/community-edition:v3.0.1   "/entrypoint.sh sh -…"   13 seconds ago   Up 7 seconds              0.0.0.0:8000->8000/tcp, [::]:8000->8000/tcp   plausible-ce-plausible-1
32abee373f30   clickhouse/clickhouse-server:24.12-alpine    "/entrypoint.sh"         13 seconds ago   Up 13 seconds (healthy)   8123/tcp, 9000/tcp, 9009/tcp                  plausible-ce-plausible_events_db-1
e7e3c399b240   postgres:16-alpine                           "docker-entrypoint.s…"   13 seconds ago   Up 13 seconds (healthy)   5432/tcp                                      plausible-ce-plausible_db-1
```

docker-compise.yml:

```
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:23.3.7.5-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v2.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local

```

In my domains nginx config, I have:

```
    location / {
      proxy_pass http://localhost:8000;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

```
 iptables --list -n | grep 8000
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8000
ACCEPT     tcp  --  0.0.0.0/0            172.18.0.4           tcp dpt:8000

sudo lsof -i :8000
COMMAND      PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
docker-pr 128706 root    7u  IPv4 344524      0t0  TCP *:8000 (LISTEN)
docker-pr 128712 root    7u  IPv6 344525      0t0  TCP *:8000 (LISTEN)
```

As far as I can see , thats all right. I'm not sure what else to try? 

Thanks!

Andy

**Comment by Tony-MF** [comment]
From what I see, you have the latest containers (v3.0.1), but your docker-compose.xml is from v2.0.

See the the latest [docker-compose.xml](https://github.com/plausible/community-edition/blob/v3.0.1/compose.yml)

**Reply by youradds** [reply]
LOL - sometimes it just takes someone with a fresh pair of eyes to look at it! OMG how stupid! All working now

**Reply by youradds** [reply]
> From what I see, you have the latest containers (v3.0.1), but your docker-compose.xml is from v2.0.
> 
> See the the latest [docker-compose.xml](https://github.com/plausible/community-edition/blob/v3.0.1/compose.yml)

I just had to say it haha . It doesn't seem to want to boot:

```
services:
  plausible_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.12-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
      # This makes ClickHouse consume less resources, which is useful for small setups.
      # https://clickhouse.com/docs/en/operations/tips#using-less-than-16gb-of-ram
      - ./clickhouse/low-resources.xml:/etc/clickhouse-server/config.d/low-resources.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m

  plausible:
    image: ghcr.io/plausible/community-edition:v3.0.1
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      # required: https://github.com/plausible/community-edition/wiki/configuration#required
      - BASE_URL=https://stats.newbyhost.com
      **- SECRET_KEY_BASE=<code generated with  openssl rand -base64 32>**
      # optional: https://github.com/plausible/community-edition/wiki/configuration#optional
      # registration: https://github.com/plausible/community-edition/wiki/configuration#registration
      - TOTP_VAULT_KEY=5IdDBrXRDKCglmF1z72t+NpATBv+vn1m0ABX9eCAn2o=
      - DISABLE_REGISTRATION=true
      - ENABLE_EMAIL_VERIFICATION
      # web: https://github.com/plausible/community-edition/wiki/configuration#web
      - HTTP_PORT
      - HTTPS_PORT
      # databases: https://github.com/plausible/community-edition/wiki/configuration#database
      - DATABASE_URL
      - CLICKHOUSE_DATABASE_URL
      # Google: https://github.com/plausible/community-edition/wiki/configuration#google
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      # geolocation: https://github.com/plausible/community-edition/wiki/configuration#ip-geolocation
      - IP_GEOLOCATION_DB
      - GEONAMES_SOURCE_FILE
      - MAXMIND_LICENSE_KEY
      - MAXMIND_EDITION
      # email: https://github.com/plausible/community-edition/wiki/configuration#email
      - MAILER_ADAPTER
      - MAILER_EMAIL=andy.xxx@gmail.com
      - MAILER_NAME
      - SMTP_HOST_ADDR
      - SMTP_HOST_PORT
      - SMTP_USER_NAME
      - SMTP_USER_PWD
      - SMTP_HOST_SSL_ENABLED
      - POSTMARK_API_KEY
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
      - MAILGUN_BASE_URI
      - MANDRILL_API_KEY
      - SENDGRID_API_KEY

volumes:
  db-data:
  event-data:
  event-logs:
  plausible-data:
```

It boots up, kinda:

```
CONTAINER ID   IMAGE                                        COMMAND                  CREATED              STATUS                        PORTS                          NAMES
529ff28cca36   ghcr.io/plausible/community-edition:v3.0.1   "/entrypoint.sh sh -…"   12 seconds ago       Restarting (1) 1 second ago                                  plausible-ce-plausible-1
```


Then a few seconds later, it reboots over and over:

```
CONTAINER ID   IMAGE                                        COMMAND                  CREATED              STATUS                          PORTS                          NAMES
1d3da13fea8b   ghcr.io/plausible/community-edition:v3.0.1   "/entrypoint.sh sh -…"   About a minute ago   Restarting (1) 47 seconds ago                                  plausible-ce-plausible-1
```

Its definatly not running, as its not listening on port 8000:

```
root@map:/home/stats/web/stats.newbyhost.com/plausible/plausible-ce# iptables --list -n | grep 8000
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8000
root@map:/home/stats/web/stats.newbyhost.com/plausible/plausible-ce#  sudo lsof -i :8000
```

Here is what I see when I try and run `docker ps` after a few seconds each time:

```
root@map:# docker ps
CONTAINER ID   IMAGE                                        COMMAND                  CREATED         STATUS                   PORTS                                         NAMES
557d95eb6114   ghcr.io/plausible/community-edition:v3.0.1   "/entrypoint.sh sh -…"   8 seconds ago   Up Less than a second    0.0.0.0:8000->8000/tcp, [::]:8000->8000/tcp   plausible-ce-plausible-1
3a5b8ff80515   postgres:16-alpine                           "docker-entrypoint.s…"   8 seconds ago   Up 7 seconds (healthy)   5432/tcp                                      plausible-ce-plausible_db-1
009722e5db57   clickhouse/clickhouse-server:24.12-alpine    "/entrypoint.sh"         8 seconds ago   Up 7 seconds (healthy)   8123/tcp, 9000/tcp, 9009/tcp                  plausible-ce-plausible_events_db-1
root@map:# docker ps
CONTAINER ID   IMAGE                                        COMMAND                  CREATED          STATUS                                  PORTS                          NAMES
557d95eb6114   ghcr.io/plausible/community-edition:v3.0.1   "/entrypoint.sh sh -…"   21 seconds ago   Restarting (1) Less than a second ago                                  plausible-ce-plausible-1
3a5b8ff80515   postgres:16-alpine                           "docker-entrypoint.s…"   21 seconds ago   Up 21 seconds (healthy)                 5432/tcp                       plausible-ce-plausible_db-1
009722e5db57   clickhouse/clickhouse-server:24.12-alpine    "/entrypoint.sh"         21 seconds ago   Up 21 seconds (healthy)                 8123/tcp, 9000/tcp, 9009/tcp   plausible-ce-plausible_events_db-1
root@map:# docker ps
CONTAINER ID   IMAGE                                        COMMAND                  CREATED          STATUS                         PORTS                          NAMES
557d95eb6114   ghcr.io/plausible/community-edition:v3.0.1   "/entrypoint.sh sh -…"   23 seconds ago   Restarting (1) 3 seconds ago                                  plausible-ce-plausible-1
3a5b8ff80515   postgres:16-alpine                           "docker-entrypoint.s…"   23 seconds ago   Up 23 seconds (healthy)        5432/tcp                       plausible-ce-plausible_db-1
009722e5db57   clickhouse/clickhouse-server:24.12-alpine    "/entrypoint.sh"         23 seconds ago   Up 23 seconds (healthy)        8123/tcp, 9000/tcp, 9009/tcp   plausible-ce-plausible_events_db-1
root@map:# docker ps
CONTAINER ID   IMAGE                                        COMMAND                  CREATED          STATUS                         PORTS                          NAMES
557d95eb6114   ghcr.io/plausible/community-edition:v3.0.1   "/entrypoint.sh sh -…"   26 seconds ago   Restarting (1) 5 seconds ago                                  plausible-ce-plausible-1
3a5b8ff80515   postgres:16-alpine                           "docker-entrypoint.s…"   26 seconds ago   Up 25 seconds (healthy)        5432/tcp                       plausible-ce-plausible_db-1
009722e5db57   clickhouse/clickhouse-server:24.12-alpine    "/entrypoint.sh"         26 seconds ago   Up 25 seconds (healthy)        8123/tcp, 9000/tcp, 9009/tcp   plausible-ce-plausible_events_db-1
root@map:# docker ps
CONTAINER ID   IMAGE                                        COMMAND                  CREATED          STATUS                                  PORTS                          NAMES
557d95eb6114   ghcr.io/plausible/community-edition:v3.0.1   "/entrypoint.sh sh -…"   28 seconds ago   Restarting (1) Less than a second ago                                  plausible-ce-plausible-1
3a5b8ff80515   postgres:16-alpine                           "docker-entrypoint.s…"   28 seconds ago   Up 28 seconds (healthy)                 5432/tcp                       plausible-ce-plausible_db-1
009722e5db57   clickhouse/clickhouse-server:24.12-alpine    "/entrypoint.sh"         28 seconds ago   Up 28 seconds (healthy)                 8123/tcp, 9000/tcp, 9009/tcp   plausible-ce-plausible_events_db-1
root@map:# docker ps
CONTAINER ID   IMAGE                                        COMMAND                  CREATED          STATUS                         PORTS                          NAMES
557d95eb6114   ghcr.io/plausible/community-edition:v3.0.1   "/entrypoint.sh sh -…"   30 seconds ago   Restarting (1) 2 seconds ago                                  plausible-ce-plausible-1
3a5b8ff80515   postgres:16-alpine                           "docker-entrypoint.s…"   30 seconds ago   Up 30 seconds (healthy)        5432/tcp                       plausible-ce-plausible_db-1
009722e5db57   clickhouse/clickhouse-server:24.12-alpine    "/entrypoint.sh"         30 seconds ago   Up 30 seconds (healthy)        8123/tcp, 9000/tcp, 9009/tcp   plausible-ce-plausible_events_db-1

```

**Comment by youradds** [comment]
Ok I feel like I'm almost there! Part of the issue is that I was using a 32 length key for SECRET_KEY_BASE, but it was meant to be 48 (looks like I was reading the command for `SECRET_KEY_BASE` to generate it!). I now have this and it boots:

```
services:
  plausible_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.12-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
      # This makes ClickHouse consume less resources, which is useful for small setups.
      # https://clickhouse.com/docs/en/operations/tips#using-less-than-16gb-of-ram
      - ./clickhouse/low-resources.xml:/etc/clickhouse-server/config.d/low-resources.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m

  plausible:
    env_file:
      - plausible-conf.env
    image: ghcr.io/plausible/community-edition:v3.0.1
    ports:
      - "8000:8000"    
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - DISABLE_LETS_ENCRYPT=true
      - TMPDIR=/var/lib/plausible/tmp
      # required: https://github.com/plausible/community-edition/wiki/configuration#required
      - BASE_URL=https://stats.newbyhost.com
      - SECRET_KEY_BASE=my_key
      # optional: https://github.com/plausible/community-edition/wiki/configuration#optional
      # registration: https://github.com/plausible/community-edition/wiki/configuration#registration
      - TOTP_VAULT_KEY
      - DISABLE_REGISTRATION=false
      - ENABLE_EMAIL_VERIFICATION
      # web: https://github.com/plausible/community-edition/wiki/configuration#web
      - HTTP_PORT
      # databases: https://github.com/plausible/community-edition/wiki/configuration#database
      - DATABASE_URL
      - CLICKHOUSE_DATABASE_URL
      # Google: https://github.com/plausible/community-edition/wiki/configuration#google
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      # geolocation: https://github.com/plausible/community-edition/wiki/configuration#ip-geolocation
      - IP_GEOLOCATION_DB
      - GEONAMES_SOURCE_FILE
      - MAXMIND_LICENSE_KEY
      - MAXMIND_EDITION
      # email: https://github.com/plausible/community-edition/wiki/configuration#email
      - MAILER_ADAPTER
      - MAILER_EMAIL
      - MAILER_NAME
      - SMTP_HOST_ADDR
      - SMTP_HOST_PORT
      - SMTP_USER_NAME
      - SMTP_USER_PWD
      - SMTP_HOST_SSL_ENABLED
      - POSTMARK_API_KEY
      - MAILGUN_API_KEY
      - MAILGUN_DOMAIN
      - MAILGUN_BASE_URI
      - MANDRILL_API_KEY
      - SENDGRID_API_KEY

volumes:
  db-data:
  event-data:
  event-logs:
  plausible-data:
```


The issue though - is how do I create a user? I have:

`DISABLE_REGISTRATION=false`

Yet when I go to:

https://stats.mysite.com/register

The form shows - but when I submit the form, nothing happens?

Thanks!

Andy
