### DISCUSSION TITLE
Events dropped when using caddy + cloudflare

### DISCUSSION THREAD

**Discussion by lemuelroberto** [plausible/analytics#5376] [Self-Hosted Support]
Hello, Plausible community! 🥇 

### General description of the issue

I'm trying to get a self-hosted deployment to work behind Caddy and Cloudflare, but every `/api/event` gets dropped without further detail.

#### Caddy access logs

Caddy access log show us below that the actual client IP is being correctly forward. If I understood correctly, `PlausibleWeb.RemoteIP` looks for client ip  in `cf-connecting-ip` and `x-forwarded-for` headers, that Caddy is sending to plausible service.

```json
{"level":"info","ts":1746243796.673512,"logger":"http.log.access.log2","msg":"handled request","request":{"remote_ip":"172.71.6.45","remote_port":"60514","client_ip":"<actual_client_ip>","proto":"HTTP/2.0","method":"POST","host":"plausible.example.com","uri":"/api/event","headers":{"Content-Type":["text/plain"],"Cf-Ray":["939cc0d11fb5aec6-GRU"],"Sec-Fetch-Mode":["cors"],"X-Forwarded-For":["<actual_client_ip>"],"X-Forwarded-Proto":["https"],"Priority":["u=1, i"],"Cf-Visitor":["{\"scheme\":\"https\"}"],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Site":["same-site"],"Cf-Ipcountry":["BR"],"Pragma":["no-cache"],"Accept":["*/*"],"Accept-Language":["en-US,en;q=0.9"],"Referer":["https://example.com/"],"Cf-Connecting-Ip":["<actual_client_ip>"],"Sec-Fetch-Dest":["empty"],"Sec-Ch-Ua-Platform":["\"Linux\""],"Accept-Encoding":["gzip, br"],"Content-Length":["99"],"Cache-Control":["no-cache"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"],"Origin":["https://example.com"],"Cdn-Loop":["cloudflare; loops=1"],"Sec-Ch-Ua":["\"Chromium\";v=\"135\", \"Not-A.Brand\";v=\"8\""]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"plausible.example.com"}},"bytes_read":99,"user_id":"","duration":0.002218218,"size":2,"status":202,"resp_headers":{"Via":["1.1 Caddy"],"Content-Length":["2"],"Date":["Sat, 03 May 2025 03:43:16 GMT"],"X-Plausible-Dropped":["1"],"Access-Control-Allow-Credentials":["true"],"Access-Control-Expose-Headers":[""],"Alt-Svc":["h3=\":443\"; ma=2592000"],"Content-Type":["text/plain; charset=utf-8"],"Access-Control-Allow-Origin":["*"],"Cache-Control":["max-age=0, private, must-revalidate"],"Server":["Cowboy"],"X-Request-Id":["GDvneyflul4wibIAACBB"]}}
```

#### Drop reason investigation

Setting `LOG_LEVEL=debug` does not help much with event drop reason, as we do not log them.

I've discovered that `Plausible.Ingestion` sets `x-plausible-dropped` header after `Ingestion.Event` processing the event, which emit telemetry with the drop reason.

Going through telemetry configuration, I've configured the `opentelemetry_exporter` with `otel_sampler_ratio` to 1.0 but it seems that only database and Elixir traces are being exported, as I could not find event drop telemetry on Honeycomb.

#### Plausible service configuration

```yaml
services:
  plausible:
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    container_name: ${PREFIX}-plausible
    environment:
      - BASE_URL=${PLAUSIBLE_URL}
      - CLICKHOUSE_DATABASE_URL=${PLAUSIBLE_CLICKHOUSE_DATABASE_URL}
      - DATABASE_URL=${PLAUSIBLE_DATABASE_URL}
      - DISABLE_REGISTRATION=true
      - HONEYCOMB_API_KEY=${PLAUSIBLE_HONEYCOMB_API_KEY}
      - HONEYCOMB_DATASET=${PLAUSIBLE_HONEYCOMB_DATASET}
      - OTEL_SAMPLER_RATIO=1.0
      - HTTP_PORT=8000
      - SECRET_KEY_BASE=${PLAUSIBLE_SECRET_KEY_BASE}
      - TMPDIR=/var/lib/plausible/tmp
    image: ghcr.io/plausible/community-edition:v3.0.1
    ports:
      - 8000:8000
    restart: always
    ulimits:
      nofile:
        hard: 65535
        soft: 65535
    volumes:
      - plausible-data:/var/lib/plausible
```

#### Caddy plausible configuration

For the header forwarding section, I've tried `{remote}` for `header_up` instead of `{http.request.header.Cf-Connecting-Ip}` and `{http.request.header.X-Forwarded-For}`. 

```Caddy
{
	servers {
		trusted_proxies cloudflare
		client_ip_headers Cf-Connecting-Ip X-Forwarded-For X-Real-IP
	}
}
plausible.example.com {
	handle {
		reverse_proxy plausible:8000 {
			header_up Host {host}
			header_up X-Real-IP {http.request.header.Cf-Connecting-Ip}
			header_up X-Forwarded-For {http.request.header.X-Forwarded-For}
			header_up Cf-Connecting-Ip {http.request.header.Cf-Connecting-Ip}
		}
	}
	tls {
		dns cloudflare {
			zone_token {env.CF_ZONE_TOKEN}
			api_token {env.CF_API_TOKEN}
		}
		resolvers 1.1.1.1
	}
}
```

### Discussion

Is there any further debugging steps I'm missing from the docs, discussions and issues? Can I provide other logs or service configuration?

Thank you very much in advance for any tips this community can provide.
