### DISCUSSION TITLE
Error when update from 2.1.5 to 3.0.1

### DISCUSSION THREAD

**Discussion by trecca** [plausible/analytics#5420] [Self-Hosted Support]
Hi team,

I'm experiencing an issue with my self-hosted Plausible Analytics instance where the ClickHouse database fails to start, displaying a "Poco::Exception. Code: 1000, System exception: cannot start thread" error in the logs.

Expected Behavior
ClickHouse should start successfully, allowing Plausible Analytics to run without issues.

Current Behavior
ClickHouse fails to initialize, preventing Plausible from operating. The following error is observed in the logs:

```
0. Poco::ThreadImpl::startImpl(Poco::SharedPtr<Poco::Runnable, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Runnable>>) @ 0x0000000016619d34
1. Poco::Thread::start(Poco::Runnable&) @ 0x000000001661ac0e
2. BaseDaemon::initializeTerminationAndSignalProcessing() @ 0x000000000dabdd14
3. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000dabb38b
4. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000d9f615b
5. Poco::Util::Application::run() @ 0x000000001666fd5a
6. DB::Server::run() @ 0x000000000d9f5f10
7. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000016678be7
8. mainEntryClickHouseServer(int, char**) @ 0x000000000d9f2d93
9. main @ 0x0000000008640abc
10. ? @ 0x00007fa0a2336d90
11. ? @ 0x00007fa0a2336e40
12. _start @ 0x00000000065e102e
 (version 24.12.6.70 (official build))
/entrypoint.sh: explicitly skip changing user 'default'
ClickHouse Database directory appears to contain a database; Skipping initialization
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/logging.xml'.
Logging warning to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Poco::Exception. Code: 1000, e.code() = 0, System exception: cannot start thread, Stack trace (when copying this message, always include the lines below):
```

compose.yml
```
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    container_name: plausible-mail
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro #delete if necessary
    networks:
      - networkPortal

  plausible_db:
    image: postgres:14-alpine
    container_name: plausible_db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro #delete if necessary
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - networkPortal

  plausible_events_db:
    #image: clickhouse/clickhouse-server:24.3.3.102-alpine
    image: clickhouse/clickhouse-server:24.12-alpine
    container_name: plausible-events-db
    restart: unless-stopped
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
      - /etc/localtime:/etc/localtime:ro #delete if necessary
    ports:
      - 8123:8123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    networks:
      - networkPortal

  ANALYTICS.DOMAIN.COM:
    hostname: ANALYTICS.DOMAIN.COM
    #image: ghcr.io/plausible/community-edition:v2.1.5
    image: ghcr.io/plausible/community-edition:v3.0.1
    container_name: ANALYTICS.DOMAIN.COM
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    volumes:
      - /etc/localtime:/etc/localtime:ro #delete if necessary
    ports:
      - 8003:8000 #change before the `:` if you've already mapped another service to port 8000
    env_file:
      - /plausible/hosting/plausible-conf.env
    networks:
      - networkPortal

networks:
  networkPortal:
    name: external-portal_default
    external: true

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
```
