### DISCUSSION TITLE
the server responded with a status of 500

### DISCUSSION THREAD

**Discussion by gardnerinfotech** [plausible/analytics#638] [Self-Hosted Support]
I installed the Plausible Docker containers, and have a simple reverse proxy using Caddy v2 to expose the server to the web. This installation was very simple and straightforward, I've installed services like this many times.

At first, everything appears to run correctly; I was able to log in to the web service and add a domain. I added the tracking code to a new site, but the events never register on my Plausible instance. Looking at the browser console, it is returning error 500 when attempting to POST to /api/event. Below are the details reported by the browser, followed by my Caddyfile directive for the reverse proxy.

```
Request URL: https://plausible.infotech.link/api/event
Request Method: POST
Status Code: 500 
Remote Address: 3.17.3.215:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-credentials: true
access-control-allow-origin: *
access-control-expose-headers
cache-control: max-age=0, private, must-revalidate
content-length: 39
content-type: application/json; charset=utf-8
date: Fri, 22 Jan 2021 02:30:57 GMT
server: Caddy
server: Cowboy
x-request-id: FlxtCkKzRFxOT68AABxh
:authority: plausible.infotech.link
:method: POST
:path: /api/event
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 173
content-type: text/plain
origin: https://onelightdistributing.com
referer: https://onelightdistributing.com/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
sec-gpc: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
{n: "pageview", u: "https://onelightdistributing.com/", d: "onelightdistributing.com",…}
d: "onelightdistributing.com"
n: "pageview"
r: "https://onelightdistributing.com/wp-admin/post.php?post=22&action=edit"
u: "https://onelightdistributing.com/"
w: 1164
```

Here's my Caddyfile directive for the reverse proxy:

```
plausible.infotech.link {
        reverse_proxy 172.26.5.57:8000 {
                header_up X-Forwarded-For {http.request.remote}
                header_up X-Forwarded-Port {http.request.port}
                header_up X-Forwarded-Proto {http.request.scheme}
        }
}
```

Any ideas where the problem may reside?

**Comment by Vigasaurus** [comment]
You'll want to check your docker logs as those will actually have some meaningful data, if you were able to login and add your sites etc, it's likely not a caddy or web server issue, but rather likely some config mishap with one of the docker containers.  `docker-compose logs` should give you all you need, but you can tack on a `-f` to follow them and send your POST after. Feel free to post the relevant portions here

**Reply by gardnerinfotech** [reply]
I realized late last night that I forgot to do that. Here's the relevant results of the docker logs:

```
plausible_1            | 13:16:42.098 request_id=FlyQRy0ujuqHDIAAAAwR [warn] Failed to send Sentry event.Cannot send Sentry event because of invalid DSN
plausible_1            | 13:16:42.099 request_id=FlyQRy0ujuqHDIAAAAwR [warn] Failed to send Sentry event.Cannot send Sentry event because of invalid DSN
plausible_1            | 13:16:42.101 [error] #PID<0.4905.0> running PlausibleWeb.Endpoint (connection #PID<0.4897.0>, stream id 8) terminated
plausible_1            | Server: plausible.infotech.link:80 (http)
plausible_1            | Request: POST /api/event
plausible_1            | ** (exit) an exception was raised:
plausible_1            |     ** (BadMapError) expected a map, got: nil
plausible_1            |         (elixir 1.10.3) lib/map.ex:450: Map.get(nil, :country, nil)
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:130: PlausibleWeb.Api.ExternalController.visitor_country/1
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:80: PlausibleWeb.Api.ExternalController.create_event/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:9: PlausibleWeb.Api.ExternalController.event/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:1: PlausibleWeb.Api.ExternalController.action/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:1: PlausibleWeb.Api.ExternalController.phoenix_controller_pipeline/2
plausible_1            |         (phoenix 1.4.17) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
plausible_1            |         (plausible 0.0.1) lib/plug/error_handler.ex:65: PlausibleWeb.Router.call/2

```

**Reply by ukutaht** [reply]
@gardnerinfotech Looks like IP geolocation is failing. Have you configured the `GEOLITE2_COUNTRY_DB` option?

**Reply by gardnerinfotech** [reply]
I have tried running docker-compose with and without the geoip image with the same results. The GEOLITE2_COUNTRY_DB environment variable is set. With the geoip, I can see on MaxMind that my geoip key was used, and I can see the downloaded country database in the hosting_geoip docker volume, so the geoipupdate image seems to be working.

This is the docker-compose.yml file I'm running:

```
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: yandex/clickhouse-server:latest
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.>
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
      - geoip
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env
    volumes:
      - geoip:/geoip:ro

  geoip:
    image: maxmindinc/geoipupdate
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168 # update every 7 days
    env_file:
      geoip/geoip.conf
    volumes:
      - geoip:/usr/share/GeoIP

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
```
