### DISCUSSION TITLE
Mixed content error for self hosting

### DISCUSSION THREAD

**Discussion by HFulcher** [plausible/analytics#654] [Self-Hosted Support] [answered]
I have a self-hosted instance running on DigitalOcean behind Caddy at analytics.huwfulcher.com. Whenever I add a snippet to one of my hosted sites I get the following error

`Mixed Content: The page at 'https://huwfulcher.com/' was loaded over HTTPS, but requested an insecure script 'http://analytics.huwfulcher.com:8000/js/plausible.js'.`

The seemingly obvious solution would be to change to `https://` but this only gives an `SSL_ERROR_RX_RECORD_TOO_LONG` error. I'm not sure what's going on as I have set up the docker containers according to the self-hosting instructions.

Previously if I included `https://` in the `BASE_URL` and corresponding config for caddy-gen I could access over HTTPS but then I would get a `failed to load` error from Chrome/Firefox for `https://analytics.huwfulcher.com:8000/js/plausible.js`.

Any idea what I'm doing wrong?

**Comment by Vigasaurus** [comment]
What are you putting as your base URL? Can you also post your caddy config and your plausible-conf.env? Those should help shed some light on it.

**Comment by HFulcher** [comment, marked as answer]
Hi @Vigasaurus, find the env and caddy config below:

plausible-conf.env
```
ADMIN_USER_EMAIL=fulcherhuw@gmail.com
ADMIN_USER_NAME=hfulcher
ADMIN_USER_PWD=<removed>
BASE_URL=http://analytics.huwfulcher.com:8000
SECRET_KEY_BASE=<removed>
``` 

caddy config
```
version: "3.3"
services:
  caddy-gen:
    container_name: caddy-gen
    image: "wemakeservices/caddy-gen:latest"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy-certificates:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - plausible

  plausible:
    labels:
      virtual.host: "http://analytics.huwfulcher.com" # change to your domain name
      virtual.port: "8000"
      virtual.tls-email: "fulcherhuw@gmail.com" # change to your email
        
volumes:
    caddy-certificates:
        driver: local
```
