### DISCUSSION TITLE
Error when starting docker container

### DISCUSSION THREAD

**Discussion by jaydns** [plausible/analytics#741] [Self-Hosted Support] [answered]
Whenever I try to start the `plausible/analytics` docker container, I get this error, and it stops;

```
Loading plausible..
Starting dependencies..
Starting repos..
create Plausible.Repo database if it doesn't exist
** (MatchError) no match of right hand side value: {:error, "connection not available and request was dropped from queue after 2708ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. By tracking down slow queries and making sure they are running fast enough\n  2. Increasing the pool_size (albeit it increases resource consumption)\n  3. Allow requests to wait longer by increasing :queue_target and :queue_interval\n\nSee DBConnection.start_link/2 for more information\n"}
    (plausible 0.0.1) lib/plausible_release.ex:48: anonymous fn/2 in Plausible.Release.createdb/0
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plausible 0.0.1) lib/plausible_release.ex:47: Plausible.Release.createdb/0
    (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.3) lib/code.ex:341: Code.eval_string_with_error_handling/3
```

Any way to fix this?

**Comment by randomizeduser** [comment]
I am having the same issue. Not sure how to fix it.

Checking the events_db docker container shows also these errors:

```
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/logging.xml'.
Logging warning to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
gging warning to console

2021.06.27 11:30:12.481317 [ 44 ] {} <Warning> Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: Address family for hostname not supported (version 21.3.2.5 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2021.06.27 11:30:12.482336 [ 44 ] {} <Warning> Application: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: Address family for hostname not supported (version 21.3.2.5 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2021.06.27 11:30:12.482919 [ 44 ] {} <Warning> Application: Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: Address family for hostname not supported (version 21.3.2.5 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2021.06.27 11:30:12.483510 [ 44 ] {} <Warning> Application: Listen [::]:9004 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: Address family for hostname not supported (version 21.3.2.5 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
```

Not sure if it is related.

**Reply by jbraithwaite** [reply]
I'm getting the same error as OP, I'll report back when I have a solution (or maybe OP has found a fix…)

@randomizeduser My understand are those are only warning that click house isn't listening on IPv6. It's just a warning.

**Comment by jbraithwaite** [comment, marked as answer]
I'm having the same error.

`Docker version 20.10.3, build b455053`
`docker-compose version 1.28.5, build 324b023a`

From the docs:

> The server must have a CPU with x86_64 architecture and support for SSE 4.2 instructions.

I'm running this on a Synology NAS (1621+)

```
…
model name      : AMD Ryzen Embedded V1500B
…
flags           : sse4_1 sse4_2 sse4a …
…
```

I was able to get this working at some point, but now fails on `docker-compose up`.  I believe this cyptic error is caused by `plausible` not being able to connect to the postgres database.

To see if it's a configuration issue, I verified that running `docker-compose up`, in this same folder, on a Mac, works as expected.

**Reply by jbraithwaite** [reply]
Found a fix for me. I was unable to connect due to firewall rules on the host.

To test this out, in a new folder I create a new `docker-compose.yml` with two services. I tried pinging one container from another and found I couldn't when the firewall rule was in place. The fix was allowing traffic on 127.0.0.0/8.

**Reply by metmarkosaric** [reply]
nice, thanks for sharing your fix!

**Reply by JvdBossche** [reply]
> ... The fix was allowing traffic on 127.0.0.0/8.

_How_ exactly did you set up this allowing of traffic? Is it a setting in the docker network or in the firewall of the synology?
Thing is, the Synology firewall is active (in my case) but in the configured "default" setting, it had no rules (which was a bit of a surprise), so it lets everything through.
As far as I can see (using the default docker app from synology) the bridge network between the 4 containers is set up ok: It looks exactly like another bridge between 2 containers related to my homeassistant setup, but in another subnet (172.17.0.0/16 vs 172.18.0.0/16).

**Reply by jbraithwaite** [reply]
Here are some screenshots and settings I used.

<img width="1018" alt="Screen Shot 2021-11-13 at 9 31 32 AM" src="https://user-images.githubusercontent.com/1044105/141656733-8941c6d3-bb6c-493b-9ff6-c71c9abfe9dc.png">
<img width="1130" alt="Screen Shot 2021-11-13 at 9 35 07 AM" src="https://user-images.githubusercontent.com/1044105/141656821-0a907e07-4208-4e49-bc5f-09988712ba7d.png">


<details>
  <summary>My docker-compose.yml</summary>
  
```yml
version: "3.5"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    restart: always
    cpu_count: 2
    mem_limit: 4gb
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - TZ=Pacific/Honolulu

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    cpu_count: 4
    mem_limit: 4gb
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:stable
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env
    links:
      - "plausible_db:database"

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

```
</details>
