### DISCUSSION TITLE
My docker setup not working

### DISCUSSION THREAD

**Discussion by Bammede** [plausible/analytics#794] [Self-Hosted Support]
Can you review my settings for plausible selfhosting as it may be something wrong, please?
I have various errors with postgres database e.g. not found. I have no idea what's wrong with this setup

Here my docker compose

```
version: "2.4"

networks:
  web:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16

services:
  caddy:
<proxy settings>

  clickhousedb:
    image: yandex/clickhouse-server:latest
    restart: unless-stopped
    environment:
      - CLICKHOUSE_DB=plausible
      - CLICKHOUSE_USER=<somename>
      - CLICKHOUSE_PASSWORD=<password>
    volumes:
      - ./plausible/clickhouse:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      web:
        ipv4_address: 10.5.0.9

  postgresdb:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./plausible/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_USER=plausible
    networks:
      web:
        ipv4_address: 10.5.0.10

  geoip:
    image: maxmindinc/geoipupdate:latest
    restart: unless-stopped
    environment:
      # Change with your own key, you can sign-up at: https://www.maxmind.com/en/geoip2-services-and-databases
      - GEOIPUPDATE_ACCOUNT_ID=<id>
      # Change it with your own key
      - GEOIPUPDATE_LICENSE_KEY=<key>
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      # update every 7 days
      - GEOIPUPDATE_FREQUENCY=168
    volumes:
      - ./plausible/geoip:/usr/share/GeoIP
    networks:
      web:
        ipv4_address: 10.5.0.11

  plausible:
    image: plausible/analytics:latest
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh postgresdb createdb && /entrypoint.sh postgresdb migrate && /entrypoint.sh postgresdb init-admin && /entrypoint.sh run"
    depends_on:
      - postgresdb
      - clickhousedb
      - geoip
    environment:
      # Change this 64 char. key
      - SECRET_KEY_BASE=<key>
      # Change this 32 char. key too
      - SIGNING_SALT=<salt>
      - DATABASE_URL=plausible://username:password@postgresdb:5432/plausible
      - PORT=8777
      - DISABLE_REGISTRATION=true
      - DISABLE_SUBSCRIPTION=true
      - CLICKHOUSE_DATABASE_HOST=10.5.0.9
      - CLICKHOUSE_DATABASE_NAME=plausible
      - CLICKHOUSE_DATABASE_USER=<username>
      - CLICKHOUSE_DATABASE_PASSWORD=<password>
      - DATABASE_POOL_SIZE=20
      - CLICKHOUSE_DATABASE_POOLSIZE=20
      # Change to the domain you wan to have Plausible Available
      - HOST=example.com
      - SCHEME=https
      - MAILER_ADAPTER=Bamboo.SMTPAdapter
      # Change this to reflect the address where emails are going to come from
      - MAILER_EMAIL=no-reply@example.com
      # Change this to your server, you can use mailgun, or google smtp
      - SMTP_HOST_ADDR=mail.example.com
      - SMTP_HOST_PORT=587 # Change to fit your server
      # This can be, user@gmail.com if you are using Google SMTP
      - SMTP_USER_NAME=<username>
      # Change with your SMTP password
      - SMTP_USER_PWD=<password>
      - SMTP_HOST_SSL_ENABLED=true
      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
      - GOOGLE_CLIENT_ID=<clientID>
      - GOOGLE_CLIENT_SECRET=<secret>
    volumes:
      - ./plausible/geoip:/geoip:ro
    networks:
      web:
        ipv4_address: 10.5.0.8

volumes:
  geoip:
    driver: local
```
