### DISCUSSION TITLE
Clickhouse query error

### DISCUSSION THREAD

**Discussion by VictorElHajj** [plausible/analytics#912] [Self-Hosted Support] [answered]
Hi! I've been struggling to get this running for a few hours now and finally reached something I've not been able to figure out. I get all the way to just after "Admin user created successful!" then clickhouse does this:
```
`plausible_events_db_1  | 2021.04.06 15:35:24.662756 [ 54 ] {3f871460-c2be-47f9-bc1e-e0dbe73638ea} <Error> executeQuery: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 658 ('timestamp') (line 1, col 658): timestamp ORDER BY s0."timestamp"
plausible_events_db_1  |  FORMAT JSONCompact. Expected one of: UNION, LIMIT, WHERE, WINDOW, INNER, LIKE, GLOBAL NOT IN, end of query, HAVING, AS, DIV, IS, GROUP BY, INTO OUTFILE, OR, QuestionMark, BETWEEN, OFFSET, NOT LIKE, MOD, LEFT ARRAY JOIN, PREWHERE, AND, JOIN, Comma, alias, ORDER BY, array join, SETTINGS, IN, ARRAY JOIN, ILIKE, FORMAT, Dot, NOT ILIKE, WITH, NOT, Arrow, table, table function, subquery or list of joined tables, token, NOT IN, GLOBAL IN (version 21.3.2.5 (official build)) (from 172.20.0.4:37103) (in query: SELECT s0."hostname", s0."domain", s0."user_id", s0."session_id", s0."start", s0."duration", s0."is_bounce", s0."entry_page", s0."exit_page", s0."pageviews", s0."events", s0."sign", s0."utm_medium", s0."utm_source", s0."utm_campaign", s0."referrer", s0."referrer_source", s0."country_code", s0."screen_size", s0."operating_system", s0."operating_system_version", s0."browser", s0."browser_version", s0."timestamp" FROM "sessions" AS s0 INNER JOIN (SELECT s0."session_id" AS "session_id", max(s0."timestamp") AS "timestamp" FROM "sessions" AS s0 WHERE (s0."timestamp" >= now() - INTERVAL 3600 SECOND) GROUP BY s0."session_id") AS s1 USING session_id, USING timestamp ORDER BY s0."timestamp" FORMAT JSONCompact), Stack trace (when copying this message, always include the lines below):
plausible_events_db_1  |
plausible_events_db_1  | 0. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x1184fcb6 in /usr/bin/clickhouse
plausible_events_db_1  | 1. ? @ 0xf12c0ae in /usr/bin/clickhouse
plausible_events_db_1  | 2. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xf130a78 in /usr/bin/clickhouse
plausible_events_db_1  | 3. DB::HTTPHandler::processQuery(DB::Context&, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0xf84675a in /usr/bin/clickhouse
plausible_events_db_1  | 4. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xf84a8ee in /usr/bin/clickhouse
plausible_events_db_1  | 5. DB::HTTPServerConnection::run() @ 0xf8d35ff in /usr/bin/clickhouse
plausible_events_db_1  | 6. Poco::Net::TCPServerConnection::start() @ 0x11f7ccbf in /usr/bin/clickhouse
plausible_events_db_1  | 7. Poco::Net::TCPServerDispatcher::run() @ 0x11f7e6d1 in /usr/bin/clickhouse
plausible_events_db_1  | 8. Poco::PooledThread::run() @ 0x120b4df9 in /usr/bin/clickhouse
plausible_events_db_1  | 9. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b0c5a in /usr/bin/clickhouse
plausible_events_db_1  | 10. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
plausible_events_db_1  | 11. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
plausible_events_db_1  |
plausible_events_db_1  | 2021.04.06 15:35:24.663069 [ 54 ] {3f871460-c2be-47f9-bc1e-e0dbe73638ea} <Error> DynamicQueryHandler: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 658 ('timestamp') (line 1, col 658): timestamp ORDER BY s0."timestamp"
plausible_events_db_1  |  FORMAT JSONCompact. Expected one of: UNION, LIMIT, WHERE, WINDOW, INNER, LIKE, GLOBAL NOT IN, end of query, HAVING, AS, DIV, IS, GROUP BY, INTO OUTFILE, OR, QuestionMark, BETWEEN, OFFSET, NOT LIKE, MOD, LEFT ARRAY JOIN, PREWHERE, AND, JOIN, Comma, alias, ORDER BY, array join, SETTINGS, IN, ARRAY JOIN, ILIKE, FORMAT, Dot, NOT ILIKE, WITH, NOT, Arrow, table, table function, subquery or list of joined tables, token, NOT IN, GLOBAL IN, Stack trace (when copying this message, always include the lines below):
plausible_events_db_1  |
plausible_events_db_1  | 0. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x1184fcb6 in /usr/bin/clickhouse
plausible_events_db_1  | 1. ? @ 0xf12c0ae in /usr/bin/clickhouse
plausible_events_db_1  | 2. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xf130a78 in /usr/bin/clickhouse
plausible_events_db_1  | 3. DB::HTTPHandler::processQuery(DB::Context&, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0xf84675a in /usr/bin/clickhouse
plausible_events_db_1  | 4. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0xf84a8ee in /usr/bin/clickhouse
plausible_events_db_1  | 5. DB::HTTPServerConnection::run() @ 0xf8d35ff in /usr/bin/clickhouse
plausible_events_db_1  | 6. Poco::Net::TCPServerConnection::start() @ 0x11f7ccbf in /usr/bin/clickhouse
plausible_events_db_1  | 7. Poco::Net::TCPServerDispatcher::run() @ 0x11f7e6d1 in /usr/bin/clickhouse
plausible_events_db_1  | 8. Poco::PooledThread::run() @ 0x120b4df9 in /usr/bin/clickhouse
plausible_events_db_1  | 9. Poco::ThreadImpl::runnableEntry(void*) @ 0x120b0c5a in /usr/bin/clickhouse
plausible_events_db_1  | 10. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
plausible_events_db_1  | 11. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
plausible_events_db_1  |  (version 21.3.2.5 (official build))
```

I looked at the two other discussion posts with similar issues (https://github.com/plausible/analytics/discussions/842 and https://github.com/plausible/analytics/discussions/816) but neither helped. 

My docker compose

```yml

version: "3.3"
services:

  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    hostname: plausible_db
    volumes:
      - plausible_db:/var/lib/postgresql/data
    env_file:
      - postgres.env
    networks:
      - plausible-net
    ports:
      - 5432

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    volumes:
      - plausible_event:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - plausible-net

  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - geoip
      - mail
    volumes:
      - geoip:/geoip:ro
    environment:
      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
    env_file:
      - plausible-conf.env
    networks:
      - plausible-net
      - web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.plausible.rule=Host(`stats.website.tld`)'
      - 'traefik.http.routers.plausible.entrypoints=websecure'
      - 'traefik.http.routers.plausible.tls=true'
      - 'traefik.http.routers.plausible.tls.certresolver=le'
      - 'traefik.http.services.plausible.loadbalances.server.port=8000'

  geoip:
    image: maxmindinc/geoipupdate
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168 # update every 7 days
    env_file:
     - geoip.env
    volumes:
      - ./geoip:/usr/share/GeoIP

volumes:
  geoip:
  plausible_db:
  plausible_event:

networks:
  plausible-net:
  web:
    external: true
```

Plausible conf env:
```env
ADMIN_USER_EMAIL=[email]
ADMIN_USER_NAME=[username]
ADMIN_USER_PWD=[password]
BASE_URL=http://stats.website.tld
SECRET_KEY_BASE="long secret key"
DISABLE_REGISTRATION=true
DATABASE_URL=postgres://plausible:test@plausible_db:5432/plausible
```

The two clickhouse config files are the same as in the /hosting repo, no idea what is wrong as the error messages are not very descriptive.

**Comment by ukutaht** [comment, marked as answer]
What's actually wrong, are you getting a 500 error? Is so, please run with `LOG_LEVEL=debug` and show the logs of the actual failing request.

These specific error messages from Clickhouse are most likely a red herring.

**Reply by VictorElHajj** [reply]
I set env DEBUG_LEVEL=debug for plausible and clickhouse and it's just more of the same.
```
plausible_1            | Admin user already exists. I won't override, bailing
plausible_1            | 10:36:39.626 [info] AppSignal disabled.
plausible_1            | 10:36:39.627 [debug] Appsignal.Error.Backend attached to Logger
plausible_1            | 10:36:39.628 [debug] Appsignal.Phoenix.EventHandler attached to [:phoenix, :endpoint, :start]
plausible_1            | 10:36:39.628 [debug] Appsignal.Phoenix.EventHandler attached to [:phoenix, :endpoint, :stop]
plausible_1            | 10:36:39.631 [info] Source for database :country not found: "/geoip/GeoLite2-Country.mmdb"
plausible_1            | 10:36:39.738 [info] Running PlausibleWeb.Endpoint with cowboy 2.8.0 at 0.0.0.0:8000 (http)
plausible_1            | 10:36:39.748 [info] Access PlausibleWeb.Endpoint at http://stats.bogdanov.red
plausible_events_db_1  | 2021.04.07 10:36:39.792436 [ 82 ] {76ac1656-73f2-4111-8910-88b8261597dd} <Error> executeQuery: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 658 (line 1, col 658): timestamp ORDER BY s0."timestamp"
plausible_events_db_1  |  FORMAT JSONCompact. Expected one of: LIMIT, WHERE, INNER, LIKE, GLOBAL NOT IN, AS, HAVING, IS, INTO OUTFILE, GROUP BY, OR, QuestionMark, BETWEEN, NOT LIKE, LEFT ARRAY JOIN, PREWHERE, AND, JOIN, Comma, alias, ORDER BY, array join, SETTINGS, UNION ALL, IN, ARRAY JOIN, FORMAT, Dot, WITH, NOT, Arrow, token, NOT IN, GLOBAL IN, table, table function, subquery or list of joined tables (version 20.3.8.53 (official build)) (from 172.28.0.4:39481) (in query: SELECT s0."hostname", s0."domain", s0."user_id", s0."session_id", s0."start", s0."duration", s0."is_bounce", s0."entry_page", s0."exit_page", s0."pageviews", s0."events", s0."sign", s0."utm_medium", s0."utm_source", s0."utm_campaign", s0."referrer", s0."referrer_source", s0."country_code", s0."screen_size", s0."operating_system", s0."operating_system_version", s0."browser", s0."browser_version", s0."timestamp" FROM "sessions" AS s0  INNER JOIN (SELECT s0."session_id" AS "session_id", max(s0."timestamp") AS "timestamp" FROM "sessions" AS s0 WHERE (s0."timestamp" >= now() - INTERVAL 3600 SECOND) GROUP BY s0."session_id") AS s1 USING session_id, USING timestamp ORDER BY s0."timestamp"  FORMAT JSONCompact), Stack trace (when copying this message, always include the lines below):
plausible_events_db_1  |
plausible_events_db_1  | 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10542450 in /usr/bin/clickhouse
plausible_events_db_1  | 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f4272d in /usr/bin/clickhouse
plausible_events_db_1  | 2. ? @ 0xe0850a7 in /usr/bin/clickhouse
plausible_events_db_1  | 3. ? @ 0xd55e87d in /usr/bin/clickhouse
plausible_events_db_1  | 4. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xd561fb9 in /usr/bin/clickhouse
plausible_events_db_1  | 5. DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x8fee706 in /usr/bin/clickhouse
plausible_events_db_1  | 6. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x8ff1bc3 in /usr/bin/clickhouse
plausible_events_db_1  | 7. Poco::Net::HTTPServerConnection::run() @ 0xe389aa4 in /usr/bin/clickhouse
plausible_events_db_1  | 8. Poco::Net::TCPServerConnection::start() @ 0xe3b9a4b in /usr/bin/clickhouse
plausible_events_db_1  | 9. Poco::Net::TCPServerDispatcher::run() @ 0xe3b9ecd in /usr/bin/clickhouse
plausible_events_db_1  | 10. Poco::PooledThread::run() @ 0x105d05b7 in /usr/bin/clickhouse
plausible_events_db_1  | 11. Poco::ThreadImpl::runnableEntry(void*) @ 0x105cc3bc in /usr/bin/clickhouse
plausible_events_db_1  | 12. ? @ 0x105cdd5d in /usr/bin/clickhouse
plausible_events_db_1  | 13. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
plausible_events_db_1  | 14. clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
plausible_events_db_1  |
plausible_events_db_1  | 2021.04.07 10:36:39.792696 [ 82 ] {} <Error> HTTPHandler: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 658 (line 1, col 658): timestamp ORDER BY s0."timestamp"
plausible_events_db_1  |  FORMAT JSONCompact. Expected one of: LIMIT, WHERE, INNER, LIKE, GLOBAL NOT IN, AS, HAVING, IS, INTO OUTFILE, GROUP BY, OR, QuestionMark, BETWEEN, NOT LIKE, LEFT ARRAY JOIN, PREWHERE, AND, JOIN, Comma, alias, ORDER BY, array join, SETTINGS, UNION ALL, IN, ARRAY JOIN, FORMAT, Dot, WITH, NOT, Arrow, token, NOT IN, GLOBAL IN, table, table function, subquery or list of joined tables, Stack trace (when copying this message, always include the lines below):
plausible_events_db_1  |
plausible_events_db_1  | 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10542450 in /usr/bin/clickhouse
plausible_events_db_1  | 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f4272d in /usr/bin/clickhouse
plausible_events_db_1  | 2. ? @ 0xe0850a7 in /usr/bin/clickhouse
plausible_events_db_1  | 3. ? @ 0xd55e87d in /usr/bin/clickhouse
plausible_events_db_1  | 4. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xd561fb9 in /usr/bin/clickhouse
plausible_events_db_1  | 5. DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x8fee706 in /usr/bin/clickhouse
plausible_events_db_1  | 6. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x8ff1bc3 in /usr/bin/clickhouse
plausible_events_db_1  | 7. Poco::Net::HTTPServerConnection::run() @ 0xe389aa4 in /usr/bin/clickhouse
plausible_events_db_1  | 8. Poco::Net::TCPServerConnection::start() @ 0xe3b9a4b in /usr/bin/clickhouse
plausible_events_db_1  | 9. Poco::Net::TCPServerDispatcher::run() @ 0xe3b9ecd in /usr/bin/clickhouse
plausible_events_db_1  | 10. Poco::PooledThread::run() @ 0x105d05b7 in /usr/bin/clickhouse
plausible_events_db_1  | 11. Poco::ThreadImpl::runnableEntry(void*) @ 0x105cc3bc in /usr/bin/clickhouse
plausible_events_db_1  | 12. ? @ 0x105cdd5d in /usr/bin/clickhouse
plausible_events_db_1  | 13. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
plausible_events_db_1  | 14. clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
plausible_events_db_1  |  (version 20.3.8.53 (official build))
plausible_1            | 10:36:39.793 [debug] QUERY ERROR source="sessions" db=36.4ms queue=7.3ms idle=0.0ms
plausible_1            | SELECT s0."hostname", s0."domain", s0."user_id", s0."session_id", s0."start", s0."duration", s0."is_bounce", s0."entry_page", s0."exit_page", s0."pageviews", s0."events", s0."sign", s0."utm_medium", s0."utm_source", s0."utm_campaign", s0."referrer", s0."referrer_source", s0."country_code", s0."screen_size", s0."operating_system", s0."operating_system_version", s0."browser", s0."browser_version", s0."timestamp" FROM "sessions" AS s0  INNER JOIN (SELECT s0."session_id" AS "session_id", max(s0."timestamp") AS "timestamp" FROM "sessions" AS s0 WHERE (s0."timestamp" >= now() - INTERVAL ? SECOND) GROUP BY s0."session_id") AS s1 USING session_id, USING timestamp ORDER BY s0."timestamp" [3600]
plausible_1            | 10:36:39.819 [debug] QUERY OK source="salts" db=4.8ms queue=20.6ms idle=36.9ms
plausible_1            | DELETE FROM "salts" AS s0 WHERE (s0."inserted_at" < now() - '48 hours'::interval) []
plausible_1            | 10:36:39.821 [debug] QUERY OK source="salts" db=0.6ms queue=1.1ms idle=61.5ms
plausible_1            | SELECT s0."salt" FROM "salts" AS s0 ORDER BY s0."inserted_at" DESC LIMIT 2 []
plausible_1            | 10:37:39.750 [debug] Session store collecting garbage
plausible_1            | 10:37:39.750 [debug] Removed 0 sessions from store
plausible_1            | 10:38:39.750 [debug] Session store collecting garbage
plausible_1            | 10:38:39.751 [debug] Removed 0 sessions from store
```

**Reply by ukutaht** [reply]
Other than error logs, what is the problem? 500? Can you not access your Plausible installation?

**Reply by VictorElHajj** [reply]
Ah, sorry. Even after "plausible_1            | 10:36:39.748 [info] Access PlausibleWeb.Endpoint at http://stats.bogdanov.red"
the webpage just gives a "404". There is nothing there.

**Reply by ukutaht** [reply]
Pretty sure that 404 is not related to the container itself but networking config around it. What's tour reverse proxy config?

**Reply by VictorElHajj** [reply]
I have
```
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.plausible.rule=Host(`stats.website.tld`)'
      - 'traefik.http.routers.plausible.entrypoints=websecure'
      - 'traefik.http.routers.plausible.tls=true'
      - 'traefik.http.routers.plausible.tls.certresolver=le'
      - 'traefik.http.services.plausible.loadbalances.server.port=8000'
  ```
on the plausible container (which has worked for many other services). I also set the same host name but with https in the BASE_URL env like in my first post.  
my traefik config itself is
```toml
debugLevel = "DEBUG"
defaultEntryPoints = ["web", "websecure"]

[api]
    insecure = false
    dashboard = false

[providers]
    [providers.docker]
    exposedByDefault = false
    network = "web"

[entryPoints]
    [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
        [entryPoints.web.http.redirections]
            [entryPoints.web.http.redirections.entryPoint]
            to = "websecure"
            scheme = "https"
    [entryPoints.websecure]
    address = ":443"


[certificatesResolvers]
    [certificatesResolvers.le.acme]
    email = "[my email]"
    storage = "/acme.json"
    tlsChallenge = true
```
My plausible container also has the same external "web" network as the other services. It's also basically the same as the traefik example provided in plausible/hosting
