### ISSUE TITLE
Can't deploy to a pre-existing database

### ISSUE THREAD

**Issue by Crocmagnon** [plausible/analytics#405]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

Somewhat similar to #243 

## Bug report
**Describe the bug**
I already have a postgresql server running so I created a database and a non-privileged user for Plausible but the app can't start with the provided docker-compose.

Here's the database url I used:

```env
DATABASE_URL=postgres://plausible:xxx@192.168.0.52/plausible
```

Plausible complains it can't connect to the `postgres` database. I guess it's using it to *create* the db I put in the URL, and I didn't allow the plausible user to connect to the postgres database anyway.

I tried various things such as allowing the user to connect to the postgres db, trying not to run `db createdb` in the command, ...

Everything led to an error:
* no `db createdb`: can't migrate on clickhouse db because the db doesn't exist
* allow connection to postgres db: complains it doesn't have "CREATE DATABASE" privileges (that's not a privilege I'm going to give to an app)

Would it be possible to allow connections to pre-existing databases ? Like just test if the DB exists and the user can create a table and if so well, continue with the setup.

Here's the full docker-compose.yaml:
```yaml
version: "3.3"
services:
  geoip:
    image: maxmindinc/geoipupdate
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168 # update every 7 days
    env_file:
      - geoip.env
    volumes:
      - geoip:/usr/share/GeoIP

  plausible_events_db:
    image: yandex/clickhouse-server:latest
    volumes:
      - event-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    command: sh -c "sleep 10 && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_events_db
    ports:
      - 8000:8000
    environment:
      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
    env_file:
      - plausible-conf.env
    volumes:
      - geoip:/geoip:ro

volumes:
  event-data:
    driver: local
  geoip:
    driver: local
```

**Expected behavior**
When the database set in the URL already exists, use it. Don't try to create a new one even if `/entrypoint.sh db createdb` is run.

**Screenshots (If applicable)**

**Environment (If applicable):**
 - OS: ubuntu 20.04 with docker compose
