### ISSUE TITLE
Logging in fails with 403 after upgrading to v2.1.0

### ISSUE THREAD

**Issue by nmaggioni** [plausible/analytics#4126]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

After upgrading from v2.0.0 I am having the same issue that was [reported for v2.1.0-rc0](https://github.com/plausible/analytics/discussions/3817#discussioncomment-8640288): when trying to log in I get a 403 and no logs.

As already mentioned there by others, I can reproduce the problem by [reverting back to v2.0.0](https://github.com/plausible/analytics/discussions/3817#discussioncomment-8641166) and then switching again to the v2.1.0 image. Postgres and Clickhouse images have been upgraded (respectively to `16-alpine` and `24.3.3.102-alpine`), the `TOTP_VAULT_KEY` env var has been added, and `SECRET_KEY_BASE` is untouched.

### Expected behavior

Login should be possible.

### Screenshots

![Screenshot taken from the discussion on the v2.1.0-rc0 release](https://private-user-images.githubusercontent.com/93723087/309231396-367bd38f-3b6f-40d6-9d62-e4e3daaf838e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjMxNDAsIm5iZiI6MTcxNjQ2Mjg0MCwicGF0aCI6Ii85MzcyMzA4Ny8zMDkyMzEzOTYtMzY3YmQzOGYtM2I2Zi00MGQ2LTlkNjItZTRlM2RhYWY4MzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDExMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MTM0ZWI1MDE0NzRlYjcyOGVjNmQ2NTIyZDg0OThkYmUxYmNlMmViYzFhNGFkNzU1YTFlYjViNzIxZmZlODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iMQ5t2E7LGSFNkPwFLz50TL_GsAG9GENEnOaNuOj8YU)

### Environment

```markdown
- OS: Linux
- Browser: Chromium
- Browser Version: 125.0.6422.60
```

**Comment by ruslandoga** [comment]
👋 @nmaggioni 

Would you be able to verify that `SECRET_KEY_BASE` env var is the same in both containers? Also would you be able to decode the contents of the `_plausible_key` cookie? Please see https://github.com/plausible/analytics/issues/3762

**Comment by nmaggioni** [comment]
Thanks, the contents of the cookie seem to be correct (the token matches `[a-zA-Z0-9_]+` as usual):
```
%{
  "_csrf_token" => "<TOKEN_HERE>",
  "current_user_id" => 1,
  "last_seen" => 1716469476,
  "login_dest" => nil,
  "session_timeout_at" => 1717679076
}
```

This cookie was set by v2.0.0 and, I guess, ignored or rejected by v2.1.0 since I am prompted to login again. When using the new version deleting it and/or using a temporary browser profile still gets me a 403 on login and no new cookie is set.

The `SECRET_KEY_BASE` env var has indeed the same expected value in both images.

If that can be of interest I am deploying Plausible on Kubernetes and my manifests have been more or less the same since v1.4.4. The only changes made while upgrading to v2.1.0 were bumping PostgreSQL, ClickHouse and Plausible image versions to the [recommended values](https://github.com/plausible/community-edition/blob/ffc883de7edfcbd7ffeb0b5da9e2ffd4b020a3f8/docker-compose.yml#L5) and setting the new `TOTP_VAULT_KEY` env var.

**Comment by ledermann** [comment]
> The only changes made while upgrading to v2.1.0 were bumping PostgreSQL, [...] image versions to the recommended values [...]

@nmaggioni: Besides all other things: Bumping PostgreSQL to a new major version will not work. It requires a backup/restore. Check the logs of the PostgreSQL container.

**Comment by nmaggioni** [comment]
@ruslandoga Here are the traces, recorded using a fresh browser profile.

<details>
  <summary>Visiting the root and being served the Welcome dialog</summary>

```plaintext
'Elixir.PlausibleWeb.AuthPlug':call(#{owner=><0.4407.0>, port=>INTERNAL_PORT_HERE, private=>#{'Elixir.PlausibleWeb.Router'=>[], plug_session_fetch=>done, plug_session=>#{}, before_send=>[#Fun<Elixir.Phoenix.Controller.4.96996861>,
 #Fun<Elixir.Plug.Session.0.76384852>,#Fun<Elixir.Plug.Telemetry.0.54455629>], phoenix_endpoint=>'Elixir.PlausibleWeb.Endpoint', phoenix_format=><<"html">>, phoenix_router=>'Elixir.PlausibleWeb.Router', robots=><<"noindex, nofollow">>}, scheme=>http, status=>nil, script_name=>[], state=>unset, host=><<"INTERNAL_HOSTNAME_HERE">>, cookies=>#{}, params=>#{}, '__struct__'=>'Elixir.Plug.Conn', halted=>false, assigns=>#{flash=>#{}}, method=><<"GET">>, path_info=>[], adapter=>{'Elixir.Plug.Cowboy.Conn',#{pid => <0.4406.0>,port => INTERNAL_PORT_HERE,
                             scheme => <<"http">>,version => 'HTTP/1.1',
                             path => <<"/">>,host => <<"INTERNAL_HOSTNAME_HERE">>,
                             peer => {{CLIENT_IP_HERE},44704},
                             sock => {{10,42,1,88},8000},
                             bindings => #{},
                             ref => 'Elixir.PlausibleWeb.Endpoint.HTTP',
                             cert => undefined,
                             headers =>
                                 #{<<"accept">> =>
                                       <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7">>,
                                   <<"accept-encoding">> =>
                                       <<"gzip, deflate">>,
                                   <<"accept-language">> =>
                                       <<"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7">>,
                                   <<"connection">> => <<"keep-alive">>,
                                   <<"host">> => <<"INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE">>,
                                   <<"upgrade-insecure-requests">> => <<"1">>,
                                   <<"user-agent">> =>
                                       <<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36">>},
                             method => <<"GET">>,qs => <<>>,
                             path_info => undefined,body_length => 0,
                             has_body => false,streamid => 1,
                             host_info => undefined}}, secret_key_base=><<"SECRET_KEY_BASE_ENV_VAR_HERE">>, req_headers=>[{<<"accept">>,
  <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7">>},
 {<<"accept-encoding">>,<<"gzip, deflate">>},
 {<<"accept-language">>,<<"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7">>},
 {<<"connection">>,<<"keep-alive">>},
 {<<"host">>,<<"INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE">>},
 {<<"upgrade-insecure-requests">>,<<"1">>},
 {<<"user-agent">>,
  <<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36">>}], remote_ip=>{CLIENT_IP_HERE}, body_params=>#{}, query_params=>#{}, query_string=><<>>, request_path=><<"/">>, path_params=>#{}, req_cookies=>#{}, resp_body=>nil, resp_cookies=>#{}, resp_headers=>[{<<"cache-control">>,<<"max-age=0, private, must-revalidate">>},
 {<<"x-request-id">>,<<"F9IvVG98mZw3SeEAACVh">>},
 {<<"access-control-allow-credentials">>,<<"true">>},
 {<<"access-control-allow-origin">>,<<"*">>},
 {<<"access-control-expose-headers">>,<<>>},
 {<<"referrer-policy">>,<<"strict-origin-when-cross-origin">>},
 {<<"x-content-type-options">>,<<"nosniff">>},
 {<<"x-download-options">>,<<"noopen">>},
 {<<"x-frame-options">>,<<"SAMEORIGIN">>},
 {<<"x-permitted-cross-domain-policies">>,<<"none">>},
 {<<"x-robots-tag">>,<<"noindex, nofollow">>}]}, [])
```
</details>

<details>
  <summary>Visiting the login page</summary>

```plaintext
'Elixir.PlausibleWeb.AuthPlug':call(#{owner=><0.4416.0>, port=>INTERNAL_PORT_HERE, private=>#{'Elixir.PlausibleWeb.Router'=>[], plug_session_fetch=>done, plug_session=>#{}, before_send=>[#Fun<Elixir.Phoenix.Controller.4.96996861>,
 #Fun<Elixir.Plug.Session.0.76384852>,#Fun<Elixir.Plug.Telemetry.0.54455629>], phoenix_endpoint=>'Elixir.PlausibleWeb.Endpoint', phoenix_format=><<"html">>, phoenix_router=>'Elixir.PlausibleWeb.Router', robots=><<"noindex, nofollow">>}, scheme=>http, status=>nil, script_name=>[], state=>unset, host=><<"INTERNAL_HOSTNAME_HERE">>, cookies=>#{}, params=>#{}, '__struct__'=>'Elixir.Plug.Conn', halted=>false, assigns=>#{flash=>#{}}, method=><<"GET">>, path_info=>[<<"login">>], adapter=>{'Elixir.Plug.Cowboy.Conn',#{pid => <0.4406.0>,port => INTERNAL_PORT_HERE,
                             scheme => <<"http">>,version => 'HTTP/1.1',
                             path => <<"/login">>,
                             host => <<"INTERNAL_HOSTNAME_HERE">>,
                             peer => {{CLIENT_IP_HERE},44704},
                             sock => {{10,42,1,88},8000},
                             bindings => #{},
                             ref => 'Elixir.PlausibleWeb.Endpoint.HTTP',
                             cert => undefined,
                             headers =>
                                 #{<<"accept">> =>
                                       <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7">>,
                                   <<"accept-encoding">> =>
                                       <<"gzip, deflate">>,
                                   <<"accept-language">> =>
                                       <<"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7">>,
                                   <<"connection">> => <<"keep-alive">>,
                                   <<"host">> => <<"INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE">>,
                                   <<"referer">> =>
                                       <<"http://INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE/">>,
                                   <<"upgrade-insecure-requests">> => <<"1">>,
                                   <<"user-agent">> =>
                                       <<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36">>},
                             method => <<"GET">>,qs => <<>>,
                             path_info => undefined,body_length => 0,
                             has_body => false,streamid => 3,
                             host_info => undefined}}, secret_key_base=><<"SECRET_KEY_BASE_ENV_VAR_HERE">>, req_headers=>[{<<"accept">>,
  <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7">>},
 {<<"accept-encoding">>,<<"gzip, deflate">>},
 {<<"accept-language">>,<<"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7">>},
 {<<"connection">>,<<"keep-alive">>},
 {<<"host">>,<<"INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE">>},
 {<<"referer">>,<<"http://INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE/">>},
 {<<"upgrade-insecure-requests">>,<<"1">>},
 {<<"user-agent">>,
  <<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36">>}], remote_ip=>{CLIENT_IP_HERE}, body_params=>#{}, query_params=>#{}, query_string=><<>>, request_path=><<"/login">>, path_params=>#{}, req_cookies=>#{}, resp_body=>nil, resp_cookies=>#{}, resp_headers=>[{<<"cache-control">>,<<"max-age=0, private, must-revalidate">>},
 {<<"x-request-id">>,<<"F9IvXDuFqRl3FxYAACYh">>},
 {<<"access-control-allow-credentials">>,<<"true">>},
 {<<"access-control-allow-origin">>,<<"*">>},
 {<<"access-control-expose-headers">>,<<>>},
 {<<"referrer-policy">>,<<"strict-origin-when-cross-origin">>},
 {<<"x-content-type-options">>,<<"nosniff">>},
 {<<"x-download-options">>,<<"noopen">>},
 {<<"x-frame-options">>,<<"SAMEORIGIN">>},
 {<<"x-permitted-cross-domain-policies">>,<<"none">>},
 {<<"x-robots-tag">>,<<"noindex, nofollow">>}]}, [])
```
</details>

<details>
  <summary>Logging in and receiving the customized 403 page</summary>

```plaintext
'Elixir.PlausibleWeb.AuthPlug':call(#{owner=><0.4427.0>, port=>INTERNAL_PORT_HERE, private=>#{'Elixir.PlausibleWeb.Router'=>[], plug_session_fetch=>done, plug_session=>#{}, before_send=>[#Fun<Elixir.Phoenix.Controller.4.96996861>,
 #Fun<Elixir.Plug.Session.0.76384852>,#Fun<Elixir.Plug.Telemetry.0.54455629>], phoenix_endpoint=>'Elixir.PlausibleWeb.Endpoint', phoenix_format=><<"html">>, phoenix_router=>'Elixir.PlausibleWeb.Router', robots=><<"noindex, nofollow">>}, scheme=>http, status=>nil, script_name=>[], state=>unset, host=><<"INTERNAL_HOSTNAME_HERE">>, cookies=>#{}, params=>#{<<"_csrf_token">>=><<"DiN8JgMHIjwJPXUpGjoPZyAHFEQYE0wYAgNkaeHqsYGLQJe4WIFtwaxH">>, <<"email">>=><<"USERNAME_HERE">>, <<"password">>=><<"PASSWORD_HERE">>}, '__struct__'=>'Elixir.Plug.Conn', halted=>false, assigns=>#{flash=>#{}}, method=><<"POST">>, path_info=>[<<"login">>], adapter=>{'Elixir.Plug.Cowboy.Conn',#{pid => <0.4406.0>,port => INTERNAL_PORT_HERE,
                             scheme => <<"http">>,version => 'HTTP/1.1',
                             path => <<"/login">>,
                             host => <<"INTERNAL_HOSTNAME_HERE">>,
                             peer => {{CLIENT_IP_HERE},44704},
                             sock => {{10,42,1,88},8000},
                             bindings => #{},
                             ref => 'Elixir.PlausibleWeb.Endpoint.HTTP',
                             cert => undefined,
                             headers =>
                                 #{<<"accept">> =>
                                       <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7">>,
                                   <<"accept-encoding">> =>
                                       <<"gzip, deflate">>,
                                   <<"accept-language">> =>
                                       <<"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7">>,
                                   <<"cache-control">> => <<"max-age=0">>,
                                   <<"connection">> => <<"keep-alive">>,
                                   <<"content-length">> => <<"133">>,
                                   <<"content-type">> =>
                                       <<"application/x-www-form-urlencoded">>,
                                   <<"host">> => <<"INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE">>,
                                   <<"origin">> =>
                                       <<"http://INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE">>,
                                   <<"referer">> =>
                                       <<"http://INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE/login">>,
                                   <<"upgrade-insecure-requests">> => <<"1">>,
                                   <<"user-agent">> =>
                                       <<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36">>},
                             method => <<"POST">>,qs => <<>>,
                             path_info => undefined,body_length => 133,
                             has_body => true,streamid => 4,
                             host_info => undefined,has_read_body => true}}, secret_key_base=><<"SECRET_KEY_BASE_ENV_VAR_HERE">>, req_headers=>[{<<"accept">>,
  <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7">>},
 {<<"accept-encoding">>,<<"gzip, deflate">>},
 {<<"accept-language">>,<<"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7">>},
 {<<"cache-control">>,<<"max-age=0">>},
 {<<"connection">>,<<"keep-alive">>},
 {<<"content-length">>,<<"133">>},
 {<<"content-type">>,<<"application/x-www-form-urlencoded">>},
 {<<"host">>,<<"INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE">>},
 {<<"origin">>,<<"http://INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE">>},
 {<<"referer">>,<<"http://INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE/login">>},
 {<<"upgrade-insecure-requests">>,<<"1">>},
 {<<"user-agent">>,
  <<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36">>}], remote_ip=>{CLIENT_IP_HERE}, body_params=>#{<<"_csrf_token">>=><<"DiN8JgMHIjwJPXUpGjoPZyAHFEQYE0wYAgNkaeHqsYGLQJe4WIFtwaxH">>, <<"email">>=><<"USERNAME_HERE">>, <<"password">>=><<"PASSWORD_HERE">>}, query_params=>#{}, query_string=><<>>, request_path=><<"/login">>, path_params=>#{}, req_cookies=>#{}, resp_body=>nil, resp_cookies=>#{}, resp_headers=>[{<<"cache-control">>,<<"max-age=0, private, must-revalidate">>},
 {<<"x-request-id">>,<<"F9IvZhFTQP3eEl8AACdh">>},
 {<<"access-control-allow-credentials">>,<<"true">>},
 {<<"access-control-allow-origin">>,<<"*">>},
 {<<"access-control-expose-headers">>,<<>>},
 {<<"referrer-policy">>,<<"strict-origin-when-cross-origin">>},
 {<<"x-content-type-options">>,<<"nosniff">>},
 {<<"x-download-options">>,<<"noopen">>},
 {<<"x-frame-options">>,<<"SAMEORIGIN">>},
 {<<"x-permitted-cross-domain-policies">>,<<"none">>},
 {<<"x-robots-tag">>,<<"noindex, nofollow">>}]}, [])
```
</details>

<details>
  <summary>Navigating back the root and being served the Welcome dialog once again</summary>

```plaintext
'Elixir.PlausibleWeb.AuthPlug':call(#{owner=><0.4403.0>, port=>INTERNAL_PORT_HERE, private=>#{'Elixir.PlausibleWeb.Router'=>[], plug_session_fetch=>done, plug_session=>#{}, before_send=>[#Fun<Elixir.Phoenix.Controller.4.96996861>,
 #Fun<Elixir.Plug.Session.0.76384852>,#Fun<Elixir.Plug.Telemetry.0.54455629>], phoenix_endpoint=>'Elixir.PlausibleWeb.Endpoint', phoenix_format=><<"html">>, phoenix_router=>'Elixir.PlausibleWeb.Router', robots=><<"noindex, nofollow">>}, scheme=>http, status=>nil, script_name=>[], state=>unset, host=><<"INTERNAL_HOSTNAME_HERE">>, cookies=>#{}, params=>#{}, '__struct__'=>'Elixir.Plug.Conn', halted=>false, assigns=>#{flash=>#{}}, method=><<"GET">>, path_info=>[], req_headers=>[{<<"accept">>,
  <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7">>},
 {<<"accept-encoding">>,<<"gzip, deflate">>},
 {<<"accept-language">>,<<"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7">>},
 {<<"connection">>,<<"keep-alive">>},
 {<<"host">>,<<"INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE">>},
 {<<"upgrade-insecure-requests">>,<<"1">>},
 {<<"user-agent">>,
  <<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36">>}], remote_ip=>{CLIENT_IP_HERE}, adapter=>{'Elixir.Plug.Cowboy.Conn',#{pid => <0.4387.0>,port => INTERNAL_PORT_HERE,
                             scheme => <<"http">>,version => 'HTTP/1.1',
                             path => <<"/">>,host => <<"INTERNAL_HOSTNAME_HERE">>,
                             peer => {{CLIENT_IP_HERE},48096},
                             sock => {{10,42,1,90},8000},
                             bindings => #{},
                             ref => 'Elixir.PlausibleWeb.Endpoint.HTTP',
                             cert => undefined,
                             headers =>
                                 #{<<"accept">> =>
                                       <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7">>,
                                   <<"accept-encoding">> =>
                                       <<"gzip, deflate">>,
                                   <<"accept-language">> =>
                                       <<"it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7">>,
                                   <<"connection">> => <<"keep-alive">>,
                                   <<"host">> => <<"INTERNAL_HOSTNAME_HERE:INTERNAL_PORT_HERE">>,
                                   <<"upgrade-insecure-requests">> => <<"1">>,
                                   <<"user-agent">> =>
                                       <<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36">>},
                             method => <<"GET">>,qs => <<>>,
                             path_info => undefined,streamid => 7,
                             body_length => 0,has_body => false,
                             host_info => undefined}}, body_params=>#{}, query_params=>#{}, query_string=><<>>, request_path=><<"/">>, secret_key_base=><<"SECRET_KEY_BASE_ENV_VAR_HERE">>, resp_body=>nil, resp_cookies=>#{}, resp_headers=>[{<<"cache-control">>,<<"max-age=0, private, must-revalidate">>},
 {<<"x-request-id">>,<<"F9Iw2qjk2SXhwd8AACYB">>},
 {<<"access-control-allow-credentials">>,<<"true">>},
 {<<"access-control-allow-origin">>,<<"*">>},
 {<<"access-control-expose-headers">>,<<>>},
 {<<"referrer-policy">>,<<"strict-origin-when-cross-origin">>},
 {<<"x-content-type-options">>,<<"nosniff">>},
 {<<"x-download-options">>,<<"noopen">>},
 {<<"x-frame-options">>,<<"SAMEORIGIN">>},
 {<<"x-permitted-cross-domain-policies">>,<<"none">>},
 {<<"x-robots-tag">>,<<"noindex, nofollow">>}], req_cookies=>#{}, path_params=>#{}}, [])
```
</details>

By enabling query logging on Postgres through the `-c log_statement=all` flag I saw that (on top of the background noise generated by Oban jobs) only a single query was being made when serving each of the above requests: `SELECT TRUE FROM "users" AS u0 LIMIT 1`. Running this query manually returns `t` as expected.

I have no Elixir knowledge but while I was at it I have also tried tracing other Plugs out of curiosity and, while `FirstLaunchPlug`, `LastSeenPlug`, `NoRobots`, `SessionTimeoutPlug`, `Tracker` produced some output when POSTing the login data, none of them seemed to log anything that caught my eye.

Here are the relevant portions of my K8S manifest:

<details>
  <summary>K8S deployment</summary>

```yaml
# PostgreSQL
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: plausible
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: plausible
spec:
  replicas: 1
  serviceName: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          env: # Auth vars
      volumes:
        - name: data
          hostPath:
            path: # Unix path
            type: Directory

# Plausible
---
apiVersion: v1
kind: Secret
metadata:
  name: plausible
  namespace: plausible
type: Opaque
data:
  secretKeyBase: # SECRET_KEY_BASE value re-encoded to base64
  totpVaultKey: # TOTP_VAULT_KEY value re-encoded to base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible
  namespace: plausible
spec:
  replicas: 1
    spec:
      initContainers:
        - name: wait-postgres
          image: docker.io/library/alpine:3.17
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 postgres 5432 && exit 0 || sleep 3; done; exit 1"]
        - name: wait-clickhouse
          image: docker.io/library/alpine:3.17
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 clickhouse 8123 && exit 0 || sleep 3; done; exit 1"]
      containers:
        - name: plausible
          image: plausible/analytics:v2.0.0  # ghcr.io/plausible/community-edition:v2.1.0
          env:
            - name: BASE_URL
              value: # EXTERNAL URL
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: plausible
                  key: secretKeyBase
                  optional: false
            - name: TOTP_VAULT_KEY
              valueFrom:
                secretKeyRef:
                  name: plausible
                  key: totpVaultKey
                  optional: false
            - name: GEOLITE2_COUNTRY_DB
              value: /geoip/GeoLite2-Country.mmdb
            - name: IP_GEOLOCATION_DB
              value: /geoip/GeoLite2-City.mmdb
            - name: GEONAMES_SOURCE_FILE
              value: /geoip/geonames.lite.csv
            - name: DISABLE_REGISTRATION
              value: "true"
            - name: MAILER_EMAIL
              value: # Sender address
            - name: CRON_ENABLED
              value: "true"
            - name: DATABASE_URL
              value: "postgres://<USERNAME>:<PASSWORD>@postgres:5432/plausible_db"
            - name: CLICKHOUSE_DATABASE_URL
              value: "http://clickhouse:8123/plausible_events_db"
            - name: SMTP_HOST_ADDR
              value: "mailer"
            - name: SMTP_HOST_PORT
              value: "25"
          ports:
            - protocol: TCP
              containerPort: 8000
              hostPort: # Host port
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
          command: ["/bin/sh"]
          args: ["-c", "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"]
          volumeMounts:
            - mountPath: /geoip
              name: geoip
              readOnly: true
      volumes:
        - name: geoip
          hostPath:
            path: # Unix path
            type: Directory
```
</details>

For these tests I am accessing the instance locally through its exposed port.

---

@ledermann My bad, I took that for granted and did not elaborate for the sake of brevity. The upgrade was indeed done [as recommended](https://github.com/plausible/community-edition/blob/ffc883de7edfcbd7ffeb0b5da9e2ffd4b020a3f8/upgrade/postgres.md) and Postgres shows no errors at startup or when trying to log in. ClickHouse seems happy too, just in case.
