### ISSUE TITLE
Existing Google Search Console API integration doesn’t work on new install

### ISSUE THREAD

**Issue by readtedium** [plausible/analytics#4524]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Hi there, I’m trying to move a Docker install of my Plausible Community Edition from x64 to ARM. I am using the same domain as previously, just trying to reset the data. The installation has gone fine, but I’m running into an issue getting my existing Google Analytics integration to work. 

Essentially, I go through the process of connecting to my existing API connection, and I run into an error that states: “Your Search Console account hasn't been connected successfully. Please unlink your Google account and try linking it again.”

I even tried building a fresh integration via the Google API, going off the docs, and it did not work. (I should note that one difference between the docs and my experience was that I was unable to click a checkbox to approve the integration, as I show in one of the screenshots. Could that be a factor?)

I think there is a chance it may be a bug given the fact that the integration worked fine on another server with the very same credentials on the same URL.

### Expected behavior

A successful integration between Google and Plausible.

### Screenshots

![Screenshot from 2024-09-03 19-16-38](https://github.com/user-attachments/assets/434392e9-4b6b-48fb-8c39-fc4ea562c3e3)

![Screenshot from 2024-09-03 19-17-37](https://github.com/user-attachments/assets/c75f04e1-0025-4950-b31d-9a14e20d9baa)

### Environment

```markdown
- OS: Nobara Linux 40 (Desktop); AlmaLinux 9 on ARM (Server)
- Browser: Vivaldi
- Browser Version: 6.9.3447.37
```

**Comment by ruslandoga** [comment]
👋 @readtedium 

What version are you using? Are the versions the same on both servers?

**Comment by readtedium** [comment]
The old app used:

```
  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.1
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env
```

The new one uses:

```
  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.1
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env
```

I should make it clear, I actually built a new “for scratch” integration after the initial one did not work, following the guide, and it did not work for me.
