### ISSUE TITLE
Invite E-Mail not sending on 2.1.4 even when testing SMTP is successful

### ISSUE THREAD

**Issue by degoya** [plausible/analytics#4840]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

I'm not able to send invite Links. Doesn't matter if i invite as Admin or Viewer User.

in my docker compose file i've added the following enviromentvars:

```
      - 'MAILER_ADAPTER=Bamboo.Mua'
      - 'MAILER_EMAIL=plausible@mydomain.de'
      - 'SMTP_HOST_ADDR=mail1.mydomain.de'
      - 'SMTP_HOST_PORT=25'
      - 'SMTP_USER_NAME=plausible@mydomain.de'
      - 'SMTP_USER_PWD=mypassword'
      - 'SMTP_HOST_SSL_ENABLED=false'
```

**i tried to debug the mail and it is working**
when i connect to the docker container and start 
`bin/plausible remote`
and execute:
`Application.get_env(:plausible, Plausible.Mailer)`
i get as result:
```
[
  adapter: Bamboo.Mua,
  ssl: [middlebox_comp_mode: false],
  protocol: :tcp,
  relay: "mail1.mymailserver.de",
  port: 25,
  auth: [username: "plausible@mydomain.de", password: "mypassword"]
]
```
what matches my settings in the environment.

when i try to send a test email with
```
email = Bamboo.Email.new_email(from: "plausible@mydomain.de", to: "admin@mydomain.de", subject: "test", text_body: "test")
Plausible.Mailer.deliver_now(email)
```
i get a mail delivered to my inbox.

As soon when i go and send an invite link via the plausible UI i get a error in the log:
`2024-11-19T17:10:52.573292413Z 17:10:52.566 request_id=GAlty2uNwBoaMdoAADUC [error] Failed to send e-mail`

this error with different request_id comes for every email adress i try to add.

i'm running on a Hetzner Cloud Server (blocking of Ports is disabled by support)

is there any way i could debug it futher?
why i'm able to send mails via STMP in test but plausible fails?

Here is my complete Docker Compose File to have everything togehter in that issue:

```
services:
  plausible:
    image: 'ghcr.io/plausible/community-edition:v2.1.4'
    command: 'sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"'
    environment:
      - SERVICE_FQDN_PLAUSIBLE
      - 'DATABASE_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@plausible-db:5432/${POSTGRES_DB:-plausible-db}'
      - 'CLICKHOUSE_DATABASE_URL=http://plausible-events-db:8123/plausible_events_db'
      - 'BASE_URL=${SERVICE_FQDN_PLAUSIBLE}'
      - 'SECRET_KEY_BASE=${SERVICE_BASE64_64_PLAUSIBLE}'
      - 'TOTP_VAULT_KEY=${SERVICE_REALBASE64_32_TOTP}'
      - 'MAILER_ADAPTER=Bamboo.Mua'
      - 'MAILER_NAME=Plausible'
      - 'MAILER_EMAIL=plausible@mydomain.de'
      - 'SMTP_HOST_ADDR=mail1.mydomain.de'
      - 'SMTP_HOST_PORT=465'
      - 'SMTP_USER_NAME=plausible@mydomain.de'
      - 'SMTP_USER_PWD=mypassword'
      - 'SMTP_HOST_SSL_ENABLED=true'
    depends_on:
      plausible-db:
        condition: service_healthy
      plausible-events-db:
        condition: service_healthy
      mail:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--tries=1'
        - '--spider'
        - 'http://127.0.0.1:8000/api/health'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s
  plausible-db:
    image: 'postgres:16-alpine'
    volumes:
      - 'plausible-postgres-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-plausible-db}'
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
  plausible-events-db:
    image: 'clickhouse/clickhouse-server:24.3.3.102-alpine'
    volumes:
      - 'plausible-events-data:/var/lib/clickhouse'
      -
        type: bind
        source: ./clickhouse/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/logging.xml
        read_only: true
        content: '<clickhouse><profiles><default><log_queries>0</log_queries><log_query_threads>0</log_query_threads></default></profiles></clickhouse>'
      -
        type: bind
        source: ./clickhouse/clickhouse-user-config.xml
        target: /etc/clickhouse-server/users.d/logging.xml
        read_only: true
        content: '<clickhouse><logger><level>warning</level><console>true</console></logger><query_thread_log remove="remove"/><query_log remove="remove"/><text_log remove="remove"/><trace_log remove="remove"/><metric_log remove="remove"/><asynchronous_metric_log remove="remove"/><session_log remove="remove"/><part_log remove="remove"/></clickhouse>'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1'
      start_period: 30s
```

### Expected behavior

Sending invite links via the setup mailer

### Environment

```markdown
- Host OS: community-edition Docker Container
- Client OS: Windows 10
- Browser: FF 
- Browser Version: 132.0.2 (64-Bit)
```
