### ISSUE TITLE
SMTP Issue OVH

### ISSUE THREAD

**Issue by asijoumi** [plausible/analytics#5346]
### Past Issues Searched

- [x] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [x] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Hi !

I use Plausible CE 2.1.1 but I have issues with mails...

This is my configuration:
```
SMTP_HOST_ADDR: ssl0.ovh.net
SMTP_HOST_PORT: 587
SMTP_USER_NAME: <usermail>
SMTP_USER_PWD: <password>
MAILER_EMAIL: <usermail>
MAILER_ADAPTER: Bamboo.SMTPAdapter
LOG_LEVEL: debug
```

But I always got this issue: 
```
17:10:40.556 [error] Task #PID<0.4475.0> started from #PID<0.4474.0> terminating
** (ArgumentError) raise/1 and reraise/2 expect a module name, string or exception as the first argument, got: {:network_failure, ~c"ssl0.ovh.net", {:error, :closed}}
    (bamboo 2.3.0) lib/bamboo/strategies/task_supervisor_strategy.ex:25: anonymous fn/3 in Bamboo.TaskSupervisorStrategy.deliver_later/3
    (elixir 1.16.0) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: #Function<0.95237244/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>
    Args: []
```

I tried to read the source code, but I think there is something wrong with Bamboo...

### Expected behavior

Sending mail properly

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by asijoumi** [comment]
I tried this configuration:

```yml
- name: MAILER_ADAPTER
  value: "Bamboo.SMTPAdapter"
- name: SMTP_HOST_ADDR
  value: "{{ .Values.SMTP_HOST_ADDR }}"
- name: SMTP_HOST_PORT
  value: "465"
- name: SMTP_USER_NAME
  value: "{{ .Values.SMTP_USER_NAME }}"
- name: SMTP_USER_PWD
  valueFrom:
    secretKeyRef:
      name: plausible-credentials
      key: smtp-user-pwd
- name: SMTP_HOST_SSL_ENABLED
  value: "true"
- name: SMTP_ENABLE_STARTTLS
  value: "false"
- name: SMTP_RETRIES
  value: "10"
- name: LOG_LEVEL
  value: "debug"
```

But I stil got this error:

```
05:11:20.482 [error] Task #PID<0.4468.0> started from #PID<0.4467.0> terminating
** (ArgumentError) raise/1 and reraise/2 expect a module name, string or exception as the first argument, got: {:network_failure, ~c"ssl0.ovh.net", {:error, {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}}}    (bamboo 2.3.0) lib/bamboo/strategies/task_supervisor_strategy.ex:25: anonymous fn/3 in Bamboo.TaskSupervisorStrategy.deliver_later/3    (elixir 1.16.0) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: #Function<0.95237244/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>    Args: []
```

I think there is something wrong with certificate..

**Comment by asijoumi** [comment]
Works fine with Metabase (analytic tool):

<img width="506" alt="Image" src="https://github.com/user-attachments/assets/c30bb551-9b0d-4abd-95fe-49597394e6f5" />

Works fine with Appsmith (nocode tool):

<img width="717" alt="Image" src="https://github.com/user-attachments/assets/a793731a-9fa4-4ac6-89cb-54147aaff45d" />

**So I think, this is due to the TLS ...**

**Comment by ruslandoga** [comment]
👋 @asijoumi 

The problem is indeed with TLS and `Bamboo.SMTPAdapter`. Recently Erlang switched from not verifying the peers by default to verifying the peers by default and thus requiring cacerts. `Bamboo.SMTPAdapter` hasn't been updated to accept cacerts option. You can try `Bamboo.Mua`.

```yml
- name: MAILER_ADAPTER
  value: "Bamboo.Mua"
- name: SMTP_HOST_ADDR
  value: "{{ .Values.SMTP_HOST_ADDR }}"
- name: SMTP_HOST_PORT
  value: "465"
- name: SMTP_USER_NAME
  value: "{{ .Values.SMTP_USER_NAME }}"
- name: SMTP_USER_PWD
  valueFrom:
    secretKeyRef:
      name: plausible-credentials
      key: smtp-user-pwd
- name: LOG_LEVEL
  value: "debug"
```

**Comment by asijoumi** [comment]
Hi ! Thank you for answering.

I tried this one, but I still got this error :
```
04:48:48.186 request_id=GDiKrEjSwQX8VvoAAAVC [debug] Sending email with Bamboo.Mua:
%Bamboo.Email{from: {nil, "hello@plausible.local"}, to: [nil: "xxx"], cc: [], bcc: [], subject: "Plausible password reset", html_body: "<a href=\"https://plausible.prod.xxx/password/reset?token=SFMyNTY.g2gDdAAAAAF3BWVtYWlsbQAAABhhaW1lbi5zaWpvdW1pQGhhYml0LmltbW9uBgA0yNNblgFiAAFRgA.crRy_hPs5fCwWIjePMIwIGef__Zv8rq0NLRqQAM7v9E\">Click here</a> to reset your Plausible password.<br /><br />\nThis link will expire in 1 hour. If you don't use it by then, you can request another login link.\n", text_body: nil, headers: %{}, attachments: [], assigns: %{reset_link: "https://plausible.prod.hxxx/password/reset?token=SFMyNTY.g2gDdAAAAAF3BWVtYWlsbQAAABhhaW1lbi5zaWpvdW1pQGhhYml0LmltbW9uBgA0yNNblgFiAAFRgA.crRy_hPs5fCwWIjePMIwIGef__Zv8rq0NLRqQAM7v9E"}, private: %{tag: "password-reset-email", message_params: %{"MessageStream" => "priority", "TrackOpens" => false}, html_layout: false, text_layout: false, view_module: PlausibleWeb.EmailView, view_template: "password_reset_email.html"}, blocked: false}

...

04:44:13.405 [error] Task #PID<0.4489.0> started from #PID<0.4488.0> terminating
** (Mua.TransportError) timeout    
(bamboo 2.3.0) lib/bamboo/strategies/task_supervisor_strategy.ex:25: anonymous fn/3 in Bamboo.TaskSupervisorStrategy.deliver_later/3    
(elixir 1.16.0) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: #Function<0.95237244/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>    
Args: []
```

**Comment by asijoumi** [comment]
I change to that and now it works... 

```yml
- name: MAILER_ADAPTER
  value: "Bamboo.Mua"
- name: MAILER_EMAIL
  value: "{{ .Values.SMTP_USER_NAME }}"
- name: SMTP_HOST_ADDR
  value: "{{ .Values.SMTP_HOST_ADDR }}"
- name: SMTP_HOST_PORT
  value: "587"
- name: SMTP_USER_NAME
  value: "{{ .Values.SMTP_USER_NAME }}"
- name: SMTP_USER_PWD
  valueFrom:
    secretKeyRef:
      name: plausible-credentials
      key: smtp-user-pwd
```

Thank you for your help @ruslandoga 😄 .

I close this issue.
